use alef_backend_swift::SwiftBackend;
use alef_core::backend::Backend;
use alef_core::config::{ResolvedCrateConfig, new_config::NewAlefConfig};
use alef_core::ir::{
    ApiSurface, CoreWrapper, EnumDef, EnumVariant, ErrorDef, ErrorVariant, FieldDef, FunctionDef, ParamDef,
    PrimitiveType, TypeDef, TypeRef,
};

// ── helpers ─────────────────────────────────────────────────────────────────

fn make_field(name: &str, ty: TypeRef, optional: bool) -> FieldDef {
    FieldDef {
        name: name.to_string(),
        ty,
        optional,
        default: None,
        doc: String::new(),
        sanitized: false,
        is_boxed: false,
        type_rust_path: None,
        cfg: None,
        typed_default: None,
        core_wrapper: CoreWrapper::None,
        vec_inner_core_wrapper: CoreWrapper::None,
        newtype_wrapper: None,
        serde_rename: None,
        serde_flatten: false,
        binding_excluded: false,
        binding_exclusion_reason: None,
    }
}

fn make_param(name: &str, ty: TypeRef) -> ParamDef {
    ParamDef {
        name: name.to_string(),
        ty,
        optional: false,
        default: None,
        sanitized: false,
        typed_default: None,
        is_ref: false,
        is_mut: false,
        newtype_wrapper: None,
        original_type: None,
    }
}

fn make_type(name: &str, fields: Vec<FieldDef>) -> TypeDef {
    TypeDef {
        name: name.to_string(),
        rust_path: format!("demo::{name}"),
        original_rust_path: String::new(),
        fields,
        methods: vec![],
        is_opaque: false,
        is_clone: true,

        is_copy: false,
        doc: String::new(),
        cfg: None,
        is_trait: false,
        has_default: false,
        has_stripped_cfg_fields: false,
        is_return_type: false,
        serde_rename_all: None,
        has_serde: false,
        super_traits: vec![],
        binding_excluded: false,
        binding_exclusion_reason: None,
    }
}

fn make_config() -> ResolvedCrateConfig {
    let toml = r#"
[workspace]
languages = ["swift"]

[[crates]]
name = "demo-crate"
sources = ["src/lib.rs"]
"#;
    let cfg: NewAlefConfig = toml::from_str(toml).expect("test config must parse");
    cfg.resolve().expect("test config must resolve").remove(0)
}

// ── struct tests ─────────────────────────────────────────────────────────────

#[test]
fn struct_with_primitive_fields_emits_public_struct() {
    let ty = make_type(
        "Point",
        vec![
            make_field("x_coord", TypeRef::Primitive(PrimitiveType::I32), false),
            make_field("y_coord", TypeRef::Primitive(PrimitiveType::I32), false),
        ],
    );
    // Non-Codable structs become typealiases to RustBridge.X
    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![ty],
        functions: vec![],
        enums: vec![],
        errors: vec![],
        excluded_type_paths: ::std::collections::HashMap::new(),
    };

    let files = SwiftBackend.generate_bindings(&api, &make_config()).unwrap();
    // generate_bindings returns 1 Swift file + 3 Rust-crate files (Cargo.toml, src/lib.rs, build.rs)
    assert_eq!(files.len(), 4);
    let content = &files[0].content;

    assert!(
        content.contains("// Generated by alef. Do not edit by hand."),
        "missing header: {content}"
    );
    assert!(
        content.contains("import Foundation"),
        "missing Foundation import: {content}"
    );
    assert!(
        content.contains("public typealias Point = RustBridge.Point"),
        "missing typealias declaration: {content}"
    );
}

#[test]
fn struct_with_optional_array_and_dict_fields() {
    // Non-Codable structs become typealiases to RustBridge.X
    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![make_type(
            "Container",
            vec![
                make_field("tag", TypeRef::Optional(Box::new(TypeRef::String)), false),
                make_field("items", TypeRef::Vec(Box::new(TypeRef::String)), false),
                make_field(
                    "meta",
                    TypeRef::Map(
                        Box::new(TypeRef::String),
                        Box::new(TypeRef::Primitive(PrimitiveType::I64)),
                    ),
                    false,
                ),
            ],
        )],
        functions: vec![],
        enums: vec![],
        errors: vec![],
        excluded_type_paths: ::std::collections::HashMap::new(),
    };

    let files = SwiftBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;

    assert!(
        content.contains("public typealias Container = RustBridge.Container"),
        "missing typealias declaration: {content}"
    );
}

#[test]
fn struct_with_serde_derives_codable() {
    // All non-trait structs become typealiases to RustBridge.X
    let mut ty = make_type(
        "Config",
        vec![make_field("value", TypeRef::Primitive(PrimitiveType::I32), false)],
    );
    ty.has_serde = true;

    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![ty],
        functions: vec![],
        enums: vec![],
        errors: vec![],
        excluded_type_paths: ::std::collections::HashMap::new(),
    };

    let files = SwiftBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;

    assert!(
        content.contains("public typealias Config = RustBridge.Config"),
        "missing typealias declaration: {content}"
    );
}

#[test]
fn empty_struct_emits_single_line() {
    // Non-Codable structs become typealiases to RustBridge.X
    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![make_type("Empty", vec![])],
        functions: vec![],
        enums: vec![],
        errors: vec![],
        excluded_type_paths: ::std::collections::HashMap::new(),
    };

    let files = SwiftBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;

    assert!(
        content.contains("public typealias Empty = RustBridge.Empty"),
        "missing typealias declaration: {content}"
    );
}

// ── enum tests ────────────────────────────────────────────────────────────────

#[test]
fn unit_only_enum_emits_lower_camel_cases() {
    // Non-Codable enums become typealiases to RustBridge.X
    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![],
        functions: vec![],
        enums: vec![EnumDef {
            name: "Status".into(),
            rust_path: "demo::Status".into(),
            original_rust_path: String::new(),
            variants: vec![
                EnumVariant {
                    name: "Active".into(),
                    fields: vec![],
                    doc: String::new(),
                    is_default: false,
                    serde_rename: None,
                    is_tuple: false,
                },
                EnumVariant {
                    name: "Inactive".into(),
                    fields: vec![],
                    doc: String::new(),
                    is_default: false,
                    serde_rename: None,
                    is_tuple: false,
                },
            ],
            doc: String::new(),
            cfg: None,
            serde_tag: None,
            serde_untagged: false,
            serde_rename_all: None,

            is_copy: false,
            has_serde: false,
            binding_excluded: false,
            binding_exclusion_reason: None,
        }],
        errors: vec![],
        excluded_type_paths: ::std::collections::HashMap::new(),
    };

    let files = SwiftBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;

    assert!(
        content.contains("public typealias Status = RustBridge.Status"),
        "missing typealias declaration: {content}"
    );
}

#[test]
fn data_bearing_enum_emits_associated_values() {
    // Non-Codable enums become typealiases to RustBridge.X
    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![],
        functions: vec![],
        enums: vec![EnumDef {
            name: "Shape".into(),
            rust_path: "demo::Shape".into(),
            original_rust_path: String::new(),
            variants: vec![
                EnumVariant {
                    name: "Circle".into(),
                    fields: vec![make_field("radius", TypeRef::Primitive(PrimitiveType::F64), false)],
                    doc: String::new(),
                    is_default: false,
                    serde_rename: None,
                    is_tuple: false,
                },
                EnumVariant {
                    name: "Unit".into(),
                    fields: vec![],
                    doc: String::new(),
                    is_default: false,
                    serde_rename: None,
                    is_tuple: false,
                },
            ],
            doc: String::new(),
            cfg: None,
            serde_tag: None,
            serde_untagged: false,
            serde_rename_all: None,

            is_copy: false,
            has_serde: false,
            binding_excluded: false,
            binding_exclusion_reason: None,
        }],
        errors: vec![],
        excluded_type_paths: ::std::collections::HashMap::new(),
    };

    let files = SwiftBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;

    assert!(
        content.contains("public typealias Shape = RustBridge.Shape"),
        "missing typealias declaration: {content}"
    );
}

// ── function tests ────────────────────────────────────────────────────────────

#[test]
fn sync_function_emits_public_static_func() {
    let api = ApiSurface {
        crate_name: "demo-crate".into(),
        version: "0.1.0".into(),
        types: vec![],
        functions: vec![FunctionDef {
            name: "greet_user".into(),
            rust_path: "demo::greet_user".into(),
            original_rust_path: String::new(),
            params: vec![make_param("user_name", TypeRef::String)],
            return_type: TypeRef::Primitive(PrimitiveType::I32),
            is_async: false,
            error_type: None,
            doc: String::new(),
            cfg: None,
            sanitized: false,
            return_sanitized: false,
            returns_ref: false,
            returns_cow: false,
            return_newtype_wrapper: None,
            binding_excluded: false,
            binding_exclusion_reason: None,
        }],
        enums: vec![],
        errors: vec![],
        excluded_type_paths: ::std::collections::HashMap::new(),
    };

    let files = SwiftBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;

    // Function wrappers are disabled (Phase 2D). No module enum wrapper or static func emitted.
    assert!(
        !content.contains("public enum DemoCrate {"),
        "function wrappers should be disabled, no module enum wrapper: {content}"
    );
    assert!(
        !content.contains("public static func greetUser(userName: String)"),
        "function wrappers should be disabled, no static func: {content}"
    );
}

#[test]
fn async_function_emits_async_keyword() {
    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![],
        functions: vec![FunctionDef {
            name: "fetch_data".into(),
            rust_path: "demo::fetch_data".into(),
            original_rust_path: String::new(),
            params: vec![],
            return_type: TypeRef::String,
            is_async: true,
            error_type: None,
            doc: String::new(),
            cfg: None,
            sanitized: false,
            return_sanitized: false,
            returns_ref: false,
            returns_cow: false,
            return_newtype_wrapper: None,
            binding_excluded: false,
            binding_exclusion_reason: None,
        }],
        enums: vec![],
        errors: vec![],
        excluded_type_paths: ::std::collections::HashMap::new(),
    };

    let files = SwiftBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;

    // Function wrappers are disabled (Phase 2D). Async qualifiers not emitted.
    assert!(
        !content.contains("public static func fetchData() async"),
        "function wrappers disabled, no async static func: {content}"
    );
}

#[test]
fn error_throwing_function_emits_throws() {
    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![],
        functions: vec![FunctionDef {
            name: "parse_input".into(),
            rust_path: "demo::parse_input".into(),
            original_rust_path: String::new(),
            params: vec![make_param("raw", TypeRef::String)],
            return_type: TypeRef::Primitive(PrimitiveType::I32),
            is_async: false,
            error_type: Some("ParseError".into()),
            doc: String::new(),
            cfg: None,
            sanitized: false,
            return_sanitized: false,
            returns_ref: false,
            returns_cow: false,
            return_newtype_wrapper: None,
            binding_excluded: false,
            binding_exclusion_reason: None,
        }],
        enums: vec![],
        errors: vec![],
        excluded_type_paths: ::std::collections::HashMap::new(),
    };

    let files = SwiftBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;

    // Function wrappers are disabled (Phase 2D). Throws qualifiers not emitted.
    assert!(
        !content.contains("public static func parseInput(raw: String) throws"),
        "function wrappers disabled, no throws static func: {content}"
    );
}

#[test]
fn async_throws_function_emits_both_qualifiers() {
    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![],
        functions: vec![FunctionDef {
            name: "load".into(),
            rust_path: "demo::load".into(),
            original_rust_path: String::new(),
            params: vec![],
            return_type: TypeRef::String,
            is_async: true,
            error_type: Some("IoError".into()),
            doc: String::new(),
            cfg: None,
            sanitized: false,
            return_sanitized: false,
            returns_ref: false,
            returns_cow: false,
            return_newtype_wrapper: None,
            binding_excluded: false,
            binding_exclusion_reason: None,
        }],
        enums: vec![],
        errors: vec![],
        excluded_type_paths: ::std::collections::HashMap::new(),
    };

    let files = SwiftBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;

    // Function wrappers are disabled (Phase 2D). Async throws qualifiers not emitted.
    assert!(
        !content.contains("public static func load() async throws"),
        "function wrappers disabled, no async throws static func: {content}"
    );
}

// ── error tests ───────────────────────────────────────────────────────────────

#[test]
fn error_enum_conforms_to_error_protocol() {
    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![],
        functions: vec![],
        enums: vec![],
        errors: vec![ErrorDef {
            name: "ApiError".into(),
            rust_path: "demo::ApiError".into(),
            original_rust_path: String::new(),
            variants: vec![
                ErrorVariant {
                    name: "NotFound".into(),
                    message_template: Some("Resource not found".into()),
                    fields: vec![],
                    has_source: false,
                    has_from: false,
                    is_unit: true,
                    doc: String::new(),
                },
                ErrorVariant {
                    name: "Timeout".into(),
                    message_template: Some("Request timed out".into()),
                    fields: vec![],
                    has_source: false,
                    has_from: false,
                    is_unit: true,
                    doc: String::new(),
                },
            ],
            doc: String::new(),
            binding_excluded: false,
            binding_exclusion_reason: None,
        }],
        excluded_type_paths: ::std::collections::HashMap::new(),
    };

    let files = SwiftBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;

    assert!(
        content.contains("public enum ApiError: Swift.Error {"),
        "missing Swift.Error conformance: {content}"
    );
    assert!(content.contains("case notFound\n"), "missing notFound case: {content}");
    assert!(content.contains("case timeout\n"), "missing timeout case: {content}");
}

#[test]
fn error_enum_named_error_is_renamed_to_module_error() {
    // When the Rust error type is literally named `Error`, Swift parses
    // `public enum Error: Error` as a circular raw-type binding rather than
    // protocol conformance, causing compile errors. The codegen must rename it
    // to `{ModuleName}Error` (here `DemoCrateError`) and qualify the protocol
    // as `Swift.Error`.
    let api = ApiSurface {
        crate_name: "demo-crate".into(),
        version: "0.1.0".into(),
        types: vec![],
        functions: vec![],
        enums: vec![],
        errors: vec![ErrorDef {
            name: "Error".into(),
            rust_path: "demo_crate::Error".into(),
            original_rust_path: String::new(),
            variants: vec![ErrorVariant {
                name: "NotFound".into(),
                message_template: Some("not found".into()),
                fields: vec![],
                has_source: false,
                has_from: false,
                is_unit: true,
                doc: String::new(),
            }],
            doc: String::new(),
            binding_excluded: false,
            binding_exclusion_reason: None,
        }],
        excluded_type_paths: ::std::collections::HashMap::new(),
    };

    let files = SwiftBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;

    // Must NOT emit `public enum Error: Error` — that is a Swift compile error.
    assert!(
        !content.contains("public enum Error: Error"),
        "bare `Error: Error` must not be emitted: {content}"
    );
    // Must rename to `{ModuleName}Error` and qualify with `Swift.Error`.
    assert!(
        content.contains("public enum DemoCrateError: Swift.Error {"),
        "renamed enum must be emitted as `DemoCrateError: Swift.Error`: {content}"
    );
    assert!(content.contains("case notFound\n"), "missing notFound case: {content}");
}

// ── convenience wrapper tests ─────────────────────────────────────────────────

/// Helper: build a FunctionDef with no error type and not async.
fn make_sync_fn(name: &str, params: Vec<ParamDef>, return_type: TypeRef) -> FunctionDef {
    FunctionDef {
        name: name.to_string(),
        rust_path: format!("demo::{name}"),
        original_rust_path: String::new(),
        params,
        return_type,
        is_async: false,
        error_type: Some("DemoError".to_string()),
        doc: String::new(),
        cfg: None,
        sanitized: false,
        return_sanitized: false,
        returns_ref: false,
        returns_cow: false,
        return_newtype_wrapper: None,
        binding_excluded: false,
        binding_exclusion_reason: None,
    }
}

/// Helper: build an optional ParamDef.
fn make_optional_param(name: &str, ty: TypeRef) -> ParamDef {
    ParamDef {
        name: name.to_string(),
        ty,
        optional: true,
        default: None,
        sanitized: false,
        typed_default: None,
        is_ref: false,
        is_mut: false,
        newtype_wrapper: None,
        original_type: None,
    }
}

#[test]
fn bytes_first_param_skips_overload_when_name_shadows_bridge() {
    // IR: analyze_bytes(content: Bytes, config: AnalyzeConfig) -> AnalyzeResult
    // The convenience wrapper name (`analyzeBytes`) collides with the bridge
    // function name (`analyzeBytes`) because there is no `_sync` suffix to
    // strip. Swift overload resolution would resolve the unlabeled inner
    // positional call to the wrapper itself (recursive shadow), and module-
    // prefix qualification of free functions is rejected by the compiler. We
    // therefore skip emitting the convenience overload entirely; users call
    // the bridge function directly with `makeByteVec(...)`.
    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![],
        functions: vec![make_sync_fn(
            "analyze_bytes",
            vec![
                make_param("content", TypeRef::Bytes),
                make_param("config", TypeRef::Named("AnalyzeConfig".into())),
            ],
            TypeRef::Named("AnalyzeResult".into()),
        )],
        enums: vec![],
        errors: vec![],
        excluded_type_paths: ::std::collections::HashMap::new(),
    };

    let files = SwiftBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;

    // No convenience overload for `analyzeBytes` — the only function in the
    // surface would shadow itself.
    assert!(
        !content.contains("public func analyzeBytes(\n    content: String"),
        "shadowing String overload must be skipped: {content}"
    );
    assert!(
        !content.contains("public func analyzeBytes(\n    content: [UInt8]"),
        "shadowing [UInt8] overload must be skipped: {content}"
    );

    // Since this is the only candidate, no convenience-wrapper section header
    // should be emitted at all.
    assert!(
        !content.contains("// MARK: - Convenience Wrapper Functions"),
        "wrapper section must not appear when all candidates shadow: {content}"
    );
    assert!(
        !content.contains("makeByteVec"),
        "makeByteVec must not appear when all candidates shadow: {content}"
    );
}

#[test]
fn bytes_overload_with_string_return_does_not_append_to_string() {
    // IR: detect_mime_type_from_bytes_sync(content: Bytes) -> String
    //
    // Bug regression: prior versions appended `.toString()` to the inner call,
    // assuming swift-bridge mapped Rust `String` returns to `RustString`. In
    // fact swift-bridge maps `String` (and `Result<String, _>`) directly to a
    // Swift-native `String` — `.toString()` is a no-op at best and a compile
    // error against the actual Swift `String` type. The convenience overload
    // must return the bridge result verbatim.
    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![],
        functions: vec![make_sync_fn(
            "detect_mime_sync",
            vec![make_param("content", TypeRef::Bytes)],
            TypeRef::String,
        )],
        enums: vec![],
        errors: vec![],
        excluded_type_paths: ::std::collections::HashMap::new(),
    };

    let files = SwiftBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;

    // Wrapper exists (no shadow: `detectMime` ≠ `detectMimeSync`).
    assert!(
        content.contains("public func detectMime(\n    content: String"),
        "missing detectMime String overload: {content}"
    );

    // Bridge result is returned verbatim — no `.toString()` suffix.
    assert!(
        !content.contains(".toString()"),
        "must not append .toString() to a Swift `String` return: {content}"
    );

    // Inner call delegates to the suffixed bridge name without conversion.
    assert!(
        content.contains("return try detectMimeSync(makeByteVec(Array(content.utf8)))\n"),
        "inner call should return verbatim without conversion: {content}"
    );
}

#[test]
fn bytes_sync_suffix_stripped_in_wrapper_name() {
    // IR: process_bytes_sync(content: Bytes, config: ProcessConfig) -> ProcessResult
    // Wrapper name should be `processBytes` (strip "Sync"), inner call `processBytesSync`.
    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![],
        functions: vec![make_sync_fn(
            "process_bytes_sync",
            vec![
                make_param("content", TypeRef::Bytes),
                make_param("config", TypeRef::Named("ProcessConfig".into())),
            ],
            TypeRef::Named("ProcessResult".into()),
        )],
        enums: vec![],
        errors: vec![],
        excluded_type_paths: ::std::collections::HashMap::new(),
    };

    let files = SwiftBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;

    // Public wrapper is named `processBytes` (Sync stripped)
    assert!(
        content.contains("public func processBytes(\n    content: String"),
        "missing String overload with Sync stripped: {content}"
    );
    assert!(
        content.contains("public func processBytes(\n    content: [UInt8]"),
        "missing [UInt8] overload with Sync stripped: {content}"
    );
    // Inner call delegates to `processBytesSync`
    assert!(
        content.contains("return try processBytesSync(makeByteVec("),
        "inner call should use processBytesSync: {content}"
    );
}

#[test]
fn path_first_param_emits_string_path_overload() {
    // IR: load_file_sync(path: Path, mime_type: String (optional), cfg: LoadConfig) -> LoadResult
    // Should emit a `loadFile` wrapper accepting `path: String`.
    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![],
        functions: vec![make_sync_fn(
            "load_file_sync",
            vec![
                make_param("path", TypeRef::Path),
                make_optional_param("mime_type", TypeRef::String),
                make_param("cfg", TypeRef::Named("LoadConfig".into())),
            ],
            TypeRef::Named("LoadResult".into()),
        )],
        enums: vec![],
        errors: vec![],
        excluded_type_paths: ::std::collections::HashMap::new(),
    };

    let files = SwiftBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;

    // Public wrapper is `loadFile` (Sync stripped)
    assert!(
        content.contains("public func loadFile(\n    path: String"),
        "missing String path overload for loadFile: {content}"
    );
    // Inner call delegates to `loadFileSync`
    assert!(
        content.contains("return try loadFileSync(path"),
        "inner call should use loadFileSync: {content}"
    );
    // Optional mime_type gets `= nil` default
    assert!(
        content.contains("mimeType: String? = nil"),
        "optional mime_type should have nil default: {content}"
    );
}

#[test]
fn no_bytes_or_path_functions_emits_no_wrapper_section() {
    // IR with only a String-param function — no convenience wrappers should be emitted.
    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![],
        functions: vec![make_sync_fn(
            "greet",
            vec![make_param("name", TypeRef::String)],
            TypeRef::String,
        )],
        enums: vec![],
        errors: vec![],
        excluded_type_paths: ::std::collections::HashMap::new(),
    };

    let files = SwiftBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;

    assert!(
        !content.contains("// MARK: - Convenience Wrapper Functions"),
        "wrapper section must not appear when no bytes/path candidates: {content}"
    );
    assert!(
        !content.contains("makeByteVec"),
        "makeByteVec must not appear when no bytes candidates: {content}"
    );
}

#[test]
fn async_bytes_function_is_not_a_candidate() {
    // Async functions are not candidates — they cannot be wrapped with a simple sync call.
    let async_fn = FunctionDef {
        name: "fetch_bytes".to_string(),
        rust_path: "demo::fetch_bytes".to_string(),
        original_rust_path: String::new(),
        params: vec![
            make_param("content", TypeRef::Bytes),
            make_param("config", TypeRef::Named("FetchConfig".into())),
        ],
        return_type: TypeRef::Named("FetchResult".into()),
        is_async: true,
        error_type: None,
        doc: String::new(),
        cfg: None,
        sanitized: false,
        return_sanitized: false,
        returns_ref: false,
        returns_cow: false,
        return_newtype_wrapper: None,
        binding_excluded: false,
        binding_exclusion_reason: None,
    };

    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![],
        functions: vec![async_fn],
        enums: vec![],
        errors: vec![],
        excluded_type_paths: ::std::collections::HashMap::new(),
    };

    let files = SwiftBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;

    assert!(
        !content.contains("public func fetchBytes"),
        "async bytes function must not generate a convenience overload: {content}"
    );
}

// ── output path tests ─────────────────────────────────────────────────────────

#[test]
fn output_path_uses_pascal_case_module_name() {
    let api = ApiSurface {
        crate_name: "demo-crate".into(),
        version: "0.1.0".into(),
        types: vec![],
        functions: vec![],
        enums: vec![],
        errors: vec![],
        excluded_type_paths: ::std::collections::HashMap::new(),
    };

    let files = SwiftBackend.generate_bindings(&api, &make_config()).unwrap();
    // generate_bindings returns 1 Swift file + 3 Rust-crate files (Cargo.toml, src/lib.rs, build.rs)
    assert_eq!(files.len(), 4);

    // The Swift wrapper must be a .swift file with PascalCase module name.
    // When using ResolvedCrateConfig, output_paths["swift"] is set from the template
    // to packages/swift/, so the file lands at packages/swift/DemoCrate.swift.
    let swift_file = files
        .iter()
        .find(|f| f.path.to_string_lossy().ends_with(".swift"))
        .unwrap();
    let path = swift_file.path.to_string_lossy();
    assert!(path.contains("DemoCrate.swift"), "unexpected output path: {path}");
}

// ── streaming-method emission tests ──────────────────────────────────────────

/// Helper: build a `ResolvedCrateConfig` with one streaming adapter on
/// `DefaultClient` plus a `client_constructor_body` override (required to make
/// `emit_client_class` consider the owner type).
fn make_streaming_config() -> ResolvedCrateConfig {
    let toml = r#"
[workspace]
languages = ["swift"]

[[crates]]
name = "demo-crate"
sources = ["src/lib.rs"]

[[crates.adapters]]
name = "chat_stream"
pattern = "streaming"
core_path = "demo_crate::chat_stream"
owner_type = "DefaultClient"
item_type = "ChatCompletionChunk"
error_type = "DemoError"

[[crates.adapters.params]]
name = "req"
type = "demo_crate::ChatCompletionRequest"

[crates.swift]
client_constructor_body.DefaultClient = "Self { inner: ::demo_crate::DefaultClient::new(api_key, base_url) }"
"#;
    let cfg: NewAlefConfig = toml::from_str(toml).expect("test config must parse");
    cfg.resolve().expect("test config must resolve").remove(0)
}

/// Build an `ApiSurface` exposing `DefaultClient` as an opaque type so the
/// gen_bindings pipeline emits a public Swift class wrapper for it.
fn make_streaming_api() -> ApiSurface {
    use alef_core::ir::{MethodDef, ReceiverKind};
    ApiSurface {
        crate_name: "demo-crate".into(),
        version: "0.1.0".into(),
        types: vec![TypeDef {
            name: "DefaultClient".to_string(),
            rust_path: "demo_crate::DefaultClient".to_string(),
            original_rust_path: String::new(),
            fields: vec![],
            methods: vec![MethodDef {
                name: "ping".to_string(),
                params: vec![],
                return_type: TypeRef::String,
                is_async: false,
                is_static: false,
                error_type: None,
                doc: String::new(),
                sanitized: false,
                returns_ref: false,
                returns_cow: false,
                return_newtype_wrapper: None,
                receiver: Some(ReceiverKind::Ref),
                trait_source: None,
                has_default_impl: false,
                binding_excluded: false,
                binding_exclusion_reason: None,
            }],
            is_opaque: true,
            is_clone: false,
            is_copy: false,
            is_trait: false,
            has_default: false,
            has_stripped_cfg_fields: false,
            is_return_type: false,
            serde_rename_all: None,
            has_serde: false,
            super_traits: vec![],
            doc: String::new(),
            cfg: None,
            binding_excluded: false,
            binding_exclusion_reason: None,
        }],
        functions: vec![],
        enums: vec![],
        errors: vec![],
        excluded_type_paths: ::std::collections::HashMap::new(),
    }
}

/// The streaming wrapper must return an `AsyncThrowingStream<Item, Error>` so
/// Swift consumers can drive it with `for try await chunk in stream`.
#[test]
fn streaming_adapter_emits_async_throwing_stream_wrapper() {
    let api = make_streaming_api();
    let config = make_streaming_config();
    let files = SwiftBackend.generate_bindings(&api, &config).unwrap();
    let swift = files
        .iter()
        .find(|f| f.path.to_string_lossy().ends_with(".swift"))
        .unwrap();

    assert!(
        swift.content.contains(
            "public func chatStream(_ req: ChatCompletionRequest) async throws -> AsyncThrowingStream<ChatCompletionChunk, Error>"
        ),
        "streaming wrapper must declare AsyncThrowingStream return type; got:\n{}",
        swift.content
    );
    assert!(
        swift.content.contains("RustBridge.defaultClientChatStreamStart(inner"),
        "streaming wrapper must call defaultClientChatStreamStart with the owner handle; got:\n{}",
        swift.content
    );
    // Must drain via handle.next() in a detached task.
    assert!(
        swift.content.contains("handle.next().toString()"),
        "streaming wrapper must drain via handle.next(); got:\n{}",
        swift.content
    );
    // Must terminate cleanly on the empty-string EOF sentinel.
    assert!(
        swift.content.contains("if json.isEmpty { break }"),
        "streaming wrapper must break on empty-string EOF sentinel; got:\n{}",
        swift.content
    );
    // Must JSON-decode each chunk into the configured item type.
    assert!(
        swift
            .content
            .contains("decoder.decode(ChatCompletionChunk.self, from: data)"),
        "streaming wrapper must JSON-decode each chunk; got:\n{}",
        swift.content
    );
    // Must cancel the drain task on stream termination so the Rust handle's deinit runs.
    assert!(
        swift
            .content
            .contains("continuation.onTermination = { _ in task.cancel() }"),
        "streaming wrapper must cancel the drain task onTermination; got:\n{}",
        swift.content
    );
}

/// Capability flag must reflect the new streaming support so downstream tooling
/// (alef CLI, e2e generators) emits Swift streaming fixtures.
#[test]
fn swift_backend_reports_supports_streaming_true() {
    let backend = SwiftBackend;
    let capabilities = alef_core::backend::Backend::capabilities(&backend);
    assert!(
        capabilities.supports_streaming,
        "SwiftBackend must report supports_streaming = true now that AsyncThrowingStream is implemented"
    );
}

// ── Defect 1: StreamHandle @unchecked Sendable ───────────────────────────────

/// Each streaming adapter's `{Owner}{Adapter}StreamHandle` must have an
/// `extension RustBridge.XStreamHandle: @unchecked Sendable {}` emitted in the
/// generated Swift file.
///
/// Swift 6 strict-concurrency rejects passing non-Sendable types across
/// `Task.detached` boundaries.  The Rust side wraps `Mutex<stream>` and a
/// `tokio::runtime::Runtime` — both thread-safe — so `@unchecked Sendable` is
/// the correct annotation.
#[test]
fn streaming_handle_emits_unchecked_sendable_extension() {
    let api = make_streaming_api();
    let config = make_streaming_config();
    let files = SwiftBackend.generate_bindings(&api, &config).unwrap();
    let swift = files
        .iter()
        .find(|f| f.path.to_string_lossy().ends_with(".swift"))
        .unwrap();

    assert!(
        swift
            .content
            .contains("extension RustBridge.DefaultClientChatStreamStreamHandle: @unchecked Sendable {}"),
        "generated Swift must declare @unchecked Sendable for the StreamHandle so Swift 6 \
         strict-concurrency allows passing it across Task.detached boundaries; got:\n{}",
        swift.content
    );
}

// ── Defect 2: streaming chunk type emits as Codable struct ───────────────────

/// When the streaming adapter's `item_type` appears in `api.types` with
/// `has_serde: true` and populated fields, the Swift backend must emit a native
/// `public struct X: Codable { … }` instead of an opaque typealias.
///
/// The streaming wrapper calls `JSONDecoder().decode(X.self, from: data)`, which
/// requires `X: Decodable`.  An `RustBridge.X` typealias (swift-bridge opaque
/// class) does not satisfy that requirement.
#[test]
fn streaming_chunk_type_with_serde_and_fields_emits_codable_struct() {
    use alef_core::ir::{MethodDef, ReceiverKind};

    // Build an API surface with:
    // - DefaultClient (opaque, has_serde: false) — the streaming owner
    // - ChatCompletionChunk (non-opaque, has_serde: true, with fields) — the item type
    let api = ApiSurface {
        crate_name: "demo-crate".into(),
        version: "0.1.0".into(),
        types: vec![
            TypeDef {
                name: "DefaultClient".to_string(),
                rust_path: "demo_crate::DefaultClient".to_string(),
                original_rust_path: String::new(),
                fields: vec![],
                methods: vec![MethodDef {
                    name: "ping".to_string(),
                    params: vec![],
                    return_type: TypeRef::String,
                    is_async: false,
                    is_static: false,
                    error_type: None,
                    doc: String::new(),
                    sanitized: false,
                    returns_ref: false,
                    returns_cow: false,
                    return_newtype_wrapper: None,
                    receiver: Some(ReceiverKind::Ref),
                    trait_source: None,
                    has_default_impl: false,
                    binding_excluded: false,
                    binding_exclusion_reason: None,
                }],
                is_opaque: true,
                is_clone: false,
                is_copy: false,
                is_trait: false,
                has_default: false,
                has_stripped_cfg_fields: false,
                is_return_type: false,
                serde_rename_all: None,
                has_serde: false,
                super_traits: vec![],
                doc: String::new(),
                cfg: None,
                binding_excluded: false,
                binding_exclusion_reason: None,
            },
            TypeDef {
                name: "ChatCompletionChunk".to_string(),
                rust_path: "demo_crate::ChatCompletionChunk".to_string(),
                original_rust_path: String::new(),
                fields: vec![
                    make_field("id", TypeRef::String, false),
                    make_field("content", TypeRef::Optional(Box::new(TypeRef::String)), true),
                ],
                methods: vec![],
                is_opaque: false,
                is_clone: true,
                is_copy: false,
                is_trait: false,
                has_default: false,
                has_stripped_cfg_fields: false,
                is_return_type: true,
                serde_rename_all: None,
                // has_serde: true — the type derives Serialize + Deserialize
                has_serde: true,
                super_traits: vec![],
                doc: String::new(),
                cfg: None,
                binding_excluded: false,
                binding_exclusion_reason: None,
            },
        ],
        functions: vec![],
        enums: vec![],
        errors: vec![],
        excluded_type_paths: ::std::collections::HashMap::new(),
    };

    let toml = r#"
[workspace]
languages = ["swift"]

[[crates]]
name = "demo-crate"
sources = ["src/lib.rs"]

[[crates.adapters]]
name = "chat_stream"
pattern = "streaming"
core_path = "demo_crate::chat_stream"
owner_type = "DefaultClient"
item_type = "ChatCompletionChunk"
error_type = "DemoError"

[[crates.adapters.params]]
name = "req"
type = "demo_crate::ChatCompletionRequest"

[crates.swift]
client_constructor_body.DefaultClient = "Self { inner: ::demo_crate::DefaultClient::new(api_key, base_url) }"
"#;
    let cfg: NewAlefConfig = toml::from_str(toml).expect("test config must parse");
    let config = cfg.resolve().expect("test config must resolve").remove(0);
    let files = SwiftBackend.generate_bindings(&api, &config).unwrap();
    let swift = files
        .iter()
        .find(|f| f.path.to_string_lossy().ends_with(".swift"))
        .unwrap();

    // Must emit a native Codable struct — NOT a typealias to RustBridge.ChatCompletionChunk.
    assert!(
        swift.content.contains("public struct ChatCompletionChunk: Codable"),
        "streaming item type with has_serde: true + fields must emit as Codable struct; got:\n{}",
        swift.content
    );
    // The typealias must NOT be emitted — it would shadow the Codable struct and break decoding.
    assert!(
        !swift
            .content
            .contains("typealias ChatCompletionChunk = RustBridge.ChatCompletionChunk"),
        "streaming item type with has_serde: true + fields must NOT emit as typealias; got:\n{}",
        swift.content
    );
    // Fields must be present.
    assert!(
        swift.content.contains("public var id: String"),
        "Codable struct must include non-optional fields; got:\n{}",
        swift.content
    );
    assert!(
        swift.content.contains("public var content: String?"),
        "Codable struct must include optional fields with ? suffix; got:\n{}",
        swift.content
    );
}
