use alef_backend_swift::SwiftBackend;
use alef_core::backend::Backend;
use alef_core::config::{AlefConfig, CrateConfig};
use alef_core::ir::{
    ApiSurface, CoreWrapper, EnumDef, EnumVariant, ErrorDef, ErrorVariant, FieldDef, FunctionDef, ParamDef,
    PrimitiveType, TypeDef, TypeRef,
};

// ── helpers ─────────────────────────────────────────────────────────────────

fn make_field(name: &str, ty: TypeRef, optional: bool) -> FieldDef {
    FieldDef {
        name: name.to_string(),
        ty,
        optional,
        default: None,
        doc: String::new(),
        sanitized: false,
        is_boxed: false,
        type_rust_path: None,
        cfg: None,
        typed_default: None,
        core_wrapper: CoreWrapper::None,
        vec_inner_core_wrapper: CoreWrapper::None,
        newtype_wrapper: None,
    }
}

fn make_param(name: &str, ty: TypeRef) -> ParamDef {
    ParamDef {
        name: name.to_string(),
        ty,
        optional: false,
        default: None,
        sanitized: false,
        typed_default: None,
        is_ref: false,
        is_mut: false,
        newtype_wrapper: None,
        original_type: None,
    }
}

fn make_type(name: &str, fields: Vec<FieldDef>) -> TypeDef {
    TypeDef {
        name: name.to_string(),
        rust_path: format!("demo::{name}"),
        original_rust_path: String::new(),
        fields,
        methods: vec![],
        is_opaque: false,
        is_clone: true,

        is_copy: false,
        doc: String::new(),
        cfg: None,
        is_trait: false,
        has_default: false,
        has_stripped_cfg_fields: false,
        is_return_type: false,
        serde_rename_all: None,
        has_serde: false,
        super_traits: vec![],
    }
}

fn make_config() -> AlefConfig {
    AlefConfig {
        version: None,
        crate_config: CrateConfig {
            name: "demo-crate".to_string(),
            sources: vec![],
            version_from: "Cargo.toml".to_string(),
            core_import: None,
            workspace_root: None,
            skip_core_import: false,
            features: vec![],
            path_mappings: std::collections::HashMap::new(),
            auto_path_mappings: Default::default(),
            extra_dependencies: Default::default(),
            source_crates: vec![],
            error_type: None,
            error_constructor: None,
        },
        languages: vec![],
        exclude: Default::default(),
        include: Default::default(),
        output: Default::default(),
        python: None,
        node: None,
        ruby: None,
        php: None,
        elixir: None,
        wasm: None,
        ffi: None,
        gleam: None,
        go: None,
        java: None,
        kotlin: None,
        dart: None,
        swift: None,
        csharp: None,
        r: None,
        zig: None,
        scaffold: None,
        readme: None,
        lint: None,
        update: None,
        test: None,
        setup: None,
        clean: None,
        build_commands: None,
        publish: None,
        custom_files: None,
        adapters: vec![],
        custom_modules: alef_core::config::CustomModulesConfig::default(),
        custom_registrations: alef_core::config::CustomRegistrationsConfig::default(),
        opaque_types: std::collections::HashMap::new(),
        generate: alef_core::config::GenerateConfig::default(),
        generate_overrides: std::collections::HashMap::new(),
        dto: Default::default(),
        sync: None,
        e2e: None,
        trait_bridges: vec![],
        tools: alef_core::config::ToolsConfig::default(),
    format: ::alef_core::config::FormatConfig::default(),
    format_overrides: ::std::collections::HashMap::new(),
    }
}

// ── struct tests ─────────────────────────────────────────────────────────────

#[test]
fn struct_with_primitive_fields_emits_public_struct() {
    let mut ty = make_type(
        "Point",
        vec![
            make_field("x_coord", TypeRef::Primitive(PrimitiveType::I32), false),
            make_field("y_coord", TypeRef::Primitive(PrimitiveType::I32), false),
        ],
    );
    // Non-Codable structs become typealiases to RustBridge.X
    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![ty],
        functions: vec![],
        enums: vec![],
        errors: vec![],
    };

    let files = SwiftBackend.generate_bindings(&api, &make_config()).unwrap();
    // generate_bindings returns 1 Swift file + 3 Rust-crate files (Cargo.toml, src/lib.rs, build.rs)
    assert_eq!(files.len(), 4);
    let content = &files[0].content;

    assert!(
        content.contains("// Generated by alef. Do not edit by hand."),
        "missing header: {content}"
    );
    assert!(content.contains("import Foundation"), "missing Foundation import: {content}");
    assert!(content.contains("public typealias Point = RustBridge.Point"), "missing typealias declaration: {content}");
}

#[test]
fn struct_with_optional_array_and_dict_fields() {
    // Non-Codable structs become typealiases to RustBridge.X
    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![make_type(
            "Container",
            vec![
                make_field("tag", TypeRef::Optional(Box::new(TypeRef::String)), false),
                make_field("items", TypeRef::Vec(Box::new(TypeRef::String)), false),
                make_field(
                    "meta",
                    TypeRef::Map(Box::new(TypeRef::String), Box::new(TypeRef::Primitive(PrimitiveType::I64))),
                    false,
                ),
            ],
        )],
        functions: vec![],
        enums: vec![],
        errors: vec![],
    };

    let files = SwiftBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;

    assert!(content.contains("public typealias Container = RustBridge.Container"), "missing typealias declaration: {content}");
}

#[test]
fn struct_with_serde_derives_codable() {
    // All non-trait structs become typealiases to RustBridge.X
    let mut ty = make_type(
        "Config",
        vec![make_field("value", TypeRef::Primitive(PrimitiveType::I32), false)],
    );
    ty.has_serde = true;

    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![ty],
        functions: vec![],
        enums: vec![],
        errors: vec![],
    };

    let files = SwiftBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;

    assert!(
        content.contains("public typealias Config = RustBridge.Config"),
        "missing typealias declaration: {content}"
    );
}

#[test]
fn empty_struct_emits_single_line() {
    // Non-Codable structs become typealiases to RustBridge.X
    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![make_type("Empty", vec![])],
        functions: vec![],
        enums: vec![],
        errors: vec![],
    };

    let files = SwiftBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;

    assert!(content.contains("public typealias Empty = RustBridge.Empty"), "missing typealias declaration: {content}");
}

// ── enum tests ────────────────────────────────────────────────────────────────

#[test]
fn unit_only_enum_emits_lower_camel_cases() {
    // Non-Codable enums become typealiases to RustBridge.X
    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![],
        functions: vec![],
        enums: vec![EnumDef {
            name: "Status".into(),
            rust_path: "demo::Status".into(),
            original_rust_path: String::new(),
            variants: vec![
                EnumVariant {
                    name: "Active".into(),
                    fields: vec![],
                    doc: String::new(),
                    is_default: false,
                    serde_rename: None,
                is_tuple: false,
                },
                EnumVariant {
                    name: "Inactive".into(),
                    fields: vec![],
                    doc: String::new(),
                    is_default: false,
                    serde_rename: None,
                is_tuple: false,
                },
            ],
            doc: String::new(),
            cfg: None,
            serde_tag: None,
            serde_rename_all: None,

            is_copy: false,
            has_serde: false,
        }],
        errors: vec![],
    };

    let files = SwiftBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;

    assert!(content.contains("public typealias Status = RustBridge.Status"), "missing typealias declaration: {content}");
}

#[test]
fn data_bearing_enum_emits_associated_values() {
    // Non-Codable enums become typealiases to RustBridge.X
    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![],
        functions: vec![],
        enums: vec![EnumDef {
            name: "Shape".into(),
            rust_path: "demo::Shape".into(),
            original_rust_path: String::new(),
            variants: vec![
                EnumVariant {
                    name: "Circle".into(),
                    fields: vec![make_field("radius", TypeRef::Primitive(PrimitiveType::F64), false)],
                    doc: String::new(),
                    is_default: false,
                    serde_rename: None,
                is_tuple: false,
                },
                EnumVariant {
                    name: "Unit".into(),
                    fields: vec![],
                    doc: String::new(),
                    is_default: false,
                    serde_rename: None,
                is_tuple: false,
                },
            ],
            doc: String::new(),
            cfg: None,
            serde_tag: None,
            serde_rename_all: None,

            is_copy: false,
            has_serde: false,
        }],
        errors: vec![],
    };

    let files = SwiftBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;

    assert!(content.contains("public typealias Shape = RustBridge.Shape"), "missing typealias declaration: {content}");
}

// ── function tests ────────────────────────────────────────────────────────────

#[test]
fn sync_function_emits_public_static_func() {
    let api = ApiSurface {
        crate_name: "demo-crate".into(),
        version: "0.1.0".into(),
        types: vec![],
        functions: vec![FunctionDef {
            name: "greet_user".into(),
            rust_path: "demo::greet_user".into(),
            original_rust_path: String::new(),
            params: vec![make_param("user_name", TypeRef::String)],
            return_type: TypeRef::Primitive(PrimitiveType::I32),
            is_async: false,
            error_type: None,
            doc: String::new(),
            cfg: None,
            sanitized: false,
            return_sanitized: false,
            returns_ref: false,
            returns_cow: false,
            return_newtype_wrapper: None,
        }],
        enums: vec![],
        errors: vec![],
    };

    let files = SwiftBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;

    // Module namespace
    assert!(
        content.contains("public enum DemoCrate {"),
        "missing module enum wrapper: {content}"
    );
    // Function signature
    assert!(
        content.contains("public static func greetUser(userName: String)"),
        "missing function signature: {content}"
    );
    assert!(content.contains("-> Int32"), "missing return type: {content}");
    // Bridge body delegates to RustBridge generated module
    assert!(
        content.contains("return RustBridge.greetUser("),
        "missing RustBridge delegation: {content}"
    );
    assert!(
        content.contains("import RustBridge"),
        "missing RustBridge import: {content}"
    );
}

#[test]
fn async_function_emits_async_keyword() {
    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![],
        functions: vec![FunctionDef {
            name: "fetch_data".into(),
            rust_path: "demo::fetch_data".into(),
            original_rust_path: String::new(),
            params: vec![],
            return_type: TypeRef::String,
            is_async: true,
            error_type: None,
            doc: String::new(),
            cfg: None,
            sanitized: false,
            return_sanitized: false,
            returns_ref: false,
            returns_cow: false,
            return_newtype_wrapper: None,
        }],
        enums: vec![],
        errors: vec![],
    };

    let files = SwiftBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;

    assert!(
        content.contains("public static func fetchData() async"),
        "missing async qualifier: {content}"
    );
    assert!(!content.contains("suspend"), "should not have Kotlin 'suspend': {content}");
}

#[test]
fn error_throwing_function_emits_throws() {
    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![],
        functions: vec![FunctionDef {
            name: "parse_input".into(),
            rust_path: "demo::parse_input".into(),
            original_rust_path: String::new(),
            params: vec![make_param("raw", TypeRef::String)],
            return_type: TypeRef::Primitive(PrimitiveType::I32),
            is_async: false,
            error_type: Some("ParseError".into()),
            doc: String::new(),
            cfg: None,
            sanitized: false,
            return_sanitized: false,
            returns_ref: false,
            returns_cow: false,
            return_newtype_wrapper: None,
        }],
        enums: vec![],
        errors: vec![],
    };

    let files = SwiftBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;

    assert!(
        content.contains("public static func parseInput(raw: String) throws"),
        "missing throws qualifier: {content}"
    );
    assert!(content.contains("-> Int32"), "missing return type: {content}");
}

#[test]
fn async_throws_function_emits_both_qualifiers() {
    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![],
        functions: vec![FunctionDef {
            name: "load".into(),
            rust_path: "demo::load".into(),
            original_rust_path: String::new(),
            params: vec![],
            return_type: TypeRef::String,
            is_async: true,
            error_type: Some("IoError".into()),
            doc: String::new(),
            cfg: None,
            sanitized: false,
            return_sanitized: false,
            returns_ref: false,
            returns_cow: false,
            return_newtype_wrapper: None,
        }],
        enums: vec![],
        errors: vec![],
    };

    let files = SwiftBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;

    assert!(
        content.contains("public static func load() async throws"),
        "missing async throws: {content}"
    );
}

// ── error tests ───────────────────────────────────────────────────────────────

#[test]
fn error_enum_conforms_to_error_protocol() {
    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![],
        functions: vec![],
        enums: vec![],
        errors: vec![ErrorDef {
            name: "ApiError".into(),
            rust_path: "demo::ApiError".into(),
            original_rust_path: String::new(),
            variants: vec![
                ErrorVariant {
                    name: "NotFound".into(),
                    message_template: Some("Resource not found".into()),
                    fields: vec![],
                    has_source: false,
                    has_from: false,
                    is_unit: true,
                    doc: String::new(),
                },
                ErrorVariant {
                    name: "Timeout".into(),
                    message_template: Some("Request timed out".into()),
                    fields: vec![],
                    has_source: false,
                    has_from: false,
                    is_unit: true,
                    doc: String::new(),
                },
            ],
            doc: String::new(),
        }],
    };

    let files = SwiftBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;

    assert!(
        content.contains("public enum ApiError: Error {"),
        "missing Error conformance: {content}"
    );
    assert!(
        content.contains("case notFound(message: String)"),
        "missing notFound case: {content}"
    );
    assert!(
        content.contains("case timeout(message: String)"),
        "missing timeout case: {content}"
    );
}

// ── output path tests ─────────────────────────────────────────────────────────

#[test]
fn output_path_uses_pascal_case_module_name() {
    let api = ApiSurface {
        crate_name: "demo-crate".into(),
        version: "0.1.0".into(),
        types: vec![],
        functions: vec![],
        enums: vec![],
        errors: vec![],
    };

    let files = SwiftBackend.generate_bindings(&api, &make_config()).unwrap();
    // generate_bindings returns 1 Swift file + 3 Rust-crate files (Cargo.toml, src/lib.rs, build.rs)
    assert_eq!(files.len(), 4);

    // The first file is always the Swift wrapper
    let path = files[0].path.to_string_lossy();
    assert!(
        path.contains("Sources/DemoCrate/DemoCrate.swift"),
        "unexpected output path: {path}"
    );
}
