pub(crate) mod adopt_command;
pub(crate) mod all_commands;
pub(crate) mod args;
pub(crate) mod aux_commands;
pub(crate) mod build_info;
pub(crate) mod component_commands;
pub(crate) mod core_commands;
pub(crate) mod dispatch;
pub(crate) mod helpers;
pub(crate) mod output;
pub(crate) mod publish_commands;
pub(crate) mod release_commands;
pub(crate) mod snippet_migration;
/// Public so `cargo test --lib` can exercise the same file `build.rs` compiles via `#[path]`. ~keep
pub mod tree_state;
mod verify_coverage;
mod verify_gitignore;
mod verify_orphans;
mod verify_outcome;
mod verify_scan;
mod verify_schema;
pub(crate) mod version_pin_sync;
