//! JNI shim code generator.
//!
//! Emits a single `lib.rs` into the consumer's `<crate>-jni` Rust crate.  The
//! emitted file exports `pub unsafe extern "system" fn Java_*` symbols that
//! satisfy every `external fun native*` declaration produced by
//! `alef-backend-kotlin-android`.
//!
//! # Symbol naming — JNI spec §5.11.3
//!
//! `Java_<package_underscored>_<Class>_<method>`
//!
//! Underscores inside any identifier segment are encoded as `_1`.  Package
//! dots become `_`.  The helpers in [`alef_core::jni`] own the canonical
//! encoding so this backend and the Kotlin backend can never drift apart.

use std::path::PathBuf;

use alef_core::backend::{Backend, BuildConfig, BuildDependency, Capabilities, GeneratedFile};
use alef_core::config::{AdapterPattern, Language, ResolvedCrateConfig};
use alef_core::ir::{ApiSurface, PrimitiveType, TypeDef, TypeRef};
use alef_core::jni::{bridge_class_name, bridge_method_name, destructor_method_name, jni_symbol, streaming_method_names};

/// Backend that emits the Rust JNI shim crate source.
#[derive(Debug, Default, Clone, Copy)]
pub struct JniBackend;

impl Backend for JniBackend {
    fn name(&self) -> &str {
        "jni"
    }

    fn language(&self) -> Language {
        Language::Jni
    }

    fn capabilities(&self) -> Capabilities {
        Capabilities {
            supports_async: true,
            supports_classes: true,
            supports_enums: false,
            supports_option: true,
            supports_result: true,
            supports_callbacks: false,
            supports_streaming: true,
        }
    }

    fn generate_bindings(&self, api: &ApiSurface, config: &ResolvedCrateConfig) -> anyhow::Result<Vec<GeneratedFile>> {
        let output_path = jni_output_path(config);
        let content = emit_lib_rs(api, config);
        Ok(vec![GeneratedFile {
            path: output_path,
            content,
            generated_header: true,
        }])
    }

    fn build_config(&self) -> Option<BuildConfig> {
        Some(BuildConfig {
            tool: "cargo",
            crate_suffix: "jni",
            build_dep: BuildDependency::Ffi,
            post_build: vec![],
        })
    }
}

// ---------------------------------------------------------------------------
// Output path resolution
// ---------------------------------------------------------------------------

/// Default output directory: `crates/<crate-name>-jni/src/lib.rs`
fn jni_output_path(config: &ResolvedCrateConfig) -> PathBuf {
    let jni_crate = format!("{}-jni", config.name);
    PathBuf::from(format!("crates/{jni_crate}/src/lib.rs"))
}

// ---------------------------------------------------------------------------
// Top-level emitter
// ---------------------------------------------------------------------------

/// Emit the full `lib.rs` content for the JNI shim crate.
pub(crate) fn emit_lib_rs(api: &ApiSurface, config: &ResolvedCrateConfig) -> String {
    let package = jni_kotlin_package(config);
    let bridge = bridge_class_name(&config.name);
    let core_crate = core_use_path(config);

    let mut out = String::new();

    // File header.
    out.push_str("// Generated by alef. Do not edit by hand.\n");
    out.push_str("//\n");
    out.push_str("// JNI shim for the Android AAR.  Every `pub unsafe extern \"system\" fn`\n");
    out.push_str("// here matches one `external fun native*` in the paired Kotlin Bridge object.\n");
    out.push('\n');
    out.push_str("#![allow(non_snake_case)]\n");
    out.push_str("#![allow(clippy::too_many_arguments)]\n");
    out.push('\n');
    out.push_str("use jni::JNIEnv;\n");
    out.push_str("use jni::objects::{JClass, JString};\n");
    out.push_str("use jni::sys::{jboolean, jbyte, jdouble, jfloat, jint, jlong, jshort};\n");
    out.push_str(&format!("use {core_crate};\n"));
    out.push('\n');

    // Collect visible top-level functions.
    let exclude_functions: std::collections::HashSet<&str> = config
        .kotlin_android
        .as_ref()
        .map(|c| c.exclude_functions.iter().map(String::as_str).collect())
        .unwrap_or_default();

    let visible_functions: Vec<_> = api
        .functions
        .iter()
        .filter(|f| !f.sanitized && !exclude_functions.contains(f.name.as_str()))
        .collect();

    // Top-level function shims.
    for f in &visible_functions {
        let method_name = bridge_method_name("", &f.name);
        let symbol = jni_symbol(&package, &bridge, &method_name);
        emit_function_shim(&mut out, &symbol, f.params.iter().map(|p| (&p.name, &p.ty)).collect(), &f.return_type, config);
    }

    // Opaque client type shims.
    let client_types: Vec<_> = api
        .types
        .iter()
        .filter(|t| t.is_opaque && !t.is_trait && t.methods.iter().any(|m| !m.sanitized && !m.is_static))
        .collect();

    for ty in &client_types {
        emit_client_shims(&mut out, ty, api, config, &package, &bridge, &exclude_functions);
    }

    out
}

// ---------------------------------------------------------------------------
// Client type shims
// ---------------------------------------------------------------------------

fn emit_client_shims(
    out: &mut String,
    ty: &TypeDef,
    api: &ApiSurface,
    config: &ResolvedCrateConfig,
    package: &str,
    bridge: &str,
    exclude_functions: &std::collections::HashSet<&str>,
) {
    // Instance method shims.
    for method in ty.methods.iter().filter(|m| !m.sanitized && !m.is_static) {
        if exclude_functions.contains(method.name.as_str()) {
            continue;
        }
        let method_name = bridge_method_name(&ty.name, &method.name);
        let symbol = jni_symbol(package, bridge, &method_name);
        emit_method_shim(out, &symbol, &ty.name, &method.name, method.params.iter().map(|p| (&p.name, &p.ty)).collect(), &method.return_type, config);
    }

    // Destructor shim.
    let free_name = destructor_method_name(&ty.name);
    let free_symbol = jni_symbol(package, bridge, &free_name);
    emit_destructor_shim(out, &free_symbol, &ty.name);

    // Streaming adapter shims owned by this type.
    let streaming: Vec<_> = config
        .adapters
        .iter()
        .filter(|a| {
            matches!(a.pattern, AdapterPattern::Streaming)
                && a.owner_type.as_deref() == Some(ty.name.as_str())
        })
        .collect();
    for adapter in &streaming {
        let (start_name, next_name, free_adapter_name) = streaming_method_names(&ty.name, &adapter.name);
        let start_sym = jni_symbol(package, bridge, &start_name);
        let next_sym = jni_symbol(package, bridge, &next_name);
        let free_sym = jni_symbol(package, bridge, &free_adapter_name);
        emit_streaming_shims(out, &start_sym, &next_sym, &free_sym, ty, adapter, config, api);
    }

    let _ = api; // suppress unused warning if no streaming adapters
}

// ---------------------------------------------------------------------------
// Individual shim emitters
// ---------------------------------------------------------------------------

/// Emit a shim for a top-level API function.
fn emit_function_shim(
    out: &mut String,
    symbol: &str,
    params: Vec<(&String, &TypeRef)>,
    return_type: &TypeRef,
    config: &ResolvedCrateConfig,
) {
    let jni_params = render_jni_params(&params);
    let jni_ret = jni_return_type(return_type);
    let ret_suffix = if matches!(return_type, TypeRef::Unit) {
        String::new()
    } else {
        format!(" -> {jni_ret}")
    };

    out.push_str(&format!(
        "#[unsafe(no_mangle)]\npub unsafe extern \"system\" fn {symbol}(\n    mut env: JNIEnv,\n    _class: JClass,\n{jni_params}){ret_suffix} {{\n"
    ));

    emit_todo_body(out, return_type, config);

    out.push_str("}\n\n");
}

/// Emit a shim for an instance method on an opaque client type.
fn emit_method_shim(
    out: &mut String,
    symbol: &str,
    _type_name: &str,
    _method_name: &str,
    params: Vec<(&String, &TypeRef)>,
    return_type: &TypeRef,
    config: &ResolvedCrateConfig,
) {
    let handle_param = "    handle: jlong,\n";
    let jni_ret = jni_return_type(return_type);
    let ret_suffix = if matches!(return_type, TypeRef::Unit) {
        String::new()
    } else {
        format!(" -> {jni_ret}")
    };

    // Methods with params also receive requestJson.
    let request_param = if params.is_empty() {
        String::new()
    } else {
        "    request_json: JString,\n".to_string()
    };

    out.push_str(&format!(
        "#[unsafe(no_mangle)]\npub unsafe extern \"system\" fn {symbol}(\n    mut env: JNIEnv,\n    _class: JClass,\n{handle_param}{request_param}){ret_suffix} {{\n"
    ));

    emit_todo_body(out, return_type, config);

    out.push_str("}\n\n");
}

/// Emit the destructor shim for an opaque type.
fn emit_destructor_shim(out: &mut String, symbol: &str, _type_name: &str) {
    out.push_str(&format!(
        "#[unsafe(no_mangle)]\npub unsafe extern \"system\" fn {symbol}(\n    _env: JNIEnv,\n    _class: JClass,\n    handle: jlong,\n) {{\n"
    ));
    out.push_str("    // SAFETY: `handle` was allocated by the matching constructor shim and\n");
    out.push_str("    // ownership is transferred back here for drop.\n");
    out.push_str("    let _ = handle; // TODO: drop(Box::from_raw(handle as *mut _));\n");
    out.push_str("}\n\n");
}

/// Emit Start/Next/Free streaming shims for one adapter.
#[allow(clippy::too_many_arguments)]
fn emit_streaming_shims(
    out: &mut String,
    start_sym: &str,
    next_sym: &str,
    free_sym: &str,
    _ty: &TypeDef,
    _adapter: &alef_core::config::AdapterConfig,
    _config: &ResolvedCrateConfig,
    _api: &ApiSurface,
) {
    // Start: (clientHandle: Long, requestJson: String) -> Long
    out.push_str(&format!(
        "#[unsafe(no_mangle)]\npub unsafe extern \"system\" fn {start_sym}(\n    mut env: JNIEnv,\n    _class: JClass,\n    client_handle: jlong,\n    request_json: JString,\n) -> jlong {{\n"
    ));
    out.push_str("    let _ = (client_handle, request_json); // TODO: spawn stream, return handle\n");
    out.push_str("    0\n");
    out.push_str("}\n\n");

    // Next: (streamHandle: Long) -> String?  — null pointer signals end
    out.push_str(&format!(
        "#[unsafe(no_mangle)]\npub unsafe extern \"system\" fn {next_sym}(\n    mut env: JNIEnv,\n    _class: JClass,\n    stream_handle: jlong,\n) -> jni::sys::jobject {{\n"
    ));
    out.push_str("    let _ = stream_handle; // TODO: poll next chunk, return JSON or null\n");
    out.push_str("    std::ptr::null_mut()\n");
    out.push_str("}\n\n");

    // Free: (streamHandle: Long)
    out.push_str(&format!(
        "#[unsafe(no_mangle)]\npub unsafe extern \"system\" fn {free_sym}(\n    _env: JNIEnv,\n    _class: JClass,\n    stream_handle: jlong,\n) {{\n"
    ));
    out.push_str("    let _ = stream_handle; // TODO: drop stream handle\n");
    out.push_str("}\n\n");
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Emit a minimal function body that satisfies the compiler for the stub.
///
/// All shims are scaffolded as `todo!()` placeholders — consumers must fill in
/// the actual bridge logic. The return expression must typecheck, so we emit a
/// typed zero/null depending on the return type.
fn emit_todo_body(out: &mut String, return_type: &TypeRef, _config: &ResolvedCrateConfig) {
    match return_type {
        TypeRef::Unit => {
            out.push_str("    todo!(\"JNI shim body\")\n");
        }
        TypeRef::Primitive(p) => {
            let zero = match p {
                PrimitiveType::Bool => "0u8",
                PrimitiveType::F32 => "0.0f32",
                PrimitiveType::F64 => "0.0f64",
                _ => "0",
            };
            out.push_str(&format!("    todo!(\"JNI shim body\"); #[allow(unreachable_code)] {zero}\n"));
        }
        TypeRef::String
        | TypeRef::Named(_)
        | TypeRef::Optional(_)
        | TypeRef::Vec(_)
        | TypeRef::Map(_, _) => {
            out.push_str("    todo!(\"JNI shim body\"); #[allow(unreachable_code)] std::ptr::null_mut()\n");
        }
        _ => {
            // Opaque handle → Long
            out.push_str("    todo!(\"JNI shim body\"); #[allow(unreachable_code)] 0i64\n");
        }
    }
}

/// Render a parameter list for a JNI function signature.
///
/// Each complex-type parameter is rendered as `JString`; primitives use the
/// matching JNI numeric type.
fn render_jni_params(params: &[(&String, &TypeRef)]) -> String {
    let mut out = String::new();
    for (name, ty) in params {
        let jni_ty = jni_param_type(ty);
        // Convert snake_case param name to a valid Rust identifier.
        let rust_name = name.replace('-', "_");
        out.push_str(&format!("    {rust_name}: {jni_ty},\n"));
    }
    out
}

/// Map a TypeRef to a JNI return type string.
fn jni_return_type(ty: &TypeRef) -> &'static str {
    match ty {
        TypeRef::Unit => "()",
        TypeRef::Primitive(p) => match p {
            PrimitiveType::Bool => "jboolean",
            PrimitiveType::I8 | PrimitiveType::U8 => "jbyte",
            PrimitiveType::I16 | PrimitiveType::U16 => "jshort",
            PrimitiveType::I32 | PrimitiveType::U32 => "jint",
            PrimitiveType::I64 | PrimitiveType::U64 | PrimitiveType::Usize | PrimitiveType::Isize => "jlong",
            PrimitiveType::F32 => "jfloat",
            PrimitiveType::F64 => "jdouble",
        },
        // String and complex types cross the boundary as Java objects.
        TypeRef::String | TypeRef::Named(_) | TypeRef::Optional(_) | TypeRef::Vec(_) | TypeRef::Map(_, _) => {
            "jni::sys::jobject"
        }
        // Opaque handles → Long.
        _ => "jlong",
    }
}

/// Map a TypeRef to a JNI parameter type string.
fn jni_param_type(ty: &TypeRef) -> &'static str {
    match ty {
        TypeRef::Primitive(p) => match p {
            PrimitiveType::Bool => "jboolean",
            PrimitiveType::I8 | PrimitiveType::U8 => "jbyte",
            PrimitiveType::I16 | PrimitiveType::U16 => "jshort",
            PrimitiveType::I32 | PrimitiveType::U32 => "jint",
            PrimitiveType::I64 | PrimitiveType::U64 | PrimitiveType::Usize | PrimitiveType::Isize => "jlong",
            PrimitiveType::F32 => "jfloat",
            PrimitiveType::F64 => "jdouble",
        },
        TypeRef::String | TypeRef::Named(_) | TypeRef::Optional(_) | TypeRef::Vec(_) | TypeRef::Map(_, _) => "JString",
        _ => "jlong",
    }
}

/// Resolve the Kotlin package string used when constructing JNI symbols.
///
/// Prefers `[crates.kotlin_android] package`, then `[crates.kotlin] package`,
/// then falls back to `config.kotlin_package()`.
fn jni_kotlin_package(config: &ResolvedCrateConfig) -> String {
    config
        .kotlin_android
        .as_ref()
        .and_then(|a| a.package.clone())
        .or_else(|| config.kotlin.as_ref().and_then(|k| k.package.clone()))
        .unwrap_or_else(|| config.kotlin_package())
}

/// Return the `use` path for the core crate from the JNI shim.
///
/// Uses the `name` field of the config (which is the crate name, e.g.
/// `liter-llm`), converting hyphens to underscores per Rust convention.
fn core_use_path(config: &ResolvedCrateConfig) -> String {
    config.name.replace('-', "_")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn jni_return_type_unit() {
        assert_eq!(jni_return_type(&TypeRef::Unit), "()");
    }

    #[test]
    fn jni_return_type_i64() {
        assert_eq!(jni_return_type(&TypeRef::Primitive(PrimitiveType::I64)), "jlong");
    }

    #[test]
    fn jni_return_type_string() {
        assert_eq!(jni_return_type(&TypeRef::String), "jni::sys::jobject");
    }
}
