use alef_backend_dart::DartBackend;
use alef_core::backend::Backend;
use alef_core::config::{AlefConfig, CrateConfig, TraitBridgeConfig};
use alef_core::ir::{
    ApiSurface, CoreWrapper, EnumDef, EnumVariant, ErrorDef, ErrorVariant, FieldDef, FunctionDef, MethodDef,
    ParamDef, PrimitiveType, ReceiverKind, TypeDef, TypeRef,
};

fn make_field(name: &str, ty: TypeRef, optional: bool) -> FieldDef {
    FieldDef {
        name: name.to_string(),
        ty,
        optional,
        default: None,
        doc: String::new(),
        sanitized: false,
        is_boxed: false,
        type_rust_path: None,
        cfg: None,
        typed_default: None,
        core_wrapper: CoreWrapper::None,
        vec_inner_core_wrapper: CoreWrapper::None,
        newtype_wrapper: None,
    }
}

fn make_param(name: &str, ty: TypeRef) -> ParamDef {
    ParamDef {
        name: name.to_string(),
        ty,
        optional: false,
        default: None,
        sanitized: false,
        typed_default: None,
        is_ref: false,
        is_mut: false,
        newtype_wrapper: None,
        original_type: None,
    }
}

fn make_type(name: &str, fields: Vec<FieldDef>) -> TypeDef {
    TypeDef {
        name: name.to_string(),
        rust_path: format!("demo::{name}"),
        original_rust_path: String::new(),
        fields,
        methods: vec![],
        is_opaque: false,
        is_clone: true,

        is_copy: false,
        doc: String::new(),
        cfg: None,
        is_trait: false,
        has_default: false,
        has_stripped_cfg_fields: false,
        is_return_type: false,
        serde_rename_all: None,
        has_serde: false,
        super_traits: vec![],
    }
}

fn make_config() -> AlefConfig {
    AlefConfig {
        version: None,
        crate_config: CrateConfig {
            name: "demo-crate".to_string(),
            sources: vec![],
            version_from: "Cargo.toml".to_string(),
            core_import: None,
            workspace_root: None,
            skip_core_import: false,
            features: vec![],
            path_mappings: std::collections::HashMap::new(),
            auto_path_mappings: Default::default(),
            extra_dependencies: Default::default(),
            source_crates: vec![],
            error_type: None,
            error_constructor: None,
        },
        languages: vec![],
        exclude: Default::default(),
        include: Default::default(),
        output: Default::default(),
        python: None,
        node: None,
        ruby: None,
        php: None,
        elixir: None,
        wasm: None,
        ffi: None,
        gleam: None,
        go: None,
        java: None,
        kotlin: None,
        dart: None,
        swift: None,
        csharp: None,
        r: None,
        zig: None,
        scaffold: None,
        readme: None,
        lint: None,
        update: None,
        test: None,
        setup: None,
        clean: None,
        build_commands: None,
        publish: None,
        custom_files: None,
        adapters: vec![],
        custom_modules: alef_core::config::CustomModulesConfig::default(),
        custom_registrations: alef_core::config::CustomRegistrationsConfig::default(),
        opaque_types: std::collections::HashMap::new(),
        generate: alef_core::config::GenerateConfig::default(),
        generate_overrides: std::collections::HashMap::new(),
        dto: Default::default(),
        sync: None,
        e2e: None,
        trait_bridges: vec![],
        tools: alef_core::config::ToolsConfig::default(),
    format: ::alef_core::config::FormatConfig::default(),
    format_overrides: ::std::collections::HashMap::new(),
    }
}

#[test]
fn struct_with_primitive_fields_emits_class() {
    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![make_type(
            "Point",
            vec![
                make_field("x_coord", TypeRef::Primitive(PrimitiveType::I32), false),
                make_field("y_coord", TypeRef::Primitive(PrimitiveType::I32), false),
            ],
        )],
        functions: vec![],
        enums: vec![],
        errors: vec![],
    };

    let files = DartBackend.generate_bindings(&api, &make_config()).unwrap();
    // generate_bindings now returns the Dart wrapper plus 4 Rust crate files
    assert_eq!(files.len(), 5);
    let content = files
        .iter()
        .find(|f| f.path.to_string_lossy().ends_with(".dart"))
        .map(|f| f.content.as_str())
        .expect("no .dart file emitted");
    assert!(content.contains("// Generated by alef. Do not edit by hand."), "missing header: {content}");
    assert!(content.contains("class Point {"), "missing class: {content}");
    assert!(content.contains("final int xCoord;"), "missing field xCoord: {content}");
    assert!(content.contains("final int yCoord;"), "missing field yCoord: {content}");
    // Multi-field constructor uses named required params
    assert!(content.contains("required this.xCoord"), "missing named ctor param: {content}");
    assert!(content.contains("required this.yCoord"), "missing named ctor param: {content}");
}

#[test]
fn struct_with_optional_vec_map_fields() {
    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![make_type(
            "Container",
            vec![
                make_field(
                    "maybe_name",
                    TypeRef::Optional(Box::new(TypeRef::String)),
                    false,
                ),
                make_field(
                    "tags",
                    TypeRef::Vec(Box::new(TypeRef::String)),
                    false,
                ),
                make_field(
                    "scores",
                    TypeRef::Map(
                        Box::new(TypeRef::String),
                        Box::new(TypeRef::Primitive(PrimitiveType::F64)),
                    ),
                    false,
                ),
            ],
        )],
        functions: vec![],
        enums: vec![],
        errors: vec![],
    };

    let files = DartBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;
    assert!(content.contains("final String? maybeName;"), "missing optional field: {content}");
    assert!(content.contains("final List<String> tags;"), "missing list field: {content}");
    assert!(content.contains("final Map<String, double> scores;"), "missing map field: {content}");
}

#[test]
fn empty_struct_emits_empty_class() {
    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![make_type("Empty", vec![])],
        functions: vec![],
        enums: vec![],
        errors: vec![],
    };

    let files = DartBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;
    assert!(content.contains("class Empty {}"), "missing empty class: {content}");
}

#[test]
fn unit_enum_emits_dart_enum() {
    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![],
        functions: vec![],
        enums: vec![EnumDef {
            name: "Status".into(),
            rust_path: "demo::Status".into(),
            original_rust_path: String::new(),
            variants: vec![
                EnumVariant {
                    name: "Active".into(),
                    fields: vec![],
                    doc: String::new(),
                    is_default: false,
                    serde_rename: None,
                is_tuple: false,
                },
                EnumVariant {
                    name: "Inactive".into(),
                    fields: vec![],
                    doc: String::new(),
                    is_default: false,
                    serde_rename: None,
                is_tuple: false,
                },
            ],
            doc: String::new(),
            cfg: None,
            serde_tag: None,
            serde_rename_all: None,

            is_copy: false,
            has_serde: false,
        }],
        errors: vec![],
    };

    let files = DartBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;
    assert!(content.contains("enum Status {"), "missing enum: {content}");
    // Dart uses lowerCamelCase for enum variants
    assert!(content.contains("active"), "missing active variant: {content}");
    assert!(content.contains("inactive"), "missing inactive variant: {content}");
    // Last variant has semicolon
    assert!(content.contains("inactive;"), "missing semicolon on last variant: {content}");
}

#[test]
fn data_bearing_enum_emits_sealed_class() {
    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![],
        functions: vec![],
        enums: vec![EnumDef {
            name: "Shape".into(),
            rust_path: "demo::Shape".into(),
            original_rust_path: String::new(),
            variants: vec![
                EnumVariant {
                    name: "Circle".into(),
                    fields: vec![make_field("radius", TypeRef::Primitive(PrimitiveType::F64), false)],
                    doc: String::new(),
                    is_default: false,
                    serde_rename: None,
                is_tuple: false,
                },
                EnumVariant {
                    name: "Rectangle".into(),
                    fields: vec![],
                    doc: String::new(),
                    is_default: false,
                    serde_rename: None,
                is_tuple: false,
                },
            ],
            doc: String::new(),
            cfg: None,
            serde_tag: None,
            serde_rename_all: None,

            is_copy: false,
            has_serde: false,
        }],
        errors: vec![],
    };

    let files = DartBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;
    assert!(content.contains("sealed class Shape {}"), "missing sealed class: {content}");
    assert!(content.contains("final class Circle extends Shape {"), "missing Circle variant: {content}");
    assert!(content.contains("final double radius;"), "missing radius field: {content}");
    assert!(content.contains("final class Rectangle extends Shape {}"), "missing unit Rectangle: {content}");
}

#[test]
fn simple_sync_function_emits_static_method() {
    let api = ApiSurface {
        crate_name: "demo-crate".into(),
        version: "0.1.0".into(),
        types: vec![],
        functions: vec![FunctionDef {
            name: "greet_user".into(),
            rust_path: "demo::greet_user".into(),
            original_rust_path: String::new(),
            params: vec![make_param("user_name", TypeRef::String)],
            return_type: TypeRef::Primitive(PrimitiveType::I32),
            is_async: false,
            error_type: None,
            doc: String::new(),
            cfg: None,
            sanitized: false,
            return_sanitized: false,
            returns_ref: false,
            returns_cow: false,
            return_newtype_wrapper: None,
        }],
        enums: vec![],
        errors: vec![],
    };

    let files = DartBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;
    assert!(content.contains("class DemoCrateBridge {"), "missing bridge class: {content}");
    assert!(content.contains("static int greetUser(String userName)"), "missing method sig: {content}");
    assert!(
        content.contains("return rust_bridge.greetUser(userName);"),
        "missing bridge call body: {content}"
    );
    assert!(
        content.contains("import 'demo_crate_bridge_generated.dart' as rust_bridge;"),
        "missing rust_bridge import: {content}"
    );
}

#[test]
fn async_function_emits_future_return_and_async_keyword() {
    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![],
        functions: vec![FunctionDef {
            name: "fetch_data".into(),
            rust_path: "demo::fetch_data".into(),
            original_rust_path: String::new(),
            params: vec![],
            return_type: TypeRef::String,
            is_async: true,
            error_type: None,
            doc: String::new(),
            cfg: None,
            sanitized: false,
            return_sanitized: false,
            returns_ref: false,
            returns_cow: false,
            return_newtype_wrapper: None,
        }],
        enums: vec![],
        errors: vec![],
    };

    let files = DartBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;
    assert!(content.contains("import 'dart:async';"), "missing dart:async import: {content}");
    assert!(
        content.contains("static Future<String> fetchData() async {"),
        "missing async method: {content}"
    );
    assert!(
        content.contains("return await rust_bridge.fetchData();"),
        "missing await bridge call: {content}"
    );
}

#[test]
fn error_returning_function_emits_doc_comment() {
    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![],
        functions: vec![FunctionDef {
            name: "parse_input".into(),
            rust_path: "demo::parse_input".into(),
            original_rust_path: String::new(),
            params: vec![make_param("raw", TypeRef::String)],
            return_type: TypeRef::String,
            is_async: false,
            error_type: Some("ParseError".into()),
            doc: String::new(),
            cfg: None,
            sanitized: false,
            return_sanitized: false,
            returns_ref: false,
            returns_cow: false,
            return_newtype_wrapper: None,
        }],
        enums: vec![],
        errors: vec![],
    };

    let files = DartBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;
    assert!(
        content.contains("/// throws ParseError on failure"),
        "missing error doc comment: {content}"
    );
    assert!(content.contains("static String parseInput(String raw)"), "missing method: {content}");
}

#[test]
fn error_type_emits_sealed_class_hierarchy() {
    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![],
        functions: vec![],
        enums: vec![],
        errors: vec![ErrorDef {
            name: "ApiError".into(),
            rust_path: "demo::ApiError".into(),
            original_rust_path: String::new(),
            variants: vec![
                ErrorVariant {
                    name: "NotFound".into(),
                    message_template: Some("Resource not found".into()),
                    fields: vec![],
                    has_source: false,
                    has_from: false,
                    is_unit: true,
                    doc: String::new(),
                },
                ErrorVariant {
                    name: "InvalidFormat".into(),
                    message_template: Some("Invalid format at line {0}".into()),
                    fields: vec![make_field("line_number", TypeRef::Primitive(PrimitiveType::I32), false)],
                    has_source: false,
                    has_from: false,
                    is_unit: false,
                    doc: String::new(),
                },
            ],
            doc: String::new(),
        }],
    };

    let files = DartBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;
    assert!(
        content.contains("sealed class ApiError implements Exception {"),
        "missing sealed error class: {content}"
    );
    assert!(content.contains("final class NotFound implements ApiError {"), "missing NotFound: {content}");
    assert!(
        content.contains("String get message => 'Resource not found'"),
        "missing message getter: {content}"
    );
    assert!(
        content.contains("final class InvalidFormat implements ApiError {"),
        "missing InvalidFormat: {content}"
    );
    assert!(content.contains("final int lineNumber;"), "missing field: {content}");
}

#[test]
fn bytes_field_adds_typed_data_import() {
    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![make_type("Blob", vec![make_field("data", TypeRef::Bytes, false)])],
        functions: vec![],
        enums: vec![],
        errors: vec![],
    };

    let files = DartBackend.generate_bindings(&api, &make_config()).unwrap();
    let content = &files[0].content;
    assert!(content.contains("import 'dart:typed_data';"), "missing typed_data import: {content}");
    assert!(content.contains("final Uint8List data;"), "missing Uint8List field: {content}");
}

#[test]
fn output_path_uses_module_name() {
    let api = ApiSurface {
        crate_name: "my-lib".into(),
        version: "0.1.0".into(),
        types: vec![],
        functions: vec![],
        enums: vec![],
        errors: vec![],
    };
    let mut config = make_config();
    config.crate_config.name = "my-lib".to_string();

    let files = DartBackend.generate_bindings(&api, &config).unwrap();
    // Even empty API generates one file (or zero if we short-circuit)
    // With no content, we still return the file — check the path ends with my_lib.dart
    if !files.is_empty() {
        let path_str = files[0].path.to_string_lossy();
        assert!(path_str.ends_with("my_lib.dart"), "wrong output path: {path_str}");
    }
}

// ── Dart trait abstract class emission ──────────────────────────────────────

fn make_method(name: &str, params: Vec<ParamDef>, return_type: TypeRef, is_async: bool) -> MethodDef {
    MethodDef {
        name: name.to_string(),
        params,
        return_type,
        is_async,
        is_static: false,
        error_type: None,
        doc: String::new(),
        receiver: Some(ReceiverKind::Ref),
        sanitized: false,
        trait_source: None,
        returns_ref: false,
        returns_cow: false,
        return_newtype_wrapper: None,
        has_default_impl: false,
    }
}

fn make_trait(name: &str, rust_path: &str, methods: Vec<MethodDef>) -> TypeDef {
    TypeDef {
        name: name.to_string(),
        rust_path: rust_path.to_string(),
        original_rust_path: String::new(),
        fields: vec![],
        methods,
        is_opaque: true,
        is_clone: false,
        is_copy: false,
        doc: String::new(),
        cfg: None,
        is_trait: true,
        has_default: false,
        has_stripped_cfg_fields: false,
        is_return_type: false,
        serde_rename_all: None,
        has_serde: false,
        super_traits: vec![],
    }
}

fn make_config_with_bridge(bridge_trait_name: &str) -> AlefConfig {
    let mut config = make_config();
    config.trait_bridges = vec![TraitBridgeConfig {
        trait_name: bridge_trait_name.to_string(),
        super_trait: None,
        registry_getter: None,
        register_fn: None,
        type_alias: None,
        param_name: None,
        register_extra_args: None,
        exclude_languages: vec![],
    }];
    config
}

fn find_traits_dart(files: &[alef_core::backend::GeneratedFile]) -> Option<&str> {
    files
        .iter()
        .find(|f| f.path.to_string_lossy().ends_with("traits.dart"))
        .map(|f| f.content.as_str())
}

#[test]
fn no_trait_bridges_does_not_emit_traits_dart() {
    let api = ApiSurface {
        crate_name: "demo".into(),
        version: "0.1.0".into(),
        types: vec![],
        functions: vec![],
        enums: vec![],
        errors: vec![],
    };

    let files = DartBackend.generate_bindings(&api, &make_config()).unwrap();
    // Without trait_bridges config, traits.dart should NOT appear.
    assert!(
        find_traits_dart(&files).is_none(),
        "traits.dart should not be emitted without trait_bridges config"
    );
}

#[test]
fn single_trait_bridge_emits_traits_dart_with_abstract_class() {
    let trait_def = make_trait(
        "OcrBackend",
        "demo_crate::OcrBackend",
        vec![make_method(
            "process_image",
            vec![make_param("bytes", TypeRef::Bytes)],
            TypeRef::String,
            true,
        )],
    );
    let api = ApiSurface {
        crate_name: "demo-crate".into(),
        version: "0.1.0".into(),
        types: vec![trait_def],
        functions: vec![],
        enums: vec![],
        errors: vec![],
    };

    let files = DartBackend.generate_bindings(&api, &make_config_with_bridge("OcrBackend")).unwrap();
    let content = find_traits_dart(&files).expect("traits.dart should be emitted");

    assert!(content.contains("// Generated by alef. Do not edit by hand."), "missing header: {content}");
    assert!(content.contains("abstract class OcrBackend {"), "missing abstract class: {content}");
    assert!(
        content.contains("Future<String> processImage(Uint8List bytes);"),
        "missing abstract method: {content}"
    );
}

#[test]
fn traits_dart_path_is_under_lib_src() {
    let trait_def = make_trait(
        "Validator",
        "demo_crate::Validator",
        vec![make_method(
            "validate",
            vec![make_param("input", TypeRef::String)],
            TypeRef::Primitive(PrimitiveType::Bool),
            false,
        )],
    );
    let api = ApiSurface {
        crate_name: "demo-crate".into(),
        version: "0.1.0".into(),
        types: vec![trait_def],
        functions: vec![],
        enums: vec![],
        errors: vec![],
    };

    let files = DartBackend.generate_bindings(&api, &make_config_with_bridge("Validator")).unwrap();
    let traits_file = files
        .iter()
        .find(|f| f.path.to_string_lossy().ends_with("traits.dart"))
        .expect("traits.dart should be emitted");

    let path_str = traits_file.path.to_string_lossy();
    assert!(
        path_str.contains("packages/dart/lib/src/traits.dart"),
        "wrong path for traits.dart: {path_str}"
    );
}

#[test]
fn multiple_trait_bridges_emit_multiple_abstract_classes() {
    let ocr_trait = make_trait(
        "OcrBackend",
        "demo_crate::OcrBackend",
        vec![make_method(
            "extract_text",
            vec![make_param("data", TypeRef::Bytes)],
            TypeRef::String,
            true,
        )],
    );
    let validator_trait = make_trait(
        "Validator",
        "demo_crate::Validator",
        vec![make_method(
            "validate",
            vec![make_param("input", TypeRef::String)],
            TypeRef::Primitive(PrimitiveType::Bool),
            false,
        )],
    );
    let api = ApiSurface {
        crate_name: "demo-crate".into(),
        version: "0.1.0".into(),
        types: vec![ocr_trait, validator_trait],
        functions: vec![],
        enums: vec![],
        errors: vec![],
    };

    let mut config = make_config();
    config.trait_bridges = vec![
        TraitBridgeConfig {
            trait_name: "OcrBackend".to_string(),
            super_trait: None,
            registry_getter: None,
            register_fn: None,
            type_alias: None,
            param_name: None,
            register_extra_args: None,
            exclude_languages: vec![],
        },
        TraitBridgeConfig {
            trait_name: "Validator".to_string(),
            super_trait: None,
            registry_getter: None,
            register_fn: None,
            type_alias: None,
            param_name: None,
            register_extra_args: None,
            exclude_languages: vec![],
        },
    ];

    let files = DartBackend.generate_bindings(&api, &config).unwrap();
    let content = find_traits_dart(&files).expect("traits.dart should be emitted");

    assert!(content.contains("abstract class OcrBackend {"), "missing OcrBackend: {content}");
    assert!(content.contains("abstract class Validator {"), "missing Validator: {content}");
    assert!(content.contains("Future<String> extractText(Uint8List data);"), "missing extractText: {content}");
    assert!(content.contains("Future<bool> validate(String input);"), "missing validate: {content}");
}

#[test]
fn excluded_trait_bridge_does_not_appear_in_traits_dart() {
    let trait_def = make_trait(
        "OcrBackend",
        "demo_crate::OcrBackend",
        vec![make_method(
            "extract_text",
            vec![make_param("data", TypeRef::Bytes)],
            TypeRef::String,
            true,
        )],
    );
    let api = ApiSurface {
        crate_name: "demo-crate".into(),
        version: "0.1.0".into(),
        types: vec![trait_def],
        functions: vec![],
        enums: vec![],
        errors: vec![],
    };

    let mut config = make_config();
    config.trait_bridges = vec![TraitBridgeConfig {
        trait_name: "OcrBackend".to_string(),
        super_trait: None,
        registry_getter: None,
        register_fn: None,
        type_alias: None,
        param_name: None,
        register_extra_args: None,
        exclude_languages: vec!["dart".to_string()],
    }];

    let files = DartBackend.generate_bindings(&api, &config).unwrap();
    // The trait is excluded for dart, so traits.dart should not appear.
    assert!(
        find_traits_dart(&files).is_none(),
        "traits.dart should not be emitted when trait bridge excludes dart"
    );
}

#[test]
fn traits_dart_includes_typed_data_import_for_bytes_param() {
    let trait_def = make_trait(
        "ImageProcessor",
        "demo_crate::ImageProcessor",
        vec![make_method(
            "process",
            vec![make_param("raw", TypeRef::Bytes)],
            TypeRef::Bytes,
            true,
        )],
    );
    let api = ApiSurface {
        crate_name: "demo-crate".into(),
        version: "0.1.0".into(),
        types: vec![trait_def],
        functions: vec![],
        enums: vec![],
        errors: vec![],
    };

    let files = DartBackend.generate_bindings(&api, &make_config_with_bridge("ImageProcessor")).unwrap();
    let content = find_traits_dart(&files).expect("traits.dart should be emitted");

    assert!(
        content.contains("import 'dart:typed_data';"),
        "missing dart:typed_data import for Bytes type: {content}"
    );
    assert!(content.contains("Future<Uint8List> process(Uint8List raw);"), "missing method: {content}");
}

#[test]
fn traits_dart_doc_comment_shows_registration_pattern() {
    let trait_def = make_trait(
        "OcrBackend",
        "demo_crate::OcrBackend",
        vec![make_method(
            "process_image",
            vec![make_param("bytes", TypeRef::Bytes)],
            TypeRef::String,
            true,
        )],
    );
    let api = ApiSurface {
        crate_name: "demo-crate".into(),
        version: "0.1.0".into(),
        types: vec![trait_def],
        functions: vec![],
        enums: vec![],
        errors: vec![],
    };

    let files = DartBackend.generate_bindings(&api, &make_config_with_bridge("OcrBackend")).unwrap();
    let content = find_traits_dart(&files).expect("traits.dart should be emitted");

    assert!(
        content.contains("createOcrBackendDartImpl("),
        "doc comment should show createOcrBackendDartImpl factory: {content}"
    );
    assert!(
        content.contains("class MyOcrBackend implements OcrBackend"),
        "doc comment should show example class: {content}"
    );
}
