pub(super) static TEMPLATES: &[(&str, &str)] = &[
    (
        "flat_enum_derive.jinja",
        include_str!("../templates/flat_enum_derive.jinja"),
    ),
    (
        "flat_enum_struct_header.jinja",
        include_str!("../templates/flat_enum_struct_header.jinja"),
    ),
    (
        "flat_enum_discriminator_field.jinja",
        include_str!("../templates/flat_enum_discriminator_field.jinja"),
    ),
    (
        "flat_enum_variant_field.jinja",
        include_str!("../templates/flat_enum_variant_field.jinja"),
    ),
    (
        "flat_enum_struct_footer.jinja",
        include_str!("../templates/flat_enum_struct_footer.jinja"),
    ),
    (
        "flat_enum_default_impl.jinja",
        include_str!("../templates/flat_enum_default_impl.jinja"),
    ),
    (
        "flat_enum_default_variant_field.jinja",
        include_str!("../templates/flat_enum_default_variant_field.jinja"),
    ),
    (
        "flat_enum_default_impl_footer.jinja",
        include_str!("../templates/flat_enum_default_impl_footer.jinja"),
    ),
    (
        "flat_enum_from_core_impl.jinja",
        include_str!("../templates/flat_enum_from_core_impl.jinja"),
    ),
    (
        "flat_enum_from_core_variant_unit.jinja",
        include_str!("../templates/flat_enum_from_core_variant_unit.jinja"),
    ),
    (
        "flat_enum_from_core_variant_tuple.jinja",
        include_str!("../templates/flat_enum_from_core_variant_tuple.jinja"),
    ),
    (
        "flat_enum_from_core_impl_footer.jinja",
        include_str!("../templates/flat_enum_from_core_impl_footer.jinja"),
    ),
    (
        "flat_enum_to_core_impl_header.jinja",
        include_str!("../templates/flat_enum_to_core_impl_header.jinja"),
    ),
    (
        "flat_enum_to_core_variant_unit.jinja",
        include_str!("../templates/flat_enum_to_core_variant_unit.jinja"),
    ),
    (
        "flat_enum_to_core_variant_tuple.jinja",
        include_str!("../templates/flat_enum_to_core_variant_tuple.jinja"),
    ),
    (
        "flat_enum_to_core_impl_footer.jinja",
        include_str!("../templates/flat_enum_to_core_impl_footer.jinja"),
    ),
    (
        "default_deser_with_error.rs.jinja",
        include_str!("../templates/default_deser_with_error.rs.jinja"),
    ),
    (
        "default_deser_without_error.rs.jinja",
        include_str!("../templates/default_deser_without_error.rs.jinja"),
    ),
    (
        "visitor_field_options_setup.rs.jinja",
        include_str!("../templates/visitor_field_options_setup.rs.jinja"),
    ),
    (
        "trait_optional_bridge_wrap.rs.jinja",
        include_str!("../templates/trait_optional_bridge_wrap.rs.jinja"),
    ),
    (
        "trait_required_bridge_wrap.rs.jinja",
        include_str!("../templates/trait_required_bridge_wrap.rs.jinja"),
    ),
    (
        "named_param_to_json.rs.jinja",
        include_str!("../templates/named_param_to_json.rs.jinja"),
    ),
    (
        "named_param_from_json.rs.jinja",
        include_str!("../templates/named_param_from_json.rs.jinja"),
    ),
    (
        "vec_str_refs_optional.rs.jinja",
        include_str!("../templates/vec_str_refs_optional.rs.jinja"),
    ),
    (
        "vec_str_refs_required.rs.jinja",
        include_str!("../templates/vec_str_refs_required.rs.jinja"),
    ),
    (
        "bytes_to_vec.rs.jinja",
        include_str!("../templates/bytes_to_vec.rs.jinja"),
    ),
    (
        "nif_result_body.rs.jinja",
        include_str!("../templates/nif_result_body.rs.jinja"),
    ),
    (
        "nif_wrapped_body.rs.jinja",
        include_str!("../templates/nif_wrapped_body.rs.jinja"),
    ),
    (
        "async_result_body.rs.jinja",
        include_str!("../templates/async_result_body.rs.jinja"),
    ),
    (
        "async_infallible_body.rs.jinja",
        include_str!("../templates/async_infallible_body.rs.jinja"),
    ),
    (
        "nif_tagged_enum_serde_tag.jinja",
        include_str!("../templates/nif_tagged_enum_serde_tag.jinja"),
    ),
    (
        "nif_tagged_enum_variant_unit.jinja",
        include_str!("../templates/nif_tagged_enum_variant_unit.jinja"),
    ),
    (
        "nif_tagged_enum_variant_struct_header.jinja",
        include_str!("../templates/nif_tagged_enum_variant_struct_header.jinja"),
    ),
    (
        "nif_tagged_enum_variant_field_line.jinja",
        include_str!("../templates/nif_tagged_enum_variant_field_line.jinja"),
    ),
    (
        "nif_tagged_enum_variant_field_attr.jinja",
        include_str!("../templates/nif_tagged_enum_variant_field_attr.jinja"),
    ),
    (
        "nif_tagged_enum_variant_struct_footer.jinja",
        include_str!("../templates/nif_tagged_enum_variant_struct_footer.jinja"),
    ),
    (
        "nif_unit_enum_header.jinja",
        include_str!("../templates/nif_unit_enum_header.jinja"),
    ),
    (
        "nif_enum_variant.jinja",
        include_str!("../templates/nif_enum_variant.jinja"),
    ),
    (
        "nif_enum_default_header.jinja",
        include_str!("../templates/nif_enum_default_header.jinja"),
    ),
    (
        "nif_enum_default_value.jinja",
        include_str!("../templates/nif_enum_default_value.jinja"),
    ),
    (
        "nif_enum_default_with_fields.jinja",
        include_str!("../templates/nif_enum_default_with_fields.jinja"),
    ),
    (
        "nif_enum_default_footer.jinja",
        include_str!("../templates/nif_enum_default_footer.jinja"),
    ),
    (
        "rust_method_instance_call.rs.jinja",
        include_str!("../templates/rust_method_instance_call.rs.jinja"),
    ),
    (
        "rust_method_static_call.rs.jinja",
        include_str!("../templates/rust_method_static_call.rs.jinja"),
    ),
    (
        "rust_method_static_call_with_preamble.rs.jinja",
        include_str!("../templates/rust_method_static_call_with_preamble.rs.jinja"),
    ),
    (
        "elixir_streaming_start_wrapper.jinja",
        include_str!("../templates/elixir_streaming_start_wrapper.jinja"),
    ),
    (
        "elixir_streaming_next_wrapper.jinja",
        include_str!("../templates/elixir_streaming_next_wrapper.jinja"),
    ),
    (
        "elixir_streaming_unfold_wrapper.jinja",
        include_str!("../templates/elixir_streaming_unfold_wrapper.jinja"),
    ),
    (
        "elixir_stream_error_exception.jinja",
        include_str!("../templates/elixir_stream_error_exception.jinja"),
    ),
    (
        "elixir_keyword_opts_wrapper.ex.jinja",
        include_str!("../templates/elixir_keyword_opts_wrapper.ex.jinja"),
    ),
    (
        "elixir_error_spec.ex.jinja",
        include_str!("../templates/elixir_error_spec.ex.jinja"),
    ),
    (
        "elixir_struct_type_field.ex.jinja",
        include_str!("../templates/elixir_struct_type_field.ex.jinja"),
    ),
    (
        "elixir_native_alias.ex.jinja",
        include_str!("../templates/elixir_native_alias.ex.jinja"),
    ),
    (
        "elixir_visitor_call_multiline.ex.jinja",
        include_str!("../templates/elixir_visitor_call_multiline.ex.jinja"),
    ),
    (
        "elixir_visitor_plain_call.ex.jinja",
        include_str!("../templates/elixir_visitor_plain_call.ex.jinja"),
    ),
    (
        "elixir_opaque_new.ex.jinja",
        include_str!("../templates/elixir_opaque_new.ex.jinja"),
    ),
    (
        "elixir_opaque_default.ex.jinja",
        include_str!("../templates/elixir_opaque_default.ex.jinja"),
    ),
    (
        "elixir_opaque_stream_method.ex.jinja",
        include_str!("../templates/elixir_opaque_stream_method.ex.jinja"),
    ),
    (
        "elixir_opaque_method_wrapper.ex.jinja",
        include_str!("../templates/elixir_opaque_method_wrapper.ex.jinja"),
    ),
    (
        "elixir_top_level_opaque_method.ex.jinja",
        include_str!("../templates/elixir_top_level_opaque_method.ex.jinja"),
    ),
    (
        "elixir_trait_behaviour.ex.jinja",
        include_str!("../templates/elixir_trait_behaviour.ex.jinja"),
    ),
    (
        "elixir_trait_register_delegate.ex.jinja",
        include_str!("../templates/elixir_trait_register_delegate.ex.jinja"),
    ),
    (
        "elixir_trait_unregister_delegate.ex.jinja",
        include_str!("../templates/elixir_trait_unregister_delegate.ex.jinja"),
    ),
    (
        "elixir_trait_clear_delegate.ex.jinja",
        include_str!("../templates/elixir_trait_clear_delegate.ex.jinja"),
    ),
    (
        "rustler_resource_registration.rs.jinja",
        include_str!("../templates/rustler_resource_registration.rs.jinja"),
    ),
    (
        "rustler_init_with_load.rs.jinja",
        include_str!("../templates/rustler_init_with_load.rs.jinja"),
    ),
    (
        "rustler_init.rs.jinja",
        include_str!("../templates/rustler_init.rs.jinja"),
    ),
    (
        "streaming_default_deser_binding.rs.jinja",
        include_str!("../templates/streaming_default_deser_binding.rs.jinja"),
    ),
    (
        "trait_impl_header.jinja",
        include_str!("../templates/trait_impl_header.jinja"),
    ),
    (
        "nif_tagged_enum_header.jinja",
        include_str!("../templates/nif_tagged_enum_header.jinja"),
    ),
    (
        "registration_variant.rs.jinja",
        include_str!("../templates/registration_variant.rs.jinja"),
    ),
    (
        "registration_variant.ex.jinja",
        include_str!("../templates/registration_variant.ex.jinja"),
    ),
    (
        "service_api_doc.ex.jinja",
        include_str!("../templates/service_api_doc.ex.jinja"),
    ),
    (
        "service_api_module_header.ex.jinja",
        include_str!("../templates/service_api_module_header.ex.jinja"),
    ),
    (
        "service_api_struct.ex.jinja",
        include_str!("../templates/service_api_struct.ex.jinja"),
    ),
    (
        "service_api_constructor.ex.jinja",
        include_str!("../templates/service_api_constructor.ex.jinja"),
    ),
    (
        "service_api_configurator.ex.jinja",
        include_str!("../templates/service_api_configurator.ex.jinja"),
    ),
    (
        "service_api_entrypoint.ex.jinja",
        include_str!("../templates/service_api_entrypoint.ex.jinja"),
    ),
    (
        "service_api_registration_method.ex.jinja",
        include_str!("../templates/service_api_registration_method.ex.jinja"),
    ),
    (
        "service_api_handler_wrapper.ex.jinja",
        include_str!("../templates/service_api_handler_wrapper.ex.jinja"),
    ),
    (
        "service_api_conn_struct.ex.jinja",
        include_str!("../templates/service_api_conn_struct.ex.jinja"),
    ),
    (
        "service_api_verb_decorator.ex.jinja",
        include_str!("../templates/service_api_verb_decorator.ex.jinja"),
    ),
    (
        "service_api_builder_variant.ex.jinja",
        include_str!("../templates/service_api_builder_variant.ex.jinja"),
    ),
    (
        "service_api_genserver.ex.jinja",
        include_str!("../templates/service_api_genserver.ex.jinja"),
    ),
    (
        "service_api_rs_header.rs.jinja",
        include_str!("../templates/service_api_rs_header.rs.jinja"),
    ),
    (
        "service_api_trait_reply_support.rs.jinja",
        include_str!("../templates/service_api_trait_reply_support.rs.jinja"),
    ),
    (
        "service_api_handler_bridge.rs.jinja",
        include_str!("../templates/service_api_handler_bridge.rs.jinja"),
    ),
    (
        "service_api_run_nif_header.rs.jinja",
        include_str!("../templates/service_api_run_nif_header.rs.jinja"),
    ),
    (
        "service_api_run_nif_footer.rs.jinja",
        include_str!("../templates/service_api_run_nif_footer.rs.jinja"),
    ),
    (
        "service_api_registration_variant_nif_header.rs.jinja",
        include_str!("../templates/service_api_registration_variant_nif_header.rs.jinja"),
    ),
    (
        "service_api_registration_variant_nif_footer.rs.jinja",
        include_str!("../templates/service_api_registration_variant_nif_footer.rs.jinja"),
    ),
    (
        "service_api_registration_dispatch.rs.jinja",
        include_str!("../templates/service_api_registration_dispatch.rs.jinja"),
    ),
    (
        "service_api_registration_variant_dispatch.rs.jinja",
        include_str!("../templates/service_api_registration_variant_dispatch.rs.jinja"),
    ),
    (
        "service_api_opaque_metadata_binding.rs.jinja",
        include_str!("../templates/service_api_opaque_metadata_binding.rs.jinja"),
    ),
    (
        "service_api_entrypoint_call.rs.jinja",
        include_str!("../templates/service_api_entrypoint_call.rs.jinja"),
    ),
];
