use alef_core::backend::GeneratedFile;
use alef_core::config::{AlefConfig, Language};
use std::path::PathBuf;

pub(crate) fn scaffold_pre_commit_config(config: &AlefConfig, languages: &[Language]) -> Vec<GeneratedFile> {
    if std::path::Path::new(".pre-commit-config.yaml").exists() {
        return vec![];
    }
    generate_pre_commit_config(config, languages)
}

/// Generate the `.pre-commit-config.yaml` content based on configured languages.
///
/// Separated from `scaffold_pre_commit_config` for testability.
pub(crate) fn generate_pre_commit_config(config: &AlefConfig, languages: &[Language]) -> Vec<GeneratedFile> {
    let has = |lang: Language| languages.contains(&lang);
    let crate_dir = config.core_crate_dir();

    // Build clippy --exclude args for binding crates that need special compilation
    // (native extensions with host-incompatible link flags). Wasm is NOT excluded
    // because rust-toolchain.toml includes the wasm32 target.
    let clippy_excludes = {
        let suffixes: &[(&str, Language)] = &[
            ("-py", Language::Python),
            ("-node", Language::Node),
            ("-php", Language::Php),
            ("-rb", Language::Ruby),
            ("-r", Language::R),
        ];
        let mut excludes = String::new();
        for (suffix, lang) in suffixes {
            if has(*lang) {
                excludes.push_str(&format!("            \"--exclude={crate_dir}{suffix}\",\n"));
            }
        }
        excludes
    };

    let mut yaml = String::new();

    // Header
    yaml.push_str(
        "# Generated by alef scaffold. Customize as needed.\n\
         default_install_hook_types:\n  - pre-commit\n  - commit-msg\n\
         exclude: ^target/|\\.alef/\n\n\
         repos:\n",
    );

    // Commit message linting
    yaml.push_str(
        "  # Commit message linting\n\
         \x20 - repo: https://github.com/Goldziher/gitfluff\n\
         \x20   rev: v0.7.6\n\
         \x20   hooks:\n\
         \x20     - id: gitfluff-lint\n\
         \x20       args: [\"--write\"]\n\
         \x20       stages: [commit-msg]\n\n",
    );

    // General file checks
    yaml.push_str(
        "  # General file checks\n\
         \x20 - repo: https://github.com/pre-commit/pre-commit-hooks\n\
         \x20   rev: v0.7.6\n\
         \x20   hooks:\n\
         \x20     - id: trailing-whitespace\n\
         \x20     - id: end-of-file-fixer\n\
         \x20     - id: check-merge-conflict\n\
         \x20     - id: check-added-large-files\n\
         \x20     - id: detect-private-key\n\
         \x20     - id: check-json\n\
         \x20     - id: check-yaml\n\
         \x20       args: [\"--allow-multiple-documents\", \"--unsafe\"]\n\
         \x20     - id: check-toml\n\
         \x20     - id: check-case-conflict\n\n",
    );

    // TOML formatting (Python only)
    if has(Language::Python) {
        yaml.push_str(
            "  - repo: https://github.com/tox-dev/pyproject-fmt\n\
             \x20   rev: \"v2.21.1\"\n\
             \x20   hooks:\n\
             \x20     - id: pyproject-fmt\n\n",
        );
    }

    yaml.push_str(
        "  - repo: https://github.com/DevinR528/cargo-sort\n\
         \x20   rev: \"v2.1.3\"\n\
         \x20   hooks:\n\
         \x20     - id: cargo-sort\n\
         \x20       args: [-w]\n\n",
    );

    // Rust: formatting, linting, unused deps, license/advisory
    yaml.push_str("  # Rust: formatting, linting, unused deps, license/advisory\n");
    yaml.push_str(
        "  - repo: https://github.com/AndrejOrsula/pre-commit-cargo\n\
         \x20   rev: 0.5.0\n\
         \x20   hooks:\n\
         \x20     - id: cargo-fmt\n\
         \x20       args: [\"--all\"]\n\
         \x20       types: [rust]\n\
         \x20     - id: cargo-clippy\n\
         \x20       args:\n\
         \x20         [\n\
         \x20           \"--fix\",\n\
         \x20           \"--allow-dirty\",\n\
         \x20           \"--allow-staged\",\n\
         \x20           \"--workspace\",\n\
         \x20           \"--all-features\",\n",
    );
    yaml.push_str(&clippy_excludes);
    yaml.push_str(
        "            \"--all-targets\",\n\
         \x20           \"--\",\n\
         \x20           \"-D\",\n\
         \x20           \"warnings\",\n\
         \x20         ]\n\n",
    );

    yaml.push_str(
        "  - repo: https://github.com/bnjbvr/cargo-machete\n\
         \x20   rev: v0.7.6\n\
         \x20   hooks:\n\
         \x20     - id: cargo-machete\n\n\
         \x20 - repo: https://github.com/EmbarkStudios/cargo-deny\n\
         \x20   rev: 0.19.4\n\
         \x20   hooks:\n\
         \x20     - id: cargo-deny\n\
         \x20       args: [\"check\"]\n\n",
    );

    // Markdown
    yaml.push_str(
        "  # Markdown\n\
         \x20 - repo: https://github.com/rvben/rumdl-pre-commit\n\
         \x20   rev: \"v0.1.81\"\n\
         \x20   hooks:\n\
         \x20     - id: rumdl-fmt\n\n",
    );

    // Alef: format, lint, verify bindings, sync versions
    yaml.push_str(
        "  # Alef: format and lint all binding languages, verify bindings, sync versions\n\
         \x20 - repo: https://github.com/kreuzberg-dev/alef\n\
         \x20   rev: v0.7.6\n\
         \x20   hooks:\n\
         \x20     - id: alef-fmt\n\
         \x20     - id: alef-lint\n\
         \x20     - id: alef-verify\n\
         \x20     - id: alef-sync-versions\n\n",
    );

    // Spelling (last)
    yaml.push_str(
        "  # Spelling\n\
         \x20 - repo: https://github.com/crate-ci/typos\n\
         \x20   rev: v0.7.6\n\
         \x20   hooks:\n\
         \x20     - id: typos\n\
         \x20       args: [\"--force-exclude\"]\n\n",
    );

    vec![GeneratedFile {
        path: PathBuf::from(".pre-commit-config.yaml"),
        content: yaml,
        generated_header: false,
    }]
}
