use alef_core::backend::GeneratedFile;
use alef_core::config::{Language, ResolvedCrateConfig};
use alef_core::template_versions as tv;
use std::path::PathBuf;

pub(crate) fn scaffold_pre_commit_config(config: &ResolvedCrateConfig, languages: &[Language]) -> Vec<GeneratedFile> {
    if std::path::Path::new(".pre-commit-config.yaml").exists() {
        return vec![];
    }
    generate_pre_commit_config(config, languages)
}

/// Generate the `.pre-commit-config.yaml` content based on configured languages.
///
/// Separated from `scaffold_pre_commit_config` for testability.
pub(crate) fn generate_pre_commit_config(config: &ResolvedCrateConfig, languages: &[Language]) -> Vec<GeneratedFile> {
    let has = |lang: Language| languages.contains(&lang);
    let crate_dir = config.core_crate_dir();

    // Build clippy --exclude args for binding crates that need special compilation
    // (native extensions with host-incompatible link flags). Wasm is NOT excluded
    // because rust-toolchain.toml includes the wasm32 target.
    let clippy_excludes = {
        let suffixes: &[(&str, Language)] = &[
            ("-py", Language::Python),
            ("-node", Language::Node),
            ("-php", Language::Php),
            ("-rb", Language::Ruby),
            ("-r", Language::R),
        ];
        let mut excludes = String::new();
        for (suffix, lang) in suffixes {
            if has(*lang) {
                excludes.push_str(&format!("            \"--exclude={crate_dir}{suffix}\",\n"));
            }
        }
        excludes
    };

    let mut yaml = String::new();

    // Header
    yaml.push_str(
        "# Generated by alef scaffold. Customize as needed.\n\
         default_install_hook_types:\n  - pre-commit\n  - commit-msg\n\
         exclude: ^target/|\\.alef/\n\n\
         repos:\n",
    );

    // Commit message linting
    yaml.push_str(&format!(
        "  # Commit message linting\n\
         \x20 - repo: https://github.com/Goldziher/gitfluff\n\
         \x20   rev: {gitfluff}\n\
         \x20   hooks:\n\
         \x20     - id: gitfluff-lint\n\
         \x20       args: [\"--write\"]\n\
         \x20       stages: [commit-msg]\n\n",
        gitfluff = tv::precommit::GITFLUFF_REV,
    ));

    // General file checks
    yaml.push_str(&format!(
        "  # General file checks\n\
         \x20 - repo: https://github.com/pre-commit/pre-commit-hooks\n\
         \x20   rev: {pre_commit_hooks}\n\
         \x20   hooks:\n\
         \x20     - id: trailing-whitespace\n\
         \x20     - id: end-of-file-fixer\n\
         \x20     - id: check-merge-conflict\n\
         \x20     - id: check-added-large-files\n\
         \x20     - id: detect-private-key\n\
         \x20     - id: check-json\n\
         \x20     - id: check-yaml\n\
         \x20       args: [\"--allow-multiple-documents\", \"--unsafe\"]\n\
         \x20     - id: check-toml\n\
         \x20     - id: check-case-conflict\n\n",
        pre_commit_hooks = tv::precommit::PRE_COMMIT_HOOKS_REV,
    ));

    // TOML formatting (Python only)
    if has(Language::Python) {
        yaml.push_str(&format!(
            "  - repo: https://github.com/tox-dev/pyproject-fmt\n\
             \x20   rev: \"{pyproject_fmt}\"\n\
             \x20   hooks:\n\
             \x20     - id: pyproject-fmt\n\n",
            pyproject_fmt = tv::precommit::PYPROJECT_FMT_REV,
        ));
    }

    yaml.push_str(&format!(
        "  - repo: https://github.com/DevinR528/cargo-sort\n\
         \x20   rev: \"{cargo_sort}\"\n\
         \x20   hooks:\n\
         \x20     - id: cargo-sort\n\
         \x20       args: [-w]\n\n",
        cargo_sort = tv::precommit::CARGO_SORT_REV,
    ));

    // Rust: formatting, linting, unused deps, license/advisory
    yaml.push_str("  # Rust: formatting, linting, unused deps, license/advisory\n");
    yaml.push_str(&format!(
        "  - repo: https://github.com/AndrejOrsula/pre-commit-cargo\n\
         \x20   rev: {pre_commit_cargo}\n\
         \x20   hooks:\n\
         \x20     - id: cargo-fmt\n\
         \x20       args: [\"--all\"]\n\
         \x20       types: [rust]\n\
         \x20     - id: cargo-clippy\n\
         \x20       args:\n\
         \x20         [\n\
         \x20           \"--fix\",\n\
         \x20           \"--allow-dirty\",\n\
         \x20           \"--allow-staged\",\n\
         \x20           \"--workspace\",\n\
         \x20           \"--all-features\",\n",
        pre_commit_cargo = tv::precommit::PRE_COMMIT_CARGO_REV,
    ));
    yaml.push_str(&clippy_excludes);
    yaml.push_str(
        "            \"--all-targets\",\n\
         \x20           \"--\",\n\
         \x20           \"-D\",\n\
         \x20           \"warnings\",\n\
         \x20         ]\n\n",
    );

    yaml.push_str(&format!(
        "  - repo: https://github.com/bnjbvr/cargo-machete\n\
         \x20   rev: {cargo_machete}\n\
         \x20   hooks:\n\
         \x20     - id: cargo-machete\n\n\
         \x20 - repo: https://github.com/EmbarkStudios/cargo-deny\n\
         \x20   rev: {cargo_deny}\n\
         \x20   hooks:\n\
         \x20     - id: cargo-deny\n\
         \x20       args: [\"check\"]\n\n",
        cargo_machete = tv::precommit::CARGO_MACHETE_REV,
        cargo_deny = tv::precommit::CARGO_DENY_REV,
    ));

    // Markdown
    yaml.push_str(&format!(
        "  # Markdown\n\
         \x20 - repo: https://github.com/rvben/rumdl-pre-commit\n\
         \x20   rev: \"{rumdl}\"\n\
         \x20   hooks:\n\
         \x20     - id: rumdl-fmt\n\n",
        rumdl = tv::precommit::RUMDL_REV,
    ));

    // Shell, Dockerfile, and docs prose (shared kreuzberg-dev hooks)
    yaml.push_str(&format!(
        "  # Shell, Dockerfile, and docs prose (shared kreuzberg-dev hooks)\n\
         \x20 - repo: https://github.com/kreuzberg-dev/pre-commit-hooks\n\
         \x20   rev: {kreuzberg_hooks}\n\
         \x20   hooks:\n\
         \x20     - id: shfmt\n\
         \x20     - id: shellcheck\n\
         \x20     - id: hadolint\n\
         \x20     - id: textlint\n\n",
        kreuzberg_hooks = tv::precommit::KREUZBERG_PRECOMMIT_HOOKS_REV,
    ));

    // Alef: readme, verify bindings, sync versions
    yaml.push_str(&format!(
        "  # Alef: generate READMEs, verify bindings, sync versions\n\
         \x20 - repo: https://github.com/kreuzberg-dev/alef\n\
         \x20   rev: {alef}\n\
         \x20   hooks:\n\
         \x20     - id: alef-readme\n\
         \x20     - id: alef-verify\n\
         \x20     - id: alef-sync-versions\n\n",
        alef = tv::precommit::ALEF_REV,
    ));

    // Spelling (last)
    yaml.push_str(&format!(
        "  # Spelling\n\
         \x20 - repo: https://github.com/crate-ci/typos\n\
         \x20   rev: {typos}\n\
         \x20   hooks:\n\
         \x20     - id: typos\n\
         \x20       args: [\"--force-exclude\"]\n\n",
        typos = tv::precommit::TYPOS_REV,
    ));

    vec![GeneratedFile {
        path: PathBuf::from(".pre-commit-config.yaml"),
        content: yaml,
        generated_header: false,
    }]
}
