use crate::backends::java::type_map::{java_boxed_type, java_type};
use crate::core::hash::{self, CommentStyle};
use crate::core::ir::{EnumDef, EnumVariant, FieldDef, TypeRef};
use heck::{ToLowerCamelCase, ToShoutySnakeCase};

use super::serializers::{DEFAULT_TAG_FIELD, gen_sealed_union_deserializer, gen_sealed_union_serializer};
use crate::backends::java::gen_bindings::helpers::{
    RECORD_LINE_WRAP_THRESHOLD, emit_javadoc, escape_javadoc_line, is_tuple_field_name, java_apply_rename_all,
    qualify_shadowed_type, safe_java_field_name,
};
use crate::codegen::java_literal::{escape_java_comment_text, escape_java_string_literal};
use crate::codegen::naming::wire_field_name;
use crate::codegen::serde_enum_repr::{SerdeEnumRepr, serde_enum_repr};

/// True when the Java binding backend emits `enum_def` as a plain `enum` with a `getValue()`
/// accessor (`simple_enum_class.jinja`), rather than a tagged- or untagged-union wrapper class
/// (`gen_java_tagged_union` / `gen_java_untagged_wrapper`, neither of which declare
/// `getValue()`). `gen_enum_class` below calls this directly to pick its branch, so the two
/// can never disagree; callers outside this module (e.g. e2e assertion codegen deciding
/// whether a field access may append `.getValue()`) must go through this function rather than
/// re-deriving the same condition, for the same reason. ~keep
pub(crate) fn emits_get_value(enum_def: &EnumDef) -> bool {
    let has_data_variants = enum_def.variants.iter().any(|v| !v.fields.is_empty());
    !((enum_def.serde_tag.is_some() && has_data_variants) || (enum_def.serde_untagged && has_data_variants))
}

pub(crate) fn gen_enum_class(package: &str, enum_def: &EnumDef, main_class: &str, text_types: &[String]) -> String {
    if !emits_get_value(enum_def) {
        if enum_def.serde_tag.is_some() {
            return gen_java_tagged_union(package, enum_def);
        }
        let emit_text = text_types.iter().any(|t| t == &enum_def.name);
        return gen_java_untagged_wrapper(package, enum_def, main_class, emit_text);
    }

    let header = hash::header(CommentStyle::DoubleSlash);
    let imports = [
        "com.fasterxml.jackson.annotation.JsonCreator",
        "com.fasterxml.jackson.annotation.JsonValue",
    ];
    let mut out = crate::backends::java::template_env::render(
        "java_file_header.jinja",
        minijinja::context! { header => header, package => package, imports => &imports },
    );
    out.push('\n');

    let mut enum_javadocs = String::new();
    let enum_doc = if enum_def.doc.is_empty() {
        format!("Auto-generated by alef from Rust type {}.", enum_def.name)
    } else {
        enum_def.doc.clone()
    };
    emit_javadoc(&mut enum_javadocs, &enum_doc, "");
    let mut variants_block = String::new();
    for (i, variant) in enum_def.variants.iter().enumerate() {
        let comma = if i < enum_def.variants.len() - 1 { "," } else { ";" };
        let json_name = variant
            .serde_rename
            .clone()
            .unwrap_or_else(|| java_apply_rename_all(&variant.name, enum_def.serde_rename_all.as_deref()));
        emit_javadoc(&mut variants_block, &variant.doc, "    ");
        variants_block.push_str("    ");
        variants_block.push_str(&crate::codegen::naming::public_host_identifier(
            crate::core::config::Language::Java,
            crate::codegen::naming::PublicIdentifierKind::EnumVariant,
            &variant.name,
        ));
        variants_block.push_str("(\"");
        variants_block.push_str(&escape_java_string_literal(&json_name));
        variants_block.push_str("\")");
        variants_block.push_str(comma);
        variants_block.push('\n');
    }
    variants_block.push('\n');

    let excluded_variant_json_names: Vec<String> = enum_def
        .excluded_variants
        .iter()
        .map(|v| {
            // Rendered into a `//` comment by `simple_enum_class.jinja`, not into a literal. ~keep
            escape_java_comment_text(
                &v.serde_rename
                    .clone()
                    .unwrap_or_else(|| java_apply_rename_all(&v.name, enum_def.serde_rename_all.as_deref())),
            )
        })
        .collect();

    out.push_str(&crate::backends::java::template_env::render(
        "simple_enum_class.jinja",
        minijinja::context! {
            javadocs => enum_javadocs,
            enum_name => &enum_def.name,
            variants_block => variants_block,
            has_excluded_variants => !excluded_variant_json_names.is_empty(),
            excluded_variant_names => excluded_variant_json_names,
        },
    ));

    out
}

/// Emit a transparent JsonNode-wrapper for `#[serde(untagged)]` enums.
///
/// Untagged unions like `EmbeddingInput = Single(String) | Multiple(Vec<String>)`
/// have no on-wire discriminator. Jackson's default deserialization tries to match
/// the JSON shape against the Java type; for plain enums it calls `fromValue(...)`
/// which throws on any value that does not match a variant name. The wrapper class
/// holds the JsonNode verbatim, with `@JsonValue` for serialization and
/// `@JsonCreator(mode=DELEGATING)` so Jackson hands the parsed JsonNode straight
/// through. The Rust core (serde) resolves the variant on the way in.
///
/// When `emit_text` is true, a `text()` method is appended that extracts the
/// plain-text display value: a JSON string is returned verbatim; a JSON array of
/// objects with `"type":"text"` has their `"text"` fields concatenated; otherwise
/// an empty string is returned.
fn gen_java_untagged_wrapper(package: &str, enum_def: &EnumDef, main_class: &str, emit_text: bool) -> String {
    let header = hash::header(CommentStyle::DoubleSlash);
    let doc = enum_def
        .doc
        .lines()
        .next()
        .map(|line| escape_javadoc_line(line.trim()))
        .unwrap_or_default();
    let exception_class = format!("{main_class}Exception");
    crate::backends::java::template_env::render(
        "untagged_union_wrapper.jinja",
        minijinja::context! {
            header => header,
            package => package,
            class_name => &enum_def.name,
            doc => doc,
            exception_class => exception_class,
            emit_text => emit_text,
            typed_list_writers => untagged_typed_list_writers(enum_def),
        },
    )
}

/// One `ObjectWriter` constant the untagged wrapper needs, for a variant whose payload is a
/// `Vec<SomeNamedType>`.
#[derive(serde::Serialize)]
struct TypedListWriter {
    /// Java type name used in the `instanceof` guard that picks this writer.
    element_type: String,
    /// Name of the generated `private static final ObjectWriter` constant.
    constant: String,
    /// Right-hand side that builds the writer with the element type pinned.
    expression: String,
}

/// Collect the element-type-pinned writers `ofObject(Object)` needs.
///
/// `ofObject`'s parameter is `Object`, and Java erases a `List`'s element type, so
/// `MAPPER.valueToTree(list)` builds a `CollectionSerializer` with no element `TypeSerializer`:
/// each element is resolved through the UNTYPED `findValueSerializer` lookup and its
/// `@JsonTypeInfo` discriminator is silently dropped. The same value passed on its own keeps its
/// discriminator, because a root value goes through `findTypedValueSerializer`. Only the erased
/// container path is affected, and the tag-less tree is then frozen into the wrapper's stored
/// `JsonNode`, so nothing downstream can repair it.
///
/// The generator knows each variant's `TypeRef`, hence the element type statically, so it can pin
/// it with the same `writerFor(constructCollectionType(..))` mechanism the DTO marshal path uses.
/// Only `Vec<Named>` payloads are collected: a `Vec<String>` element type can never carry a
/// discriminator, and an untagged union may mix both (`Single(String) | Multiple(Vec<String>) |
/// Parts(Vec<SomePart>)`), so the guard has to be per element type rather than "is a list". ~keep
fn untagged_typed_list_writers(enum_def: &EnumDef) -> Vec<TypedListWriter> {
    let opaque_types = ahash::AHashSet::new();
    let mut writers: Vec<TypedListWriter> = Vec::new();
    for variant in &enum_def.variants {
        if variant.binding_excluded || variant.fields.len() != 1 {
            continue;
        }
        let ty = &variant.fields[0].ty;
        let TypeRef::Vec(inner) = ty else { continue };
        let TypeRef::Named(element_type) = inner.as_ref() else {
            continue;
        };
        if writers.iter().any(|w| &w.element_type == element_type) {
            continue;
        }
        writers.push(TypedListWriter {
            element_type: element_type.clone(),
            constant: format!("LIST_WRITER_{}", element_type.to_shouty_snake_case()),
            expression: crate::backends::java::gen_bindings::marshal::build_collection_writer_for(
                inner,
                ty,
                &opaque_types,
            ),
        });
    }
    writers
}

pub(crate) fn gen_java_tagged_union(package: &str, enum_def: &EnumDef) -> String {
    let repr = serde_enum_repr(enum_def);
    let tag_field = repr.tag().unwrap_or(DEFAULT_TAG_FIELD);
    let flags = tagged_union_flags(enum_def, &repr);

    let imports = tagged_union_imports(&flags);
    let header = hash::header(CommentStyle::DoubleSlash);
    let mut out = crate::backends::java::template_env::render(
        "java_file_header.jinja",
        minijinja::context! { header => header, package => package, imports => &imports },
    );
    out.push('\n');

    push_tagged_union_class_annotations(&mut out, enum_def, tag_field, flags.needs_unwrapped);

    for variant in &enum_def.variants {
        out.push('\n');
        push_tagged_union_variant(&mut out, variant, enum_def, package, &flags);
    }

    if flags.has_data_variants {
        push_tagged_union_accessor_methods(&mut out, enum_def, package, &flags.variant_names);
    }

    out.push_str("}\n");

    if flags.needs_unwrapped {
        out.push('\n');
        gen_sealed_union_deserializer(&mut out, package, enum_def);
        out.push('\n');
        gen_sealed_union_serializer(&mut out, package, enum_def);
    }

    out
}

/// Flags and lookups shared across `gen_java_tagged_union`'s emission stages, computed once from
/// the enum's shape so every stage dispatches on the same answer. ~keep
struct TaggedUnionFlags<'a> {
    variant_names: std::collections::HashSet<&'a str>,
    optional_type: &'static str,
    needs_json_property: bool,
    has_data_variants: bool,
    needs_list: bool,
    needs_map: bool,
    needs_optional: bool,
    needs_unwrapped: bool,
}

fn tagged_union_flags<'a>(enum_def: &'a EnumDef, repr: &SerdeEnumRepr) -> TaggedUnionFlags<'a> {
    let variant_names: std::collections::HashSet<&str> = enum_def.variants.iter().map(|v| v.name.as_str()).collect();
    let optional_type = if variant_names.contains("Optional") {
        "java.util.Optional"
    } else {
        "Optional"
    };

    let needs_json_property = enum_def
        .variants
        .iter()
        .any(|v| v.fields.iter().any(|f| !is_tuple_field_name(&f.name)));

    let has_data_variants = enum_def
        .variants
        .iter()
        .any(|v| !v.fields.is_empty() && is_tuple_field_name(&v.fields[0].name));

    let needs_list = !variant_names.contains("List")
        && enum_def
            .variants
            .iter()
            .any(|v| v.fields.iter().any(|f| matches!(&f.ty, TypeRef::Vec(_))));
    let needs_map = !variant_names.contains("Map")
        && enum_def
            .variants
            .iter()
            .any(|v| v.fields.iter().any(|f| matches!(&f.ty, TypeRef::Map(_, _))));
    let needs_optional =
        !variant_names.contains("Optional") && enum_def.variants.iter().any(|v| v.fields.iter().any(|f| f.optional));
    // `@JsonTypeInfo(Id.NAME, property = tag)` can only express serde's *internal* shape, so an
    // adjacently tagged enum must go through the hand-written codecs whatever its variants look
    // like — otherwise its payload lands beside the tag instead of under the content key. ~keep
    let needs_unwrapped = repr.content().is_some()
        || enum_def
            .variants
            .iter()
            .any(|v| v.fields.len() == 1 && is_tuple_field_name(&v.fields[0].name));

    TaggedUnionFlags {
        variant_names,
        optional_type,
        needs_json_property,
        has_data_variants,
        needs_list,
        needs_map,
        needs_optional,
        needs_unwrapped,
    }
}

fn tagged_union_imports(flags: &TaggedUnionFlags) -> Vec<&'static str> {
    let mut imports: Vec<&str> = vec![];
    if flags.needs_json_property {
        imports.push("com.fasterxml.jackson.annotation.JsonProperty");
    }
    if !flags.needs_unwrapped {
        imports.push("com.fasterxml.jackson.annotation.JsonSubTypes");
        imports.push("com.fasterxml.jackson.annotation.JsonTypeInfo");
    }
    if flags.needs_list {
        imports.push("java.util.List");
    }
    if flags.needs_map {
        imports.push("java.util.Map");
    }
    if flags.needs_optional {
        imports.push("java.util.Optional");
    }
    if flags.needs_unwrapped {
        imports.push("com.fasterxml.jackson.databind.deser.std.StdDeserializer");
        imports.push("com.fasterxml.jackson.databind.ser.std.StdSerializer");
        imports.push("com.fasterxml.jackson.core.JsonParser");
        imports.push("com.fasterxml.jackson.core.JsonGenerator");
        imports.push("com.fasterxml.jackson.databind.DeserializationContext");
        imports.push("com.fasterxml.jackson.databind.SerializerProvider");
        imports.push("com.fasterxml.jackson.databind.node.ObjectNode");
        imports.push("com.fasterxml.jackson.databind.annotation.JsonDeserialize");
        imports.push("com.fasterxml.jackson.databind.annotation.JsonSerialize");
    }
    if flags.has_data_variants {
        imports.push("org.jspecify.annotations.Nullable");
    }
    imports
}

fn push_tagged_union_class_annotations(out: &mut String, enum_def: &EnumDef, tag_field: &str, needs_unwrapped: bool) {
    let tagged_union_doc = if enum_def.doc.is_empty() {
        format!("Auto-generated by alef from Rust type {}.", enum_def.name)
    } else {
        enum_def.doc.clone()
    };
    emit_javadoc(out, &tagged_union_doc, "");
    if !needs_unwrapped {
        out.push_str("@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = \"");
        out.push_str(&escape_java_string_literal(tag_field));
        out.push_str("\", visible = false)\n");
        out.push_str("@JsonSubTypes({\n");
        for (i, variant) in enum_def.variants.iter().enumerate() {
            let discriminator = variant
                .serde_rename
                .clone()
                .unwrap_or_else(|| java_apply_rename_all(&variant.name, enum_def.serde_rename_all.as_deref()));
            let comma = if i < enum_def.variants.len() - 1 { "," } else { "" };
            out.push_str("    @JsonSubTypes.Type(value = ");
            out.push_str(&enum_def.name);
            out.push('.');
            out.push_str(&variant.name);
            out.push_str(".class, name = \"");
            out.push_str(&escape_java_string_literal(&discriminator));
            out.push_str("\")");
            out.push_str(comma);
            out.push('\n');
        }
        out.push_str("})\n");
    }
    out.push_str("@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)\n");
    if needs_unwrapped {
        out.push_str("@JsonDeserialize(using = ");
        out.push_str(&enum_def.name);
        out.push_str("Deserializer.class)\n");
        out.push_str("@JsonSerialize(using = ");
        out.push_str(&enum_def.name);
        out.push_str("Serializer.class)\n");
    }
    out.push_str("public sealed interface ");
    out.push_str(&enum_def.name);
    out.push_str(" {\n");
}

/// Emit one variant's record declaration: dispatches on the same unit-vs-data-payload shape
/// `gen_java_tagged_union`'s loop already dispatched on before this split. ~keep
fn push_tagged_union_variant(
    out: &mut String,
    variant: &EnumVariant,
    enum_def: &EnumDef,
    package: &str,
    flags: &TaggedUnionFlags,
) {
    let is_unit_tuple = variant.fields.len() == 1
        && is_tuple_field_name(&variant.fields[0].name)
        && matches!(&variant.fields[0].ty, TypeRef::Unit);
    if variant.fields.is_empty() || is_unit_tuple {
        push_tagged_union_unit_record(out, variant, enum_def);
    } else {
        let field_parts = tagged_union_variant_field_parts(variant, enum_def, package, flags);
        push_tagged_union_record_body(out, variant, enum_def, &field_parts);
    }
}

fn push_tagged_union_unit_record(out: &mut String, variant: &EnumVariant, enum_def: &EnumDef) {
    emit_javadoc(out, &variant.doc, "    ");
    out.push_str("    record ");
    out.push_str(&variant.name);
    out.push_str("() implements ");
    out.push_str(&enum_def.name);
    out.push_str(" {\n");
    out.push_str("    }\n");
}

/// The record component's Java type: dispatches on the same `f.optional` boxed-vs-unboxed shape
/// the field-parts map already dispatched on before this split. ~keep
fn tagged_union_field_ty(
    f: &FieldDef,
    package: &str,
    variant_names: &std::collections::HashSet<&str>,
    optional_type: &str,
) -> String {
    if f.optional {
        let inner = java_boxed_type(&f.ty);
        let inner_str = inner.as_ref();
        let mut inner_qualified = inner_str.to_string();
        if variant_names.contains("List") {
            inner_qualified = inner_qualified.replace("List<", "java.util.List<");
        }
        if variant_names.contains("Map") {
            inner_qualified = inner_qualified.replace("Map<", "java.util.Map<");
        }
        format!(
            "{optional_type}<{}>",
            qualify_shadowed_type(&inner_qualified, package, variant_names)
        )
    } else {
        let t = java_type(&f.ty);
        let mut t_str = t.into_owned();
        if variant_names.contains("List") {
            t_str = t_str.replace("List<", "java.util.List<");
        }
        if variant_names.contains("Map") {
            t_str = t_str.replace("Map<", "java.util.Map<");
        }
        qualify_shadowed_type(&t_str, package, variant_names)
    }
}

fn tagged_union_variant_field_parts(
    variant: &EnumVariant,
    enum_def: &EnumDef,
    package: &str,
    flags: &TaggedUnionFlags,
) -> Vec<String> {
    let variant_names = &flags.variant_names;
    let optional_type = flags.optional_type;
    variant
        .fields
        .iter()
        .map(|f| {
            let ftype = tagged_union_field_ty(f, package, variant_names, optional_type);
            if is_tuple_field_name(&f.name) {
                format!("{ftype} value")
            } else {
                let raw_field_name = f.name.trim_start_matches('_');
                let jname = safe_java_field_name(raw_field_name);
                // A struct-shaped variant's field names are a separate serde namespace
                // from the enum's own variant names: `serde_rename_all` cases variant
                // names, `rename_all_fields` cases these struct-variant field names, and
                // a field's own `serde_rename` wins over both. ~keep
                let json_name = wire_field_name(
                    raw_field_name,
                    f.serde_rename.as_deref(),
                    enum_def.rename_all_fields.as_deref(),
                );
                let json_literal = escape_java_string_literal(&json_name);
                format!("@JsonProperty(\"{json_literal}\") {ftype} {jname}")
            }
        })
        .collect()
}

fn push_tagged_union_record_body(out: &mut String, variant: &EnumVariant, enum_def: &EnumDef, field_parts: &[String]) {
    let fields_joined: String = field_parts.join(", ");
    let single_len = "    record ".len()
        + variant.name.len()
        + 1
        + fields_joined.len()
        + ") implements ".len()
        + enum_def.name.len()
        + " { }".len();

    emit_javadoc(out, &variant.doc, "    ");
    if single_len > RECORD_LINE_WRAP_THRESHOLD && field_parts.len() > 1 {
        out.push_str("    record ");
        out.push_str(&variant.name);
        out.push_str("(\n");
        for (i, fp) in field_parts.iter().enumerate() {
            let comma = if i < field_parts.len() - 1 { "," } else { "" };
            out.push_str("        ");
            out.push_str(fp);
            out.push_str(comma);
            out.push('\n');
        }
        out.push_str("    ) implements ");
        out.push_str(&enum_def.name);
        out.push_str(" {\n");
        out.push_str("    }\n");
    } else {
        out.push_str("    record ");
        out.push_str(&variant.name);
        out.push('(');
        out.push_str(&fields_joined);
        out.push_str(") implements ");
        out.push_str(&enum_def.name);
        out.push_str(" { }\n");
    }
}

fn push_tagged_union_accessor_methods(
    out: &mut String,
    enum_def: &EnumDef,
    package: &str,
    variant_names: &std::collections::HashSet<&str>,
) {
    out.push('\n');
    for variant in &enum_def.variants {
        if variant.fields.is_empty() || !is_tuple_field_name(&variant.fields[0].name) {
            continue;
        }
        if matches!(&variant.fields[0].ty, TypeRef::Unit) {
            continue;
        }
        let method_name = variant.name.to_lower_camel_case();
        let boxed_return_type = java_boxed_type(&variant.fields[0].ty);
        let return_type = qualify_shadowed_type(&boxed_return_type, package, variant_names);
        let variant_name = &variant.name;
        out.push_str("    /** Returns the ");
        out.push_str(variant_name);
        out.push_str(" data if this is a ");
        out.push_str(variant_name);
        out.push_str(" variant, otherwise null. */\n");
        out.push_str("    default @Nullable ");
        out.push_str(&return_type);
        out.push(' ');
        out.push_str(&method_name);
        out.push_str("() {\n");
        out.push_str("        return this instanceof ");
        out.push_str(variant_name);
        out.push_str(" variant ? variant.value() : null;\n");
        out.push_str("    }\n");
        out.push('\n');
    }
}
