//! Enumeration of every marker spelling alef's emitters actually produce.
//!
//! Two sources, both derived from real emitters rather than hand-copied prose so this list can't
//! silently drift from what alef actually ships:
//!
//! - Rust-side literals that have been hoisted into named constants in [`crate::core::hash`]
//!   (`STANDARD_HEADER_LINE`, `SWIFT_C_UMBRELLA_HEADER_MARKER`, `CITATION_CFF_HEADER_LINE`,
//!   `SELF_MARKING_HEADER_LINE`) because at least one call site duplicated the literal, or the
//!   brief's confirmed example lived here. Every production call site listed in each constant's
//!   doc comment now reads the same constant, so a spelling change only has to compile once.
//! - `.jinja` templates that bake their own header line directly into the template file instead
//!   of going through [`crate::core::hash::header`]/[`crate::core::hash::header_for_config`].
//!   These are pulled in with `include_str!`, which embeds the exact bytes of the template file
//!   at compile time -- if a template's header line is ever edited, this list sees the new text
//!   automatically, and [`super::every_known_marker_spelling_is_recognized`] re-checks it. This
//!   can only go stale by omission (a brand-new template not yet added below), not by drift of an
//!   already-listed one.
//!
//! Deliberately built as two separate slices (constants can't hold a computed concatenation of
//! `include_str!` calls without repeating each entry's index by hand, which is exactly the kind
//! of hand-maintained list this module exists to avoid) and chained at iteration time by
//! [`all_known_marker_texts`]. ~keep

use crate::core::hash::{
    CITATION_CFF_HEADER_LINE, SELF_MARKING_HEADER_LINE, SELF_MARKING_HEADER_LINE_HASH, STANDARD_HEADER_LINE,
    SWIFT_C_UMBRELLA_HEADER_MARKER,
};

/// Marker spellings hoisted into named Rust constants because a real production call site
/// duplicated the literal, or the fix's brief confirmed the exact text as a live example.
const RUST_CONSTANT_MARKERS: &[&str] = &[
    STANDARD_HEADER_LINE,
    SWIFT_C_UMBRELLA_HEADER_MARKER,
    CITATION_CFF_HEADER_LINE,
    SELF_MARKING_HEADER_LINE,
    SELF_MARKING_HEADER_LINE_HASH,
];

/// `.jinja` templates that hardcode their own alef marker line rather than receiving one via a
/// `{{ header }}` context variable. Grouped by backend for readability; order is not significant.
const SELF_MARKING_TEMPLATES: &[&str] = &[
    // Go: the two spellings that gave this defect its name -- the standard prose header, and
    // Go's own "Code generated ... by <tool>. DO NOT EDIT." idiom.
    include_str!("../../../backends/go/templates/cmd_setup_main.go.jinja"),
    include_str!("../../../backends/go/templates/native_setup.go.jinja"),
    // Dart.
    include_str!("../../../backends/dart/templates/dart_barrel_file.jinja"),
    include_str!("../../../backends/dart/templates/dart_ffi_file_header.jinja"),
    include_str!("../../../backends/dart/templates/bin_download_libs.jinja"),
    include_str!("../../../backends/dart/templates/dart_native_loader_helper.jinja"),
    include_str!("../../../backends/dart/templates/dart_ffi_wrapper_file.jinja"),
    include_str!("../../../backends/dart/templates/service_api/file_header.rs.jinja"),
    // Kotlin / Kotlin-Android / JNI.
    include_str!("../../../backends/kotlin_android/templates/kt_file.jinja"),
    include_str!("../../../backends/kotlin/templates/jni_bridge_file.jinja"),
    include_str!("../../../backends/kotlin/templates/jni_client_file.jinja"),
    include_str!("../../../backends/jni/templates/lib_header.rs.jinja"),
    // Swift.
    include_str!("../../../backends/swift/templates/swift_trait_bridge_file.swift.jinja"),
    include_str!("../../../backends/swift/templates/swift_trait_bridge_overloads.swift.jinja"),
    include_str!("../../../backends/swift/templates/swift_inbound_box_preamble.swift.jinja"),
    include_str!("../../../backends/swift/templates/swift_plugin_bridge_protocol.swift.jinja"),
    include_str!("../../../backends/swift/templates/swift_module_header.swift.jinja"),
    // C# -- includes the two REFUSED "Auto-generated by alef" (capital A) sites the brief
    // confirmed, and the REFUSED lowercase "generated by alef" trait-bridge header.
    include_str!("../../../backends/csharp/templates/service_class_header.jinja"),
    include_str!("../../../backends/csharp/templates/service_native_methods_header.jinja"),
    include_str!("../../../backends/csharp/templates/native_methods_header.jinja"),
    include_str!("../../../backends/csharp/templates/exception_class.jinja"),
    include_str!("../../../backends/csharp/templates/untagged_union_wrapper.jinja"),
    include_str!("../../../backends/csharp/templates/enum_header.jinja"),
    include_str!("../../../backends/csharp/templates/opaque_handle_header.jinja"),
    include_str!("../../../backends/csharp/templates/wrapper_class_header.jinja"),
    include_str!("../../../backends/csharp/templates/trait_bridges_header.jinja"),
    // FFI / cbindgen.
    include_str!("../../../backends/ffi/templates/cbindgen_toml.jinja"),
    include_str!("../../../backends/ffi/templates/build_rs.jinja"),
    // e2e / codegen templates.
    include_str!("../../../e2e/templates/ruby/rubocop.yml.jinja"),
    include_str!("../../../codegen/templates/error_gen/java_error_base.jinja"),
    include_str!("../../../codegen/templates/error_gen/java_error_variant.jinja"),
    include_str!("../../../codegen/templates/config_gen/java_builder.jinja"),
    include_str!("../../../codegen/templates/error_gen/csharp_error_base.jinja"),
    include_str!("../../../codegen/templates/error_gen/csharp_error_variant.jinja"),
    include_str!("../../../codegen/templates/config_gen/csharp_record.jinja"),
];

/// Every marker spelling this crate is known to emit: [`RUST_CONSTANT_MARKERS`] chained with
/// [`SELF_MARKING_TEMPLATES`]. See the module doc for how this stays derived from real emitters
/// instead of hand-copied prose. ~keep
pub(crate) fn all_known_marker_texts() -> impl Iterator<Item = &'static str> {
    RUST_CONSTANT_MARKERS.iter().chain(SELF_MARKING_TEMPLATES).copied()
}

#[test]
fn self_marking_templates_enumeration_is_non_empty() {
    // A cheap tripwire against an accidental empty list (e.g. every entry removed by mistake),
    // which would make `every_known_marker_spelling_is_recognized` vacuously pass. Exact counts
    // deliberately aren't asserted here -- the list is expected to grow as backends are added.
    assert!(!RUST_CONSTANT_MARKERS.is_empty());
    assert!(!SELF_MARKING_TEMPLATES.is_empty());
    assert_eq!(
        all_known_marker_texts().count(),
        RUST_CONSTANT_MARKERS.len() + SELF_MARKING_TEMPLATES.len()
    );
}

/// The enumeration above can only go stale one way: by omission. A brand-new self-marking
/// template is not in [`SELF_MARKING_TEMPLATES`], so nothing checks its spelling, and the file it
/// stamps is refused on every run forever with no diagnostic -- which is the exact defect this
/// module was written to close, reappearing one template later.
///
/// So don't maintain the list: walk the shipped templates and ask each one directly. A template
/// fails here if it clearly *intends* to stamp provenance -- its text says something was
/// "generated by" and names alef -- yet [`content_has_alef_marker`] would still refuse the result,
/// whether or not anyone remembered to add it to the list above.
///
/// The intent test is deliberately narrower than [`near_miss_marker`], which the runtime refusal
/// uses. That one fires on any leading line mentioning alef and "generated" independently, which
/// is right for a diagnostic on a file already being refused -- a false positive there costs one
/// extra hint -- but wrong as a build gate: it flags body prose like "pass this value back to
/// Alef-generated bridge APIs" in partial templates that were never headers at all. Requiring the
/// contiguous "generated by" phrasing keeps this gate on lines that are actually trying to be
/// markers. ~keep
#[test]
fn no_shipped_template_stamps_a_marker_alef_would_refuse_to_read_back() {
    use crate::core::hash::content_has_alef_marker;

    /// A line that means to be a provenance marker: it claims generation and names alef.
    /// A line satisfying this that `content_has_alef_marker` still refuses is a broken marker.
    fn intends_to_mark(line: &str) -> bool {
        let lowered = line.to_ascii_lowercase();
        lowered.contains("generated by") && lowered.contains("alef")
    }

    fn collect_jinja(dir: &std::path::Path, found: &mut Vec<std::path::PathBuf>) {
        let entries = std::fs::read_dir(dir).unwrap_or_else(|err| panic!("read {}: {err}", dir.display()));
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                collect_jinja(&path, found);
            } else if path.extension().is_some_and(|ext| ext == "jinja") {
                found.push(path);
            }
        }
    }

    let src = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("src");
    let mut templates = Vec::new();
    collect_jinja(&src, &mut templates);

    // Non-vacuity guard: a walk that finds nothing passes every assertion below and is
    // indistinguishable from a clean result. alef ships hundreds of templates; if this floor is
    // ever hit, the walk is broken, not the templates. ~keep
    assert!(
        templates.len() > 100,
        "expected the template walk to find hundreds of .jinja files under {}, found {} -- the \
         walk is broken and this test is checking nothing",
        src.display(),
        templates.len()
    );

    let mut refused: Vec<String> = Vec::new();
    let mut marked = 0usize;
    for path in &templates {
        let Ok(content) = std::fs::read_to_string(path) else {
            continue;
        };
        if content_has_alef_marker(&content) {
            marked += 1;
        } else if let Some(broken) = content.lines().find(|line| intends_to_mark(line)) {
            let relative = path.strip_prefix(&src).unwrap_or(path);
            refused.push(format!("  {}: {}", relative.display(), broken.trim()));
        }
    }

    // Second non-vacuity guard: the walk must actually reach self-marking templates, or every
    // near-miss branch above is dead and the test proves nothing about spellings. ~keep
    assert!(
        marked > 0,
        "no walked template carried a recognized alef marker, so the broken-marker check never ran"
    );

    assert!(
        refused.is_empty(),
        "these templates stamp a marker `content_has_alef_marker` refuses, so every file they \
         generate is un-ownable and silently re-refused forever:\n{}",
        refused.join("\n")
    );
}

/// The two marker forms a consumer census found that contain neither `generated by alef` nor any
/// case variant of it. Pinned verbatim as reported, because both live in shipped output — a
/// Homebrew `Brewfile` driving a published install path, and real C source in an R binding — and
/// because the substring predicate they defeat is the one thing standing between them and being
/// refused on every run forever.
///
/// A census that greps for the marker it expects cannot report the marker it does not: the
/// consumer's own first pass used a regex requiring `generated by alef`, so it was structurally
/// incapable of finding these two and reported a clean result over a conditioned population. They
/// surfaced only on a second pass keyed on `alef` and `do not edit` independently. ~keep
#[test]
fn the_two_non_conforming_marker_forms_a_consumer_census_found_are_recognized() {
    use crate::core::hash::content_has_alef_marker;

    let brewfile = "# Brewfile — managed by alef. DO NOT EDIT.\nbrew \"cmake\"\n";
    let r_entrypoint = "// Generated entrypoint: forwards to the extendr-generated init function.\n\
                        // Do not edit — regenerate with `alef generate`.\n#include <R.h>\n";

    assert!(
        content_has_alef_marker(brewfile),
        "a Brewfile saying `managed by alef` is an ownership claim; refusing it makes the file \
         unadoptable forever, and it drives a published install path"
    );
    assert!(
        content_has_alef_marker(r_entrypoint),
        "this header names alef and says do not edit, but never adjacently — a human reads it as a \
         marker and a contiguous substring test does not"
    );

    // Negative control. Without it, a predicate that accepted everything would satisfy the two
    // assertions above and look like a fix. ~keep
    assert!(
        !content_has_alef_marker("// Hand-written helper. Edit freely.\nint main(void) { return 0; }\n"),
        "a file making no ownership claim must still be refused"
    );
    assert!(
        !content_has_alef_marker("// Managed by hand; alef is not involved in this file.\n"),
        "naming alef in prose is not an ownership claim — the marker must be a contiguous phrase, \
         or any file discussing alef becomes alef-owned"
    );
}
