use crate::type_map::python_type;
use alef_core::ir::{ApiSurface, EnumDef, FunctionDef, MethodDef, TypeDef, TypeRef};

/// Convert a name to be safe for Python by escaping reserved keywords.
fn python_safe_name(name: &str) -> String {
    const PYTHON_KEYWORDS: &[&str] = &[
        "from", "import", "class", "def", "return", "yield", "pass", "break", "continue", "and", "or", "not", "is",
        "in", "if", "else", "elif", "for", "while", "with", "as", "try", "except", "finally", "raise", "del", "global",
        "nonlocal", "lambda", "assert", "type",
        // Built-in constants that are also reserved in some contexts
        "None", "True", "False",
    ];
    if PYTHON_KEYWORDS.contains(&name) {
        format!("{name}_")
    } else {
        name.to_string()
    }
}

/// Check if a parameter name shadows a Python builtin (triggers ruff A002).
fn is_python_builtin_name(name: &str) -> bool {
    const BUILTINS: &[&str] = &[
        "id",
        "type",
        "input",
        "hash",
        "format",
        "dir",
        "help",
        "list",
        "map",
        "filter",
        "range",
        "set",
        "dict",
        "str",
        "int",
        "float",
        "bool",
        "bytes",
        "tuple",
        "len",
        "max",
        "min",
        "sum",
        "abs",
        "all",
        "any",
        "print",
        "open",
        "next",
        "iter",
        "vars",
        "zip",
        "object",
        "property",
        "super",
        "staticmethod",
        "classmethod",
        "compile",
        "exec",
        "eval",
    ];
    BUILTINS.contains(&name)
}

/// For constructor parameters, use the enum type name for enum fields.
/// The enum stub has `__init__(self, value: int | str)` so callers can pass
/// either a raw string/int or an enum instance.
/// Data enum fields accept a `dict`.
fn constructor_param_type(ty: &TypeRef, api: &ApiSurface) -> String {
    use alef_codegen::generators::enum_has_data_variants;
    let enum_names: std::collections::HashSet<String> = api.enums.iter().map(|e| e.name.clone()).collect();
    let data_enum_names: std::collections::HashSet<String> = api
        .enums
        .iter()
        .filter(|e| enum_has_data_variants(e))
        .map(|e| e.name.clone())
        .collect();

    match ty {
        TypeRef::Named(name) if data_enum_names.contains(name) => format!("{} | dict[str, Any]", name),
        TypeRef::Named(name) if enum_names.contains(name) => format!("{} | str", name),
        TypeRef::Optional(inner) => match inner.as_ref() {
            TypeRef::Named(name) if data_enum_names.contains(name) => {
                format!("{} | dict[str, Any] | None", name)
            }
            TypeRef::Named(name) if enum_names.contains(name) => format!("{} | str | None", name),
            _ => python_type(ty),
        },
        _ => python_type(ty),
    }
}

pub fn gen_stubs(api: &ApiSurface) -> String {
    let mut lines = vec![
        "# This file is auto-generated by alef. DO NOT EDIT.".to_string(),
        "# Re-generate with: alef generate".to_string(),
        "".to_string(),
        "from typing import Any".to_string(),
        "".to_string(),
    ];

    // Generate type stubs
    for typ in api.types.iter().filter(|typ| !typ.is_trait) {
        if typ.is_opaque {
            lines.push(gen_opaque_type_stub(typ));
            lines.push("".to_string());
        } else {
            lines.push(gen_type_stub(typ, api));
            lines.push("".to_string());
        }
    }

    // Generate enum stubs
    for enum_def in &api.enums {
        lines.push(gen_enum_stub(enum_def));
        lines.push("".to_string());
    }

    // Generate function stubs
    for func in &api.functions {
        lines.push(gen_function_stub(func));
        lines.push("".to_string());
    }

    lines.join("\n")
}

/// Generate a Python type stub for an opaque type (no fields, only methods).
fn gen_opaque_type_stub(typ: &TypeDef) -> String {
    let mut lines = vec![];

    lines.push(format!("class {}:", typ.name));
    // D101: every public class needs a docstring.
    let doc = if typ.doc.is_empty() {
        format!("Wrapper for {}.", typ.name)
    } else {
        typ.doc.lines().next().unwrap_or("").to_string()
    };
    lines.push(format!("    \"\"\"{}\"\"\"", doc));

    // Instance methods
    for method in &typ.methods {
        if !method.is_static {
            lines.push(gen_method_stub(method, false));
        }
    }

    // Static methods
    for method in &typ.methods {
        if method.is_static {
            lines.push(gen_method_stub(method, true));
        }
    }

    // If no methods at all, use `...` (PYI009: empty body should use `...` not `pass`)
    if typ.methods.is_empty() {
        lines.push("    ...".to_string());
    }

    lines.join("\n")
}

/// Generate a Python type stub for a struct.
fn gen_type_stub(typ: &TypeDef, api: &ApiSurface) -> String {
    let mut lines = vec![];

    lines.push(format!("class {}:", typ.name));
    // D101: every public class needs a docstring.
    let doc = if typ.doc.is_empty() {
        format!("Wrapper for {}.", typ.name)
    } else {
        typ.doc.lines().next().unwrap_or("").to_string()
    };
    lines.push(format!("    \"\"\"{}\"\"\"", doc));

    // Add field type annotations
    for field in &typ.fields {
        let type_str = python_type(&field.ty);
        // Duration fields on has_default types are Option<u64> in PyO3, so annotate as int | None
        let is_optional_duration = typ.has_default && matches!(field.ty, TypeRef::Duration) && !field.optional;
        let field_type = if (is_optional_duration || field.optional) && !type_str.contains("| None") {
            format!("{} | None", type_str)
        } else {
            type_str
        };
        lines.push(format!("    {}: {}", field.name, field_type));
    }

    // Add __init__ signature
    lines.push(gen_type_init_stub(typ, api));

    // Add instance methods
    for method in &typ.methods {
        if !method.is_static {
            lines.push(gen_method_stub(method, false));
        }
    }

    // Add static methods
    for method in &typ.methods {
        if method.is_static {
            lines.push(gen_method_stub(method, true));
        }
    }

    lines.join("\n")
}

/// Generate __init__ signature stub for a struct.
fn gen_type_init_stub(typ: &TypeDef, api: &ApiSurface) -> String {
    // Partition fields into required (non-optional) and optional.
    // Duration fields on has_default types are Option<u64> in PyO3 and must go in the optional
    // partition (the binding accepts `None` and applies its own default).
    let (required, optional): (Vec<_>, Vec<_>) = typ.fields.iter().partition(|f| {
        let is_optional_duration = typ.has_default && matches!(f.ty, TypeRef::Duration) && !f.optional;
        !f.optional && !is_optional_duration
    });

    // Generate required params first, then optional params
    // For constructor params, use str instead of enum types (PyO3 accepts any string)
    let mut params: Vec<String> = required
        .iter()
        .map(|f| {
            let param_type = constructor_param_type(&f.ty, api);
            format!("{}: {}", f.name, param_type)
        })
        .collect();

    params.extend(optional.iter().map(|f| {
        let type_str = constructor_param_type(&f.ty, api);
        let param_type = if !type_str.contains("| None") {
            format!("{} | None", type_str)
        } else {
            type_str
        };
        format!("{}: {} = None", f.name, param_type)
    }));

    // If any parameter shadows a Python builtin we must use the multi-line form so we can
    // append `# noqa: A002` on those lines. The noqa suppression is not valid on a single-line
    // def, so force wrapping whenever a builtin-shadowing param is present.
    let has_builtin_param = params
        .iter()
        .any(|p| is_python_builtin_name(p.split(':').next().unwrap_or("").trim()));
    let single_line = format!("    def __init__(self, {}) -> None: ...", params.join(", "));
    if single_line.len() <= 100 && !has_builtin_param {
        single_line
    } else {
        // Wrap parameters across multiple lines to stay within 100 chars.
        // For params that shadow Python builtins, append `# noqa: A002` AFTER the comma.
        let mut wrapped = String::from("    def __init__(\n");
        wrapped.push_str("        self,\n");
        for param in &params {
            let name = param.split(':').next().unwrap_or("").trim();
            if is_python_builtin_name(name) {
                wrapped.push_str(&format!("        {},  # noqa: A002\n", param));
            } else {
                wrapped.push_str(&format!("        {},\n", param));
            }
        }
        wrapped.push_str("    ) -> None: ...");
        wrapped
    }
}

/// Generate a method stub.
fn gen_method_stub(method: &MethodDef, is_static: bool) -> String {
    // Partition params into required (non-optional) and optional
    let (required, optional): (Vec<_>, Vec<_>) = method.params.iter().partition(|p| !p.optional);

    // Generate required params first, then optional params
    let mut params: Vec<String> = required
        .iter()
        .map(|p| {
            let param_type = python_type(&p.ty);
            format!("{}: {}", p.name, param_type)
        })
        .collect();

    params.extend(optional.iter().map(|p| {
        let type_str = python_type(&p.ty);
        let param_type = if !type_str.contains("| None") {
            format!("{} | None", type_str)
        } else {
            type_str
        };
        format!("{}: {} = None", p.name, param_type)
    }));

    let return_type = python_type(&method.return_type);
    let indent = "    ";
    let safe_name = python_safe_name(&method.name);

    if is_static {
        if params.is_empty() {
            format!(
                "{}@staticmethod\n{}def {}() -> {}: ...",
                indent, indent, safe_name, return_type
            )
        } else {
            let single_line = format!(
                "{}@staticmethod\n{}def {}({}) -> {}: ...",
                indent,
                indent,
                safe_name,
                params.join(", "),
                return_type
            );
            // Check the def line (second line) for length
            let def_line = format!(
                "{}def {}({}) -> {}: ...",
                indent,
                safe_name,
                params.join(", "),
                return_type
            );
            if def_line.len() <= 100 {
                single_line
            } else {
                let mut wrapped = format!("{}@staticmethod\n{}def {}(\n", indent, indent, safe_name);
                for param in &params {
                    wrapped.push_str(&format!("{}    {},\n", indent, param));
                }
                wrapped.push_str(&format!("{}) -> {}: ...", indent, return_type));
                wrapped
            }
        }
    } else if params.is_empty() {
        format!("{}def {}(self) -> {}: ...", indent, safe_name, return_type)
    } else {
        let single_line = format!(
            "{}def {}(self, {}) -> {}: ...",
            indent,
            safe_name,
            params.join(", "),
            return_type
        );
        if single_line.len() <= 100 {
            single_line
        } else {
            let mut wrapped = format!("{}def {}(\n", indent, safe_name);
            wrapped.push_str(&format!("{}    self,\n", indent));
            for param in &params {
                wrapped.push_str(&format!("{}    {},\n", indent, param));
            }
            wrapped.push_str(&format!("{}) -> {}: ...", indent, return_type));
            wrapped
        }
    }
}

/// Generate a Python enum stub.
fn gen_enum_stub(enum_def: &EnumDef) -> String {
    use alef_codegen::generators::enum_has_data_variants;
    let mut lines = vec![];

    lines.push(format!("class {}:", enum_def.name));
    // D101: every public class needs a docstring.
    let doc = if enum_def.doc.is_empty() {
        format!("Wrapper for {}.", enum_def.name)
    } else {
        enum_def.doc.lines().next().unwrap_or("").to_string()
    };
    lines.push(format!("    \"\"\"{}\"\"\"", doc));

    if enum_has_data_variants(enum_def) {
        // Data enums are frozen structs accepting a dict.
        lines.push("    def __init__(self, value: dict[str, Any]) -> None: ...".to_string());
    } else {
        for variant in &enum_def.variants {
            lines.push(format!(
                "    {}: {} = ...",
                python_safe_name(&variant.name),
                enum_def.name
            ));
        }
        lines.push("    def __init__(self, value: int | str) -> None: ...".to_string());
    }

    lines.join("\n")
}

/// Generate a function stub.
fn gen_function_stub(func: &FunctionDef) -> String {
    // Partition params into required (non-optional) and optional
    let (required, optional): (Vec<_>, Vec<_>) = func.params.iter().partition(|p| !p.optional);

    // Generate required params first, then optional params
    let mut params: Vec<String> = required
        .iter()
        .map(|p| {
            let param_type = python_type(&p.ty);
            format!("{}: {}", p.name, param_type)
        })
        .collect();

    params.extend(optional.iter().map(|p| {
        let type_str = python_type(&p.ty);
        let param_type = if !type_str.contains("| None") {
            format!("{} | None", type_str)
        } else {
            type_str
        };
        format!("{}: {} = None", p.name, param_type)
    }));

    let return_type = python_type(&func.return_type);
    let safe_name = python_safe_name(&func.name);

    let single_line = format!("def {}({}) -> {}: ...", safe_name, params.join(", "), return_type);
    if single_line.len() <= 100 {
        single_line
    } else {
        let mut wrapped = format!("def {}(\n", safe_name);
        for param in &params {
            wrapped.push_str(&format!("    {},\n", param));
        }
        wrapped.push_str(&format!(") -> {}: ...", return_type));
        wrapped
    }
}
