//! Kotlin source emitter for the AAR module.
//!
//! Adapted from the legacy `alef-backend-kotlin::gen_android` module with two
//! corrections relative to the original:
//!
//! 1. The wrapper class is emitted at `<pkg_path>/<Module>.kt` rather than
//!    being split between two diverging directories (the historical
//!    backend/scaffold drift that produced `<pkg>/android/<Module>Android.kt`).
//! 2. A top-of-object `init { System.loadLibrary(...) }` block loads the
//!    bundled native cdylib so consumers do not need to call
//!    `System.loadLibrary` themselves.

use std::collections::BTreeSet;
use std::path::PathBuf;

use alef_backend_kotlin::{
    emit_enum_pub, emit_error_type_pub, emit_function_jvm, emit_jvm_client_class, emit_type_pub, to_pascal_case,
};
use alef_core::backend::GeneratedFile;
use alef_core::config::ResolvedCrateConfig;
use alef_core::ir::ApiSurface;

use crate::naming::{java_package, kotlin_package};

/// Emit `<kotlin_source_dir>/<Module>.kt` and (when the API has methodful
/// types) `<kotlin_source_dir>/DefaultClient.kt`.
///
/// `kotlin_source_dir` is the resolved Kotlin source destination —
/// `<project_root>/src/main/kotlin/<dotted_package_as_path>/` in the Gradle
/// Android source-set layout.
pub fn emit(api: &ApiSurface, config: &ResolvedCrateConfig, kotlin_source_dir: &std::path::Path) -> Vec<GeneratedFile> {
    let package = kotlin_package(config);
    let module_name = to_pascal_case(&config.name);
    let java_pkg = java_package(config);
    let lib_name = config.ffi_lib_name();

    let exclude_functions: std::collections::HashSet<&str> = config
        .kotlin_android
        .as_ref()
        .map(|c| c.exclude_functions.iter().map(String::as_str).collect())
        .unwrap_or_default();
    let exclude_types: std::collections::HashSet<&str> = config
        .kotlin_android
        .as_ref()
        .map(|c| c.exclude_types.iter().map(String::as_str).collect())
        .unwrap_or_default();

    let mut imports: BTreeSet<String> = BTreeSet::new();
    let mut body = String::new();

    for ty in api.types.iter().filter(|t| !exclude_types.contains(t.name.as_str())) {
        emit_type_pub(ty, &mut body, &mut imports);
        body.push('\n');
    }

    for en in api.enums.iter().filter(|e| !exclude_types.contains(e.name.as_str())) {
        emit_enum_pub(en, &mut body);
        body.push('\n');
    }

    for error in &api.errors {
        emit_error_type_pub(error, &mut body, &mut imports);
        body.push('\n');
    }

    let visible_functions: Vec<_> = api
        .functions
        .iter()
        .filter(|f| !exclude_functions.contains(f.name.as_str()))
        .collect();

    // Always emit a {Module} object — even when the API has zero free
    // functions — so the System.loadLibrary call happens on first class load.
    imports.insert(format!("import {java_pkg}.{module_name} as Bridge"));
    if visible_functions.iter().any(|f| f.is_async) {
        imports.insert("import kotlinx.coroutines.Dispatchers".to_string());
        imports.insert("import kotlinx.coroutines.withContext".to_string());
    }
    body.push_str(&format!("object {module_name} {{\n"));
    body.push_str(&format!("    init {{ System.loadLibrary(\"{lib_name}\") }}\n\n"));
    for f in &visible_functions {
        emit_function_jvm(f, &mut body, &mut imports, &java_pkg);
        body.push('\n');
    }
    body.push_str("}\n");

    let mut content = String::new();
    content.push_str("// Generated by alef. Do not edit by hand.\n\n");
    content.push_str(&format!("package {package}\n\n"));
    for import in &imports {
        content.push_str(import);
        content.push('\n');
    }
    if !imports.is_empty() {
        content.push('\n');
    }
    content.push_str(&body);

    let kt_path = kotlin_source_dir.join(format!("{module_name}.kt"));

    let mut files = vec![GeneratedFile {
        path: kt_path,
        content,
        generated_header: false,
    }];

    if let Some(client_file) = emit_jvm_client_class(api, config) {
        let android_client_path = kotlin_source_dir.join("DefaultClient.kt");
        files.push(GeneratedFile {
            path: android_client_path,
            content: client_file.content,
            generated_header: false,
        });
    }

    let _ = PathBuf::new(); // suppress unused import on some toolchains
    files
}
