//! `build.gradle.kts` emitter — full Android library project with
//! maven-publish, ktlint hooks, and bundled-Java-facade source set wiring.

use alef_core::config::ResolvedCrateConfig;
use alef_core::template_versions::{maven, toolchain};

use crate::naming::{aar_artifact_id, aar_group_id, compile_sdk, jvm_target, min_sdk, namespace};

/// Emit `build.gradle.kts` for the generated AAR module.
pub fn emit(config: &ResolvedCrateConfig) -> String {
    let kotlin_version = maven::KOTLIN_JVM_PLUGIN;
    let android_gradle_plugin = maven::ANDROID_GRADLE_PLUGIN;
    let junit_legacy = maven::JUNIT_LEGACY;
    let androidx_junit = maven::ANDROIDX_TEST_EXT_JUNIT;
    let espresso_core = maven::ANDROIDX_TEST_ESPRESSO_CORE;
    let _kotlinx_coroutines = maven::KOTLINX_COROUTINES_CORE;
    let _ = toolchain::ANDROID_JVM_TARGET;

    let android_namespace = namespace(config);
    let compile_sdk_val = compile_sdk(config);
    let min_sdk_val = min_sdk(config);
    let android_jvm_target = jvm_target(config);
    let group_id = aar_group_id(config);
    let artifact_id = aar_artifact_id(config);
    let version_placeholder = "0.0.0";

    format!(
        r#"// Generated by alef. Do not edit by hand.

plugins {{
    id("com.android.library") version "{android_gradle_plugin}"
    kotlin("android") version "{kotlin_version}"
    id("maven-publish")
}}

android {{
    namespace = "{android_namespace}"
    compileSdk = {compile_sdk_val}

    defaultConfig {{
        minSdk = {min_sdk_val}
        consumerProguardFiles("consumer-rules.pro")
    }}

    compileOptions {{
        sourceCompatibility = JavaVersion.VERSION_{android_jvm_target}
        targetCompatibility = JavaVersion.VERSION_{android_jvm_target}
    }}

    kotlinOptions {{
        jvmTarget = "{android_jvm_target}"
    }}

    sourceSets {{
        getByName("main") {{
            java.srcDirs("src/main/java")
            jniLibs.srcDirs("src/main/jniLibs")
        }}
    }}
}}

dependencies {{
    implementation("org.jetbrains.kotlin:kotlin-stdlib")
    testImplementation("junit:junit:{junit_legacy}")
    androidTestImplementation("androidx.test.ext:junit:{androidx_junit}")
    androidTestImplementation("androidx.test.espresso:espresso-core:{espresso_core}")
}}

publishing {{
    publications {{
        register<MavenPublication>("release") {{
            afterEvaluate {{
                from(components["release"])
            }}
            groupId = "{group_id}"
            artifactId = "{artifact_id}"
            version = "{version_placeholder}"
        }}
    }}
}}
"#
    )
}
