//! `.gitignore` for the AAR module — covers Gradle build outputs, IDE
//! caches, and stray Android-specific files.

/// Emit `.gitignore`.
pub fn emit() -> String {
    "# Generated by alef. Do not edit by hand.\nbuild/\n.gradle/\n.idea/\n*.iml\nlocal.properties\n".to_string()
}
