//! Swift trait bridge codegen for outbound plugins.
//!
//! For each configured `TraitBridgeConfig` entry (when `bind_via = "function_param"`),
//! generates:
//!
//! 1. A Swift `protocol Swift<TraitName>Bridge` declaring the trait methods with
//!    async/throws matching the Rust trait method signatures. Excluded/internal types
//!    are marshalled as JSON strings at the boundary.
//! 2. A Swift `struct Swift<TraitName>Adapter` wrapping an instance of the protocol
//!    and exposing methods that handle marshalling (conversion from/to JSON for excluded types,
//!    conversion from/to proper Swift types for visible types).
//! 3. A `register<TraitName>(_ bridge: Swift<TraitName>Bridge)` function that
//!    constructs the adapter and calls into Rust to register it.

use crate::backends::swift::naming::bridge_protocol_name;
use crate::core::config::TraitBridgeConfig;
use crate::core::ir::{TypeDef, TypeRef};
use heck::{ToKebabCase, ToLowerCamelCase, ToSnakeCase};
use std::collections::HashSet;

/// Generate Swift trait bridge protocol and adapter for outbound plugins.
///
/// `exclude_types` is the set of types that are not visible in the generated Swift binding.
/// These types are marshalled as JSON strings at the trait boundary.
///
/// Returns a list of (filename, content) tuples ready for emission.
pub fn gen_trait_bridge_files(
    bridges: &[(String, &TraitBridgeConfig, &TypeDef)],
    exclude_types: &HashSet<String>,
) -> Vec<(String, String)> {
    let mut files = Vec::new();

    for (trait_name, bridge_cfg, trait_def) in bridges {
        // Skip if swift is in exclude_languages
        if bridge_cfg.exclude_languages.iter().any(|lang| lang == "swift") {
            continue;
        }

        // Skip if not function_param binding (only outbound plugins use this codegen)
        if !matches!(bridge_cfg.bind_via, crate::core::config::BridgeBinding::FunctionParam) {
            continue;
        }

        let content = gen_single_trait_bridge_file(trait_name, bridge_cfg, trait_def, exclude_types);
        // Use the canonical protocol name as the filename base so the filename
        // stays in sync with the protocol declaration.
        let protocol = bridge_protocol_name(trait_name);
        let filename = format!("{protocol}.swift");
        files.push((filename, content));
    }

    files
}

/// Generate Swift trait bridge code for a single trait.
///
/// `exclude_types` contains type names that are not visible in the Swift binding surface.
/// These types are marshalled as JSON strings at trait boundaries.
fn gen_single_trait_bridge_file(
    trait_name: &str,
    _bridge_cfg: &TraitBridgeConfig,
    trait_def: &TypeDef,
    exclude_types: &HashSet<String>,
) -> String {
    let mut out = String::new();

    // Header
    out.push_str("// Generated by alef. Do not edit by hand.\n");
    out.push_str("// swift-format-ignore-file\n");
    out.push_str("// This file contains generated FFI glue for trait bridge registration.\n\n");
    out.push_str("import Foundation\n");
    out.push_str("import RustBridge\n\n");

    // MARK: Protocol Declaration
    let protocol = bridge_protocol_name(trait_name);
    out.push_str(&format!(
        "/// Protocol for outbound `{trait_name}` implementations.\n\
         /// Conform your Swift class or struct to this protocol to implement\n\
         /// a Rust trait from the host side.\n\
         public protocol {protocol}: AnyObject {{\n"
    ));

    for method in &trait_def.methods {
        if method.has_default_impl {
            continue;
        }

        let method_camel = method.name.to_lower_camel_case();
        // Protocol method parameters use native types (excluded types as native structs, not marshalled)
        let params_sig = swift_method_params_native(&method.params, exclude_types);
        // Protocol method return types marshal excluded types as JSON strings (like Java does)
        let return_type = swift_return_type(&method.return_type, exclude_types);
        let throws = if method.error_type.is_some() { " throws" } else { "" };
        let async_kw = if method.is_async { " async" } else { "" };

        out.push_str(&format!(
            "    func {method_camel}({params_sig}){async_kw}{throws} -> {return_type}\n"
        ));
    }

    out.push_str("}\n\n");

    // MARK: Adapter Class
    out.push_str(&format!(
        "/// Internal adapter wrapping a `{protocol}` conformer.\n\
         /// Marshals Swift types and trait calls to/from the C boundary.\n\
         /// Excluded/internal types are serialised to/from JSON strings.\n\
         final class Swift{trait_name}Adapter {{\n\
         \x20   private let bridge: any {protocol}\n\n"
    ));

    // Constructor
    out.push_str(&format!(
        "    init(bridge: any {protocol}) {{\n\
         \x20\x20\x20\x20self.bridge = bridge\n\
         \x20   }}\n\n"
    ));

    // Method entry points — these marshal types across the boundary
    for method in &trait_def.methods {
        if method.has_default_impl {
            continue;
        }

        let method_camel = method.name.to_lower_camel_case();
        // Build parameter signature for the adapter method (input from Rust across the boundary)
        let params_sig = swift_method_params(&method.params, exclude_types);
        // Build return type for the adapter method (output back to Rust)
        // If the method has an error type, the adapter returns String (JSON envelope);
        // otherwise, it returns the original type
        let return_type = if method.error_type.is_some() {
            "String".to_string()
        } else {
            swift_return_type(&method.return_type, exclude_types)
        };

        // Build async/throws keywords for the adapter method signature
        let async_kw = if method.is_async { " async" } else { "" };
        let throws_kw = if method.error_type.is_some() { " throws" } else { "" };

        out.push_str(&format!(
            "    func {method_camel}Call({params_sig}){async_kw}{throws_kw} -> {return_type} {{\n"
        ));

        // Generate method body: construct call arguments and handle return value.
        let call_args = build_adapter_call_args(method);
        let call_args_str = call_args.join(", ");

        if method.error_type.is_some() {
            // Error-returning method: wrap result in try-catch and return JSON envelope
            // Swift requires 'try await' order (not 'await try')
            let try_await = if method.is_async { "try await " } else { "try " };
            out.push_str(&format!(
                "        do {{\n\
                 \x20\x20\x20\x20let result = {try_await}self.bridge.{method_camel}({call_args_str})\n"
            ));
            // Special case: if return type is Void, don't try to marshal it
            if matches!(method.return_type, TypeRef::Unit) {
                out.push_str(
                    "            return marshal_ok_result(Empty())\n\
                     \x20\x20\x20\x20} catch {\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20return marshal_error_result(error)\n\
                     \x20\x20\x20\x20}\n",
                );
            } else {
                // For error-returning methods, JSON-encode the result
                match &method.return_type {
                    TypeRef::String => {
                        out.push_str(
                            "            return marshal_ok_result(result)\n\
                             \x20\x20\x20\x20} catch {\n\
                             \x20\x20\x20\x20\x20\x20\x20\x20return marshal_error_result(error)\n\
                             \x20\x20\x20\x20}\n",
                        );
                    }
                    TypeRef::Unit => {
                        out.push_str(
                            "            return marshal_ok_result(Empty())\n\
                             \x20\x20\x20\x20} catch {\n\
                             \x20\x20\x20\x20\x20\x20\x20\x20return marshal_error_result(error)\n\
                             \x20\x20\x20\x20}\n",
                        );
                    }
                    TypeRef::Primitive(_) | TypeRef::Bytes | TypeRef::Char => {
                        out.push_str(
                            "            return marshal_ok_result(result)\n\
                             \x20\x20\x20\x20} catch {\n\
                             \x20\x20\x20\x20\x20\x20\x20\x20return marshal_error_result(error)\n\
                             \x20\x20\x20\x20}\n",
                        );
                    }
                    TypeRef::Named(name) if exclude_types.contains(name) => {
                        // Excluded type: result is the native Swift struct (not Encodable).
                        // Encode directly and wrap in JSON string manually.
                        out.push_str(
                            "            let encodedData = try marshal_encode_excluded(result)\n\
                             \x20\x20\x20\x20if let jsonString = String(data: encodedData, encoding: .utf8) {\n\
                             \x20\x20\x20\x20\x20\x20\x20\x20return \"{\\\"ok\\\": \\(jsonString)}\"\n\
                             \x20\x20\x20\x20}\n\
                             \x20\x20\x20\x20return \"{\\\"ok\\\": null}\"\n\
                             \x20\x20\x20\x20} catch {\n\
                             \x20\x20\x20\x20\x20\x20\x20\x20return marshal_error_result(error)\n\
                             \x20\x20\x20\x20}\n",
                        );
                    }
                    _ => {
                        out.push_str(
                            "            return marshal_ok_result(try JSONEncoder().encode(result))\n\
                             \x20\x20\x20\x20} catch {\n\
                             \x20\x20\x20\x20\x20\x20\x20\x20return marshal_error_result(error)\n\
                             \x20\x20\x20\x20}\n",
                        );
                    }
                }
            }
        } else if method.is_async {
            // Async method without error: return the result directly, no encoding
            out.push_str(&format!(
                "        let result = await self.bridge.{method_camel}({call_args_str})\n"
            ));
            out.push_str("        return result\n");
        } else {
            // Sync method without error: return the result directly, no encoding
            out.push_str(&format!(
                "        let result = self.bridge.{method_camel}({call_args_str})\n"
            ));
            out.push_str("        return result\n");
        }

        out.push_str("    }\n\n");
    }

    out.push_str("}\n\n");

    // MARK: Helper functions for marshalling
    out.push_str("// MARK: - Marshalling helpers\n\n");
    out.push_str(
        "private struct Empty: Codable {}\n\n\
         private func marshal_ok_result<T: Encodable>(_ value: T) -> String {\n\
         \x20\x20\x20\x20let encoder = JSONEncoder()\n\
         \x20\x20\x20\x20if let data = try? encoder.encode(value),\n\
         \x20\x20\x20\x20   let jsonString = String(data: data, encoding: .utf8) {\n\
         \x20\x20\x20\x20\x20\x20\x20\x20return \"{\\\"ok\\\": \\(jsonString)}\"\n\
         \x20\x20\x20\x20}\n\
         \x20\x20\x20\x20return \"{\\\"ok\\\": null}\"\n\
         }\n\n\
         private func marshal_encode_excluded<T: Encodable>(_ value: T) throws -> Data {\n\
         \x20\x20\x20\x20let encoder = JSONEncoder()\n\
         \x20\x20\x20\x20return try encoder.encode(value)\n\
         }\n\n\
         private func marshal_error_result(_ error: any Error) -> String {\n\
         \x20\x20\x20\x20let errorString = String(describing: error)\n\
         \x20\x20\x20\x20let encoder = JSONEncoder()\n\
         \x20\x20\x20\x20if let data = try? encoder.encode(errorString),\n\
         \x20\x20\x20\x20   let jsonString = String(data: data, encoding: .utf8) {\n\
         \x20\x20\x20\x20\x20\x20\x20\x20return \"{\\\"err\\\": \\(jsonString)}\"\n\
         \x20\x20\x20\x20}\n\
         \x20\x20\x20\x20return \"{\\\"err\\\": \\\"unknown error\\\"}\"\n\
         }\n\n",
    );

    // NOTE: Registration functions are NOT emitted here. They live in <Binding>.swift
    // (generated by `emit_trait_bridge_forwarders`) and accept the Box-based type
    // (`Swift{Trait}Box`) from `Sources/RustBridge/Plugins.swift` that the RustBridge
    // `register_*` entry point actually expects. Emitting a duplicate here that passes
    // `Swift{Trait}Adapter` would cause a type mismatch at the `try RustBridge.{camel}(adapter)`
    // call site because Adapter and Box are distinct, incompatible types.

    out
}

/// Emit Swift method parameter signature from MethodDef params.
///
/// Protocol methods use native types (excluded types as native structs, not marshalled).
fn swift_method_params_native(params: &[crate::core::ir::ParamDef], exclude_types: &HashSet<String>) -> String {
    if params.is_empty() {
        return String::new();
    }

    params
        .iter()
        .map(|p| {
            let name = p.name.to_snake_case();
            let ty = swift_type_name_native(&p.ty, exclude_types);
            format!("{}: {}", name, ty)
        })
        .collect::<Vec<_>>()
        .join(", ")
}

/// Emit Swift method parameter signature from MethodDef params.
///
/// Adapter methods marshal excluded types as JSON strings for the C boundary.
fn swift_method_params(params: &[crate::core::ir::ParamDef], exclude_types: &HashSet<String>) -> String {
    if params.is_empty() {
        return String::new();
    }

    params
        .iter()
        .map(|p| {
            let name = p.name.to_snake_case();
            let ty = swift_type_name(&p.ty, exclude_types);
            format!("{}: {}", name, ty)
        })
        .collect::<Vec<_>>()
        .join(", ")
}

/// Get the Swift type name for a TypeRef.
///
/// Protocol methods use native types (excluded types as native structs).
#[allow(clippy::only_used_in_recursion)]
fn swift_type_name_native(ty: &TypeRef, exclude_types: &HashSet<String>) -> String {
    match ty {
        TypeRef::Primitive(p) => match p {
            crate::core::ir::PrimitiveType::Bool => "Bool".to_string(),
            crate::core::ir::PrimitiveType::I8 => "Int8".to_string(),
            crate::core::ir::PrimitiveType::I16 => "Int16".to_string(),
            crate::core::ir::PrimitiveType::I32 => "Int32".to_string(),
            crate::core::ir::PrimitiveType::I64 => "Int64".to_string(),
            crate::core::ir::PrimitiveType::U8 => "UInt8".to_string(),
            crate::core::ir::PrimitiveType::U16 => "UInt16".to_string(),
            crate::core::ir::PrimitiveType::U32 => "UInt32".to_string(),
            crate::core::ir::PrimitiveType::U64 => "UInt64".to_string(),
            crate::core::ir::PrimitiveType::Usize => "Int".to_string(),
            crate::core::ir::PrimitiveType::Isize => "Int".to_string(),
            crate::core::ir::PrimitiveType::F32 => "Float".to_string(),
            crate::core::ir::PrimitiveType::F64 => "Double".to_string(),
        },
        TypeRef::String => "String".to_string(),
        TypeRef::Bytes => "Data".to_string(),
        TypeRef::Path => "URL".to_string(),
        TypeRef::Char => "Character".to_string(),
        TypeRef::Named(name) => {
            // Protocol uses native type name (excluded or not)
            name.clone()
        }
        TypeRef::Vec(inner) => format!("[{}]", swift_type_name_native(inner, exclude_types)),
        TypeRef::Map(k, v) => format!(
            "[{}: {}]",
            swift_type_name_native(k, exclude_types),
            swift_type_name_native(v, exclude_types)
        ),
        TypeRef::Optional(inner) => format!("{}?", swift_type_name_native(inner, exclude_types)),
        TypeRef::Unit => "Void".to_string(),
        TypeRef::Json => "String".to_string(),
        TypeRef::Duration => "TimeInterval".to_string(),
    }
}

/// Get the Swift type name for a TypeRef.
///
/// Adapter methods marshal excluded/internal types (not in the visible binding surface) as JSON strings.
fn swift_type_name(ty: &TypeRef, exclude_types: &HashSet<String>) -> String {
    match ty {
        TypeRef::Primitive(p) => match p {
            crate::core::ir::PrimitiveType::Bool => "Bool".to_string(),
            crate::core::ir::PrimitiveType::I8 => "Int8".to_string(),
            crate::core::ir::PrimitiveType::I16 => "Int16".to_string(),
            crate::core::ir::PrimitiveType::I32 => "Int32".to_string(),
            crate::core::ir::PrimitiveType::I64 => "Int64".to_string(),
            crate::core::ir::PrimitiveType::U8 => "UInt8".to_string(),
            crate::core::ir::PrimitiveType::U16 => "UInt16".to_string(),
            crate::core::ir::PrimitiveType::U32 => "UInt32".to_string(),
            crate::core::ir::PrimitiveType::U64 => "UInt64".to_string(),
            crate::core::ir::PrimitiveType::Usize => "Int".to_string(), // Maps to platform-dependent size
            crate::core::ir::PrimitiveType::Isize => "Int".to_string(), // Maps to platform-dependent size
            crate::core::ir::PrimitiveType::F32 => "Float".to_string(),
            crate::core::ir::PrimitiveType::F64 => "Double".to_string(),
        },
        TypeRef::String => "String".to_string(),
        TypeRef::Bytes => "Data".to_string(),
        TypeRef::Path => "URL".to_string(),
        TypeRef::Char => "Character".to_string(),
        TypeRef::Named(name) => {
            // If the named type is excluded (internal/not visible), marshal as JSON string
            if exclude_types.contains(name) {
                "String".to_string() // JSON-marshalled as String
            } else {
                name.clone()
            }
        }
        TypeRef::Vec(inner) => format!("[{}]", swift_type_name(inner, exclude_types)),
        TypeRef::Map(k, v) => format!(
            "[{}: {}]",
            swift_type_name(k, exclude_types),
            swift_type_name(v, exclude_types)
        ),
        TypeRef::Optional(inner) => format!("{}?", swift_type_name(inner, exclude_types)),
        TypeRef::Unit => "Void".to_string(),
        TypeRef::Json => "String".to_string(), // JSON is marshalled as String
        TypeRef::Duration => "TimeInterval".to_string(), // Duration -> TimeInterval in Swift
    }
}

/// Emit Swift return type from TypeRef for adapter methods (marshalled types).
fn swift_return_type(ty: &TypeRef, exclude_types: &HashSet<String>) -> String {
    swift_type_name(ty, exclude_types)
}

/// Build the call arguments for the adapter method with Swift argument labels.
///
/// Swift requires explicit labels for all method arguments.
fn build_adapter_call_args(method: &crate::core::ir::MethodDef) -> Vec<String> {
    method
        .params
        .iter()
        .map(|p| {
            let name = p.name.to_snake_case();
            format!("{}: {}", name, name)
        })
        .collect()
}

/// Generate the registration overloads file (`BridgeRegistrationOverloads.swift`)
/// that provides convenience register/unregister functions for bridge stubs.
///
/// This file contains:
/// - Unregister `name:` label overloads for all bridge-bound traits
/// - Register overloads that accept bridge protocols and wrap them in adapters
/// - Stub adapter classes that implement full trait protocols with sensible defaults
///
/// Returns `(filename, content)` ready for emission.
pub fn gen_bridge_registration_overloads_file(
    bridges: &[(String, &TraitBridgeConfig, &TypeDef)],
) -> Option<(String, String)> {
    let trait_bridges: Vec<_> = bridges
        .iter()
        .filter(|(_, bridge_cfg, _)| {
            // Only include bridges not excluded from swift
            !bridge_cfg.exclude_languages.iter().any(|lang| lang == "swift")
                && matches!(bridge_cfg.bind_via, crate::core::config::BridgeBinding::FunctionParam)
        })
        .collect();

    if trait_bridges.is_empty() {
        return None;
    }

    let mut content = String::new();

    // Header
    content.push_str("// Generated by alef. Do not edit by hand.\n");
    content.push_str("// swift-format-ignore-file\n");
    content.push_str("// This file contains convenience overloads matching the alef e2e generator's call shapes.\n\n");

    content.push_str("import Foundation\n");
    content.push_str("import RustBridge\n\n");

    // MARK: Path/UTF-8 helper
    content.push_str("// MARK: - Path/UTF-8 helper used by the String overloads of extractBytes(Sync).\n\n");
    content.push_str(
        "/// Treat the input as a filesystem path first (resolved against the test\n\
         /// fixtures directory if relative); fall back to the raw UTF-8 bytes if no\n\
         /// such file exists. The alef e2e generator emits fixture paths into\n\
         /// `extract_bytes` calls, but third-party callers may still want to pass\n\
         /// inline string content.\n",
    );
    content.push_str("public func _loadBytesFromPathOrUtf8(_ pathOrContent: String) throws -> [UInt8] {\n");
    content.push_str("    let fm = FileManager.default\n");
    content.push_str("    var roots: [String] = [\n");
    content.push_str("        fm.currentDirectoryPath,\n");
    content.push_str("    ]\n");
    content.push_str("    if let envRoot = ProcessInfo.processInfo.environment[\"ALEF_TEST_DOCUMENTS_DIR\"] {\n");
    content.push_str("        roots.append(envRoot)\n");
    content.push_str("    }\n");
    content.push_str("    var walker = URL(fileURLWithPath: fm.currentDirectoryPath)\n");
    content.push_str("    for _ in 0..<16 {\n");
    content.push_str("        roots.append(walker.appendingPathComponent(\"test_documents\").path)\n");
    content.push_str("        roots.append(walker.appendingPathComponent(\"fixtures\").path)\n");
    content.push_str("        let parent = walker.deletingLastPathComponent()\n");
    content.push_str("        if parent.path == walker.path { break }\n");
    content.push_str("        walker = parent\n");
    content.push_str("    }\n");
    content.push_str(
        "    let candidates = [pathOrContent] + roots.map { ($0 as NSString).appendingPathComponent(pathOrContent) }\n",
    );
    content.push_str("    for path in candidates {\n");
    content.push_str(
        "        if fm.fileExists(atPath: path), let data = try? Data(contentsOf: URL(fileURLWithPath: path)) {\n",
    );
    content.push_str("            return [UInt8](data)\n");
    content.push_str("        }\n");
    content.push_str("    }\n");
    content.push_str("    return [UInt8](pathOrContent.utf8)\n");
    content.push_str("}\n\n");

    // MARK: Unregister name: label overloads
    content.push_str("// MARK: - Unregister name: label overloads\n\n");
    for (trait_name, _, _) in &trait_bridges {
        let pascal_name = to_pascal_case(trait_name);
        content.push_str(&format!(
            "public func unregister{pascal_name}(name: String) throws {{\n\
             \x20   try unregister{pascal_name}(name)\n\
             }}\n\n"
        ));
    }

    // MARK: Bridge → Box register overloads
    content.push_str("// MARK: - Bridge → Box register overloads\n\n");
    for (trait_name, _, _) in &trait_bridges {
        let pascal_name = to_pascal_case(trait_name);
        content.push_str(&format!(
            "public func register{pascal_name}(_ bridge: Swift{pascal_name}Bridge) throws {{\n\
             \x20   try register{pascal_name}(Swift{pascal_name}Box(_{pascal_name}BridgeAdapter(bridge: bridge)))\n\
             }}\n\n"
        ));
    }

    // MARK: Internal stub adapters
    content.push_str("// MARK: - Internal stub adapters\n");
    content.push_str("//\n");
    content.push_str("// Each adapter conforms to the full plugin protocol expected by the\n");
    content.push_str("// `Swift<Plugin>Box` wrapper and delegates only the methods the bridge\n");
    content.push_str("// exposes. The remaining methods use safe defaults: register/initialize/\n");
    content.push_str("// shutdown are no-ops, processing entrypoints throw, capability queries\n");
    content.push_str("// report false/empty.\n");
    content.push_str("//\n");
    content.push_str("// Adapter stub names (returned by name() method):\n");
    for (trait_name, _, _) in &trait_bridges {
        let pascal_name = to_pascal_case(trait_name);
        let stub_name = derive_short_stub_name(trait_name);
        content.push_str(&format!(
            "// - _{pascal_name}BridgeAdapter → \"swift-bridge-{stub_name}-stub\"\n"
        ));
    }
    content.push_str("//\n");
    content.push_str("// These names are used by e2e test cleanup to unregister stubs after each test.\n\n");

    content.push_str("private struct _BridgeStubError: Error, CustomStringConvertible {\n");
    content.push_str("    let description: String\n");
    content.push_str("}\n\n");

    // Emit adapter classes
    for (trait_name, _, trait_def) in &trait_bridges {
        let pascal_name = to_pascal_case(trait_name);
        let stub_name = derive_short_stub_name(trait_name);

        content.push_str(&format!(
            "private final class _{pascal_name}BridgeAdapter: {pascal_name} {{\n\
             \x20   private let bridge: any Swift{pascal_name}Bridge\n\
             \x20   init(bridge: any Swift{pascal_name}Bridge) {{ self.bridge = bridge }}\n\n"
        ));

        // Emit default implementations of all trait methods
        content.push_str(&format!(
            "    func name() -> String {{ \"swift-bridge-{stub_name}-stub\" }}\n"
        ));

        // Generate default implementations for all methods
        for method in &trait_def.methods {
            if method.has_default_impl {
                continue;
            }

            let method_camel = method.name.to_lower_camel_case();

            // Build parameter list
            let params = method
                .params
                .iter()
                .map(|p| format!("{}_{}: {}", p.name, p.name, "String"))
                .collect::<Vec<_>>()
                .join(", ");

            // For most methods, emit a default no-op or throw error
            // This is a conservative stub that will compile but throw on async methods
            if method.is_async {
                content.push_str(&format!(
                    "    func {method_camel}({params}) throws -> String {{\n\
                     \x20       throw _BridgeStubError(description: \"async bridge {method_camel} cannot be invoked from sync FFI stub\")\n\
                     \x20   }}\n\n"
                ));
            } else {
                // For sync methods, return sensible defaults
                match &method.return_type {
                    TypeRef::Unit => {
                        content.push_str(&format!("    func {method_camel}({params}) {{}}\n\n"));
                    }
                    TypeRef::String => {
                        content.push_str(&format!("    func {method_camel}({params}) -> String {{ \"\" }}\n\n"));
                    }
                    TypeRef::Bytes => {
                        content.push_str(&format!("    func {method_camel}({params}) -> [UInt8] {{ [] }}\n\n"));
                    }
                    TypeRef::Primitive(crate::core::ir::PrimitiveType::Bool) => {
                        content.push_str(&format!("    func {method_camel}({params}) -> Bool {{ false }}\n\n"));
                    }
                    _ => {
                        // For other types, emit a placeholder comment
                        content.push_str(&format!("    // TODO: Implement {method_camel} stub\n\n"));
                    }
                }
            }
        }

        content.push_str("}\n\n");
    }

    Some(("BridgeRegistrationOverloads.swift".to_string(), content))
}

/// Derive the short kebab-cased stub-name suffix used in adapter `name()`.
/// Kebab-case the trait name, then strip a trailing `-backend` so plugin
/// traits like `OcrBackend` map to `ocr` — matching the established e2e
/// fixture cleanup names that consumers rely on.
fn derive_short_stub_name(trait_name: &str) -> String {
    let kebab = trait_name.to_kebab_case();
    kebab.strip_suffix("-backend").map(str::to_string).unwrap_or(kebab)
}

/// Convert a snake_case or kebab-case identifier to PascalCase.
fn to_pascal_case(s: &str) -> String {
    s.split(&['-', '_'][..])
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::config::BridgeBinding;

    fn make_trait_def(name: &str) -> TypeDef {
        TypeDef {
            name: name.to_string(),
            rust_path: format!("testcrate::{}", name),
            original_rust_path: String::new(),
            fields: vec![],
            methods: vec![],
            is_opaque: false,
            is_clone: true,
            is_copy: false,
            is_trait: true,
            has_default: false,
            has_stripped_cfg_fields: false,
            is_return_type: false,
            serde_rename_all: None,
            has_serde: false,
            super_traits: vec![],
            doc: String::new(),
            cfg: None,
            binding_excluded: false,
            binding_exclusion_reason: None,
        }
    }

    fn make_bridge_cfg(trait_name: &str) -> TraitBridgeConfig {
        TraitBridgeConfig {
            trait_name: trait_name.to_string(),
            param_name: None,
            type_alias: None,
            exclude_languages: vec![],
            super_trait: None,
            registry_getter: None,
            register_fn: Some(format!("register{}", trait_name)),
            unregister_fn: None,
            clear_fn: None,
            register_extra_args: None,
            bind_via: BridgeBinding::FunctionParam,
            options_type: None,
            options_field: None,
            context_type: None,
            result_type: None,
            ffi_skip_methods: Vec::new(),
        }
    }

    #[test]
    fn test_trait_bridge_protocol_generated() {
        let trait_def = make_trait_def("OcrBackend");
        let bridge_cfg = make_bridge_cfg("OcrBackend");
        let bridges = vec![("OcrBackend".to_string(), &bridge_cfg, &trait_def)];
        let exclude_types = HashSet::new();
        let files = gen_trait_bridge_files(&bridges, &exclude_types);

        assert_eq!(files.len(), 1);
        assert_eq!(files[0].0, "SwiftOcrBackendBridge.swift");
        assert!(files[0].1.contains("protocol SwiftOcrBackendBridge"));
    }

    #[test]
    fn test_trait_bridge_excludes_swift_language() {
        let trait_def = make_trait_def("OcrBackend");
        let mut bridge_cfg = make_bridge_cfg("OcrBackend");
        bridge_cfg.exclude_languages = vec!["swift".to_string()];
        let bridges = vec![("OcrBackend".to_string(), &bridge_cfg, &trait_def)];
        let exclude_types = HashSet::new();
        let files = gen_trait_bridge_files(&bridges, &exclude_types);

        assert!(files.is_empty());
    }

    #[test]
    fn test_trait_bridge_skips_non_function_param() {
        let trait_def = make_trait_def("OcrBackend");
        let mut bridge_cfg = make_bridge_cfg("OcrBackend");
        bridge_cfg.bind_via = BridgeBinding::OptionsField;
        let bridges = vec![("OcrBackend".to_string(), &bridge_cfg, &trait_def)];
        let exclude_types = HashSet::new();
        let files = gen_trait_bridge_files(&bridges, &exclude_types);

        assert!(files.is_empty());
    }

    #[test]
    fn test_swift_type_mapping() {
        use crate::core::ir::PrimitiveType;
        let exclude_types = HashSet::new();
        assert_eq!(swift_type_name(&TypeRef::String, &exclude_types), "String");
        assert_eq!(swift_type_name(&TypeRef::Bytes, &exclude_types), "Data");
        assert_eq!(swift_type_name(&TypeRef::Unit, &exclude_types), "Void");
        assert_eq!(
            swift_type_name(&TypeRef::Primitive(PrimitiveType::I32), &exclude_types),
            "Int32"
        );
        assert_eq!(swift_type_name(&TypeRef::Duration, &exclude_types), "TimeInterval");
    }

    #[test]
    fn test_swift_marshals_excluded_types_as_json() {
        let mut exclude_types = HashSet::new();
        exclude_types.insert("InternalDocument".to_string());
        assert_eq!(
            swift_type_name(&TypeRef::Named("InternalDocument".to_string()), &exclude_types),
            "String",
            "Excluded types should be marshalled as JSON strings"
        );
        assert_eq!(
            swift_type_name(&TypeRef::Named("ExtractionResult".to_string()), &exclude_types),
            "ExtractionResult",
            "Non-excluded types should keep their original names"
        );
    }

    /// Verify that gen_single_trait_bridge_file does NOT emit a `public func register*`
    /// function. Registration is handled by `emit_trait_bridge_forwarders` in `<Binding>.swift`
    /// which uses the Box-based type (`SwiftDocumentExtractorBox`) that the RustBridge
    /// `register_*` entry point actually expects. A duplicate here would pass the
    /// incompatible `Adapter` type, causing a compile error.
    #[test]
    fn test_no_register_fn_in_trait_bridge_file() {
        let trait_def = make_trait_def("DocumentExtractor");
        let bridge_cfg = make_bridge_cfg("DocumentExtractor");
        let bridges = vec![("DocumentExtractor".to_string(), &bridge_cfg, &trait_def)];
        let exclude_types = HashSet::new();
        let files = gen_trait_bridge_files(&bridges, &exclude_types);

        assert_eq!(files.len(), 1);
        let content = &files[0].1;

        // The protocol and adapter must still be emitted.
        assert!(
            content.contains("protocol SwiftDocumentExtractorBridge"),
            "protocol must be emitted, got:\n{content}"
        );
        assert!(
            content.contains("final class SwiftDocumentExtractorAdapter"),
            "adapter class must be emitted, got:\n{content}"
        );

        // A register function must NOT be emitted — it is emitted by emit_trait_bridge_forwarders
        // in <Binding>.swift and uses SwiftDocumentExtractorBox (not Adapter).
        assert!(
            !content.contains("public func registerDocumentExtractor("),
            "register function must NOT be emitted in the bridge file (would use wrong Adapter type), got:\n{content}"
        );
    }

    /// Verify that when an excluded type (e.g. InternalDocument) appears in a trait method
    /// signature, the protocol accepts the native type but the adapter marshals it as JSON String.
    #[test]
    fn test_excluded_type_in_method_becomes_string() {
        use crate::core::ir::{MethodDef, ParamDef, ReceiverKind};

        let mut trait_def = make_trait_def("DocumentExtractor");
        // Add a method with InternalDocument as return type.
        trait_def.methods.push(MethodDef {
            name: "extract_bytes".to_string(),
            params: vec![ParamDef {
                name: "content".to_string(),
                ty: TypeRef::Bytes,
                optional: false,
                default: None,
                sanitized: false,
                typed_default: None,
                is_ref: false,
                is_mut: false,
                newtype_wrapper: None,
                original_type: None,
                map_is_ahash: false,
                map_key_is_cow: false,
            }],
            return_type: TypeRef::Named("InternalDocument".to_string()),
            is_async: false,
            is_static: false,
            error_type: Some("Error".to_string()),
            doc: String::new(),
            receiver: Some(ReceiverKind::Ref),
            sanitized: false,
            trait_source: None,
            returns_ref: false,
            returns_cow: false,
            return_newtype_wrapper: None,
            has_default_impl: false,
            binding_excluded: false,
            binding_exclusion_reason: None,
        });

        let bridge_cfg = make_bridge_cfg("DocumentExtractor");
        let bridges = vec![("DocumentExtractor".to_string(), &bridge_cfg, &trait_def)];

        // Pass InternalDocument in exclude_types (mimicking what mod.rs does when
        // it augments from IR binding_excluded types).
        let mut exclude_types = HashSet::new();
        exclude_types.insert("InternalDocument".to_string());

        let files = gen_trait_bridge_files(&bridges, &exclude_types);
        assert_eq!(files.len(), 1);
        let content = &files[0].1;

        // Protocol method must return String (JSON) for excluded type InternalDocument
        assert!(
            content.contains("func extractBytes(content: Data) throws -> String"),
            "protocol method must marshal excluded type to String, got:\n{content}"
        );

        // Adapter method must return String (JSON marshalling)
        assert!(
            content.contains("func extractBytesCall(content: Data) throws -> String"),
            "adapter method must marshal to String, got:\n{content}"
        );

        // Marshalling helper must be present
        assert!(
            content.contains("marshal_encode_excluded"),
            "marshal_encode_excluded helper must be present, got:\n{content}"
        );
    }

    #[test]
    fn test_bridge_registration_overloads_file() {
        let trait_def = make_trait_def("MyLib");
        let bridge_cfg = make_bridge_cfg("MyLib");
        let bridges = vec![("MyLib".to_string(), &bridge_cfg, &trait_def)];

        let result = gen_bridge_registration_overloads_file(&bridges);
        assert!(result.is_some(), "should generate file");

        let (filename, content) = result.unwrap();
        assert_eq!(filename, "BridgeRegistrationOverloads.swift");

        // Check for expected sections
        assert!(
            content.contains("// MARK: - Unregister name: label overloads"),
            "missing unregister overload section"
        );
        assert!(
            content.contains("public func unregisterMyLib(name: String) throws"),
            "missing unregister overload"
        );

        // Check for register overload
        assert!(
            content.contains("// MARK: - Bridge → Box register overloads"),
            "missing register overload section"
        );
        assert!(
            content.contains("public func registerMyLib(_ bridge: SwiftMyLibBridge) throws"),
            "missing register overload"
        );

        // Check for adapter class
        assert!(
            content.contains("private final class _MyLibBridgeAdapter: MyLib"),
            "missing adapter class"
        );
        assert!(
            content.contains("func name() -> String { \"swift-bridge-my-lib-stub\" }"),
            "missing adapter name method"
        );

        // Check for error struct
        assert!(
            content.contains("private struct _BridgeStubError"),
            "missing error struct"
        );

        // Check for helper function
        assert!(
            content.contains("public func _loadBytesFromPathOrUtf8"),
            "missing helper function"
        );
    }

    #[test]
    fn test_bridge_registration_overloads_empty_when_no_bridges() {
        let bridges: Vec<(String, &TraitBridgeConfig, &TypeDef)> = vec![];
        let result = gen_bridge_registration_overloads_file(&bridges);
        assert!(result.is_none(), "should not generate file when no bridges");
    }

    #[test]
    fn test_bridge_registration_overloads_skips_excluded_language() {
        let trait_def = make_trait_def("MyLib");
        let mut bridge_cfg = make_bridge_cfg("MyLib");
        bridge_cfg.exclude_languages = vec!["swift".to_string()];
        let bridges = vec![("MyLib".to_string(), &bridge_cfg, &trait_def)];

        let result = gen_bridge_registration_overloads_file(&bridges);
        assert!(result.is_none(), "should skip bridges excluded from swift");
    }

    #[test]
    fn test_pascal_case_conversion() {
        assert_eq!(to_pascal_case("my_lib"), "MyLib");
        assert_eq!(to_pascal_case("ocr_backend"), "OcrBackend");
        assert_eq!(to_pascal_case("test"), "Test");
        assert_eq!(to_pascal_case("a"), "A");
    }
}
