mod errors;
mod functions;
mod render_type;
mod types;

use alef_core::backend::{Backend, BuildConfig, BuildDependency, Capabilities, GeneratedFile, PostBuildStep};
use alef_core::config::{AlefConfig, DartStyle, Language, resolve_output_dir};
use alef_core::ir::{ApiSurface, FunctionDef};
use std::collections::BTreeSet;
use std::path::PathBuf;

use crate::gen_ffi;
use crate::gen_rust_crate;

use errors::emit_error;
use functions::emit_function;
use types::{emit_enum, emit_type};

pub struct DartBackend;

impl Backend for DartBackend {
    fn name(&self) -> &str {
        "dart"
    }

    fn language(&self) -> Language {
        Language::Dart
    }

    fn capabilities(&self) -> Capabilities {
        Capabilities {
            supports_async: true,
            supports_classes: true,
            supports_enums: true,
            supports_option: true,
            supports_result: true,
            supports_callbacks: false,
            supports_streaming: false,
        }
    }

    fn generate_bindings(&self, api: &ApiSurface, config: &AlefConfig) -> anyhow::Result<Vec<GeneratedFile>> {
        if config.dart_style() == DartStyle::Ffi {
            return gen_ffi::emit(api, config);
        }

        let module_name = dart_module_name(&config.crate_config.name);

        let exclude_functions: std::collections::HashSet<&str> = config
            .dart
            .as_ref()
            .map(|c| c.exclude_functions.iter().map(String::as_str).collect())
            .unwrap_or_default();
        let exclude_types: std::collections::HashSet<&str> = config
            .dart
            .as_ref()
            .map(|c| c.exclude_types.iter().map(String::as_str).collect())
            .unwrap_or_default();

        let visible_functions: Vec<&FunctionDef> = api
            .functions
            .iter()
            .filter(|f| !exclude_functions.contains(f.name.as_str()))
            .collect();

        let mut imports: BTreeSet<String> = BTreeSet::new();
        let mut body = String::new();

        for ty in api.types.iter().filter(|t| !exclude_types.contains(t.name.as_str())) {
            emit_type(ty, &mut body, &mut imports);
            body.push('\n');
        }

        for en in api.enums.iter().filter(|e| !exclude_types.contains(e.name.as_str())) {
            emit_enum(en, &mut body);
            body.push('\n');
        }

        for error in &api.errors {
            emit_error(error, &mut body, &mut imports);
            body.push('\n');
        }

        if !visible_functions.is_empty() {
            let has_async = visible_functions.iter().any(|f| f.is_async);
            if has_async {
                imports.insert("import 'dart:async';".to_string());
            }

            imports.insert(format!("import '{module_name}_bridge_generated.dart' as rust_bridge;"));

            let bridge_class = dart_bridge_class_name(&config.crate_config.name);
            body.push_str(&format!("class {bridge_class} {{\n"));
            for f in &visible_functions {
                emit_function(f, &mut body, &mut imports);
                body.push('\n');
            }
            body.push_str("}\n");
        }

        let mut content = String::new();
        content.push_str("// Generated by alef. Do not edit by hand.\n\n");
        for import in &imports {
            content.push_str(import);
            content.push('\n');
        }
        if !imports.is_empty() {
            content.push('\n');
        }
        content.push_str(&body);

        let dir = resolve_output_dir(
            None,
            &config.crate_config.name,
            "packages/dart/lib/src",
        );
        let path = PathBuf::from(dir).join(format!("{module_name}.dart"));

        let mut files = vec![GeneratedFile {
            path,
            content,
            generated_header: false,
        }];

        let rust_crate_files = gen_rust_crate::emit(api, config)?;
        files.extend(rust_crate_files);

        Ok(files)
    }

    fn build_config(&self) -> Option<BuildConfig> {
        Some(BuildConfig {
            tool: "cargo",
            crate_suffix: "-dart",
            build_dep: BuildDependency::None,
            post_build: vec![PostBuildStep::RunCommand {
                cmd: "flutter_rust_bridge_codegen",
                args: vec!["generate"],
            }],
        })
    }
}

impl DartBackend {
    /// Return a `BuildConfig` that reflects the active bridging style from `config`.
    ///
    /// - `DartStyle::Ffi` — no Rust crate; use the shared C FFI library.
    /// - `DartStyle::Frb` — Rust crate + flutter_rust_bridge codegen (default).
    pub fn build_config_for(&self, config: &AlefConfig) -> Option<BuildConfig> {
        match config.dart_style() {
            DartStyle::Ffi => Some(BuildConfig {
                tool: "dart",
                crate_suffix: "",
                build_dep: BuildDependency::Ffi,
                post_build: vec![],
            }),
            DartStyle::Frb => Some(BuildConfig {
                tool: "cargo",
                crate_suffix: "-dart",
                build_dep: BuildDependency::None,
                post_build: vec![PostBuildStep::RunCommand {
                    cmd: "flutter_rust_bridge_codegen",
                    args: vec!["generate"],
                }],
            }),
        }
    }
}

/// Converts a crate name like `"my-lib"` to snake_case `"my_lib"`.
fn dart_module_name(crate_name: &str) -> String {
    crate_name.replace('-', "_")
}

/// Converts a crate name like `"my-lib"` to `"MyLibBridge"` for the bridge class.
fn dart_bridge_class_name(crate_name: &str) -> String {
    let mut out = String::new();
    let mut upper_next = true;
    for ch in crate_name.chars() {
        if ch == '-' || ch == '_' {
            upper_next = true;
        } else if upper_next {
            out.extend(ch.to_uppercase());
            upper_next = false;
        } else {
            out.push(ch);
        }
    }
    out.push_str("Bridge");
    out
}
