mod dart_traits;
mod errors;
mod functions;
mod render_type;
mod types;

use crate::naming::dart_style;
use alef_core::backend::{Backend, BuildConfig, BuildDependency, Capabilities, GeneratedFile, PostBuildStep};
use alef_core::config::{DartStyle, Language, ResolvedCrateConfig, resolve_output_dir};
use alef_core::ir::{ApiSurface, FunctionDef};
use std::collections::BTreeSet;
use std::path::PathBuf;

use crate::gen_ffi;
use crate::gen_rust_crate;

use dart_traits::emit_dart_traits;
use functions::emit_function;

pub struct DartBackend;

impl Backend for DartBackend {
    fn name(&self) -> &str {
        "dart"
    }

    fn language(&self) -> Language {
        Language::Dart
    }

    fn capabilities(&self) -> Capabilities {
        Capabilities {
            supports_async: true,
            supports_classes: true,
            supports_enums: true,
            supports_option: true,
            supports_result: true,
            supports_callbacks: false,
            supports_streaming: false,
        }
    }

    fn generate_bindings(&self, api: &ApiSurface, config: &ResolvedCrateConfig) -> anyhow::Result<Vec<GeneratedFile>> {
        if dart_style(config) == DartStyle::Ffi {
            return gen_ffi::emit(api, config);
        }

        let module_name = dart_module_name(&config.name);

        let exclude_functions: std::collections::HashSet<&str> = config
            .dart
            .as_ref()
            .map(|c| c.exclude_functions.iter().map(String::as_str).collect())
            .unwrap_or_default();
        let _exclude_types: std::collections::HashSet<&str> = config
            .dart
            .as_ref()
            .map(|c| c.exclude_types.iter().map(String::as_str).collect())
            .unwrap_or_default();

        let visible_functions: Vec<&FunctionDef> = api
            .functions
            .iter()
            .filter(|f| !exclude_functions.contains(f.name.as_str()))
            .collect();

        let mut imports: BTreeSet<String> = BTreeSet::new();
        let mut body = String::new();

        // For FRB style: all types come from the FRB-generated lib.dart.
        // We export it so that callers of `kreuzberg.dart` get all types from
        // one import and there are no duplicate-type conflicts.
        //
        // We also import it as `rust_bridge` for calling bridge functions
        // from within the wrapper class. Dart allows both export and import
        // of the same URI — the export makes types visible to callers; the
        // import (with prefix) makes the free functions callable here.
        body.push_str(&format!("export '{module_name}_bridge_generated/lib.dart';\n"));

        if !visible_functions.is_empty() {
            // FRB places its generated Dart code in a subdirectory named
            // `{module_name}_bridge_generated/` and exposes it via `lib.dart`.
            //
            // The prefixed import (`as rust_bridge`) lets us call bridge free-functions
            // without namespace collisions. The unqualified import makes all FRB types
            // (ExtractionConfig, ResultFormat, etc.) available unqualified inside the
            // class body for use in return-type annotations and default-value literals.
            body.push_str(&format!(
                "import '{module_name}_bridge_generated/lib.dart' as rust_bridge;\n"
            ));
            body.push_str(&format!(
                "// ignore: duplicate_import\nimport '{module_name}_bridge_generated/lib.dart';\n"
            ));
            body.push('\n');

            let bridge_class = dart_bridge_class_name(&config.name);
            body.push_str(&crate::template_env::render(
                "dart_bridge_class_open.jinja",
                minijinja::context! {
                    bridge_class => bridge_class.as_str(),
                },
            ));
            for f in &visible_functions {
                emit_function(f, &mut body, &mut imports);
                body.push('\n');
            }
            body.push_str("}\n");
        }

        let mut content = String::new();
        content.push_str("// Generated by alef. Do not edit by hand.\n\n");
        // Write collected imports (e.g. dart:typed_data for Uint8List) before the body.
        for import in &imports {
            content.push_str(import);
            content.push('\n');
        }
        if !imports.is_empty() {
            content.push('\n');
        }
        content.push_str(&body);

        let dir = resolve_output_dir(None, &config.name, "packages/dart/lib/src");
        let path = PathBuf::from(dir).join(format!("{module_name}.dart"));

        // Emit the top-level barrel file `lib/<module>.dart` so that consumers
        // can import `package:<pkg>/<pkg>.dart` (the canonical Dart import path).
        let barrel_dir = resolve_output_dir(None, &config.name, "packages/dart/lib");
        let barrel_path = PathBuf::from(barrel_dir).join(format!("{module_name}.dart"));
        let barrel_content =
            format!("// Generated by alef. Do not edit by hand.\n\nexport 'src/{module_name}.dart';\n");

        let mut files = vec![
            GeneratedFile {
                path,
                content,
                generated_header: false,
            },
            GeneratedFile {
                path: barrel_path,
                content: barrel_content,
                generated_header: false,
            },
        ];

        let rust_crate_files = gen_rust_crate::emit(api, config)?;
        files.extend(rust_crate_files);

        // Emit traits.dart when at least one [[trait_bridges]] entry is configured
        // for the Dart backend (not excluded).
        let dart_backend_name = "dart";
        let trait_names: Vec<&str> = config
            .trait_bridges
            .iter()
            .filter(|b| !b.exclude_languages.iter().any(|l| l == dart_backend_name))
            .map(|b| b.trait_name.as_str())
            .collect();

        if !trait_names.is_empty() {
            let (traits_body, traits_imports) = emit_dart_traits(api, &trait_names);
            if !traits_body.is_empty() {
                let mut traits_content = String::new();
                traits_content.push_str("// Generated by alef. Do not edit by hand.\n\n");
                for import in &traits_imports {
                    traits_content.push_str(import);
                    traits_content.push('\n');
                }
                if !traits_imports.is_empty() {
                    traits_content.push('\n');
                }
                traits_content.push_str(&traits_body);

                let traits_dir = resolve_output_dir(None, &config.name, "packages/dart/lib/src");
                let traits_path = PathBuf::from(traits_dir).join("traits.dart");
                files.push(GeneratedFile {
                    path: traits_path,
                    content: traits_content,
                    generated_header: false,
                });
            }
        }

        Ok(files)
    }

    fn build_config(&self) -> Option<BuildConfig> {
        Some(BuildConfig {
            tool: "cargo",
            crate_suffix: "-dart",
            build_dep: BuildDependency::None,
            post_build: vec![PostBuildStep::RunCommand {
                cmd: "flutter_rust_bridge_codegen",
                args: vec!["generate"],
            }],
        })
    }
}

impl DartBackend {
    /// Return a `BuildConfig` that reflects the active bridging style from `config`.
    ///
    /// - `DartStyle::Ffi` — no Rust crate; use the shared C FFI library.
    /// - `DartStyle::Frb` — Rust crate + flutter_rust_bridge codegen (default).
    pub fn build_config_for(&self, config: &ResolvedCrateConfig) -> Option<BuildConfig> {
        match dart_style(config) {
            DartStyle::Ffi => Some(BuildConfig {
                tool: "dart",
                crate_suffix: "",
                build_dep: BuildDependency::Ffi,
                post_build: vec![],
            }),
            DartStyle::Frb => Some(BuildConfig {
                tool: "cargo",
                crate_suffix: "-dart",
                build_dep: BuildDependency::None,
                post_build: vec![PostBuildStep::RunCommand {
                    cmd: "flutter_rust_bridge_codegen",
                    args: vec!["generate"],
                }],
            }),
        }
    }
}

/// Converts a crate name like `"my-lib"` to snake_case `"my_lib"`.
fn dart_module_name(crate_name: &str) -> String {
    crate_name.replace('-', "_")
}

/// Converts a crate name like `"my-lib"` to `"MyLibBridge"` for the bridge class.
fn dart_bridge_class_name(crate_name: &str) -> String {
    let mut out = String::new();
    let mut upper_next = true;
    for ch in crate_name.chars() {
        if ch == '-' || ch == '_' {
            upper_next = true;
        } else if upper_next {
            out.extend(ch.to_uppercase());
            upper_next = false;
        } else {
            out.push(ch);
        }
    }
    out.push_str("Bridge");
    out
}
