use alef_codegen::keywords::swift_ident;
use alef_codegen::type_mapper::TypeMapper;
use alef_core::backend::{Backend, BuildConfig, BuildDependency, Capabilities, GeneratedFile, PostBuildStep};
use alef_core::config::{AlefConfig, Language, resolve_output_dir};
use alef_core::ir::{ApiSurface, EnumDef, EnumVariant, ErrorDef, FieldDef, FunctionDef, ParamDef, TypeDef, TypeRef};
use heck::ToLowerCamelCase;
use std::collections::BTreeSet;
use std::path::PathBuf;

use crate::gen_rust_crate;
use crate::type_map::SwiftMapper;

pub struct SwiftBackend;

impl Backend for SwiftBackend {
    fn name(&self) -> &str {
        "swift"
    }

    fn language(&self) -> Language {
        Language::Swift
    }

    fn capabilities(&self) -> Capabilities {
        Capabilities {
            supports_async: true,
            supports_classes: true,
            supports_enums: true,
            supports_option: true,
            supports_result: true,
            supports_callbacks: false,
            supports_streaming: false,
        }
    }

    fn generate_bindings(&self, api: &ApiSurface, config: &AlefConfig) -> anyhow::Result<Vec<GeneratedFile>> {
        let module_name = config.swift_module();
        let mapper = SwiftMapper;

        let exclude_functions: std::collections::HashSet<&str> = config
            .swift
            .as_ref()
            .map(|c| c.exclude_functions.iter().map(String::as_str).collect())
            .unwrap_or_default();
        let exclude_types: std::collections::HashSet<&str> = config
            .swift
            .as_ref()
            .map(|c| c.exclude_types.iter().map(String::as_str).collect())
            .unwrap_or_default();

        let visible_functions: Vec<&FunctionDef> = api
            .functions
            .iter()
            .filter(|f| !exclude_functions.contains(f.name.as_str()))
            .collect();

        let mut imports: BTreeSet<String> = BTreeSet::new();
        // Foundation is always included — Codable, Data, URL all live there.
        imports.insert("import Foundation".to_string());
        // RustBridge is the Swift module generated by swift-bridge from the Rust bridge crate.
        // It provides the FFI entry points that the wrapper delegates to.
        if !visible_functions.is_empty() {
            imports.insert("import RustBridge".to_string());
        }

        let mut body = String::new();

        for ty in api.types.iter().filter(|t| !exclude_types.contains(t.name.as_str())) {
            emit_struct(ty, &mut body, &mapper);
            body.push('\n');
        }

        for en in api.enums.iter().filter(|e| !exclude_types.contains(e.name.as_str())) {
            emit_enum(en, &mut body, &mapper);
            body.push('\n');
        }

        for error in &api.errors {
            emit_error(error, &mut body, &mapper);
            body.push('\n');
        }

        if !visible_functions.is_empty() {
            body.push_str(&format!("public enum {module_name} {{\n"));
            for f in &visible_functions {
                emit_function(f, &mut body, &mapper);
                body.push('\n');
            }
            body.push_str("}\n");
        }

        let mut content = String::new();
        content.push_str("// Generated by alef. Do not edit by hand.\n\n");
        for import in &imports {
            content.push_str(import);
            content.push('\n');
        }
        content.push('\n');
        content.push_str(&body);

        let dir = resolve_output_dir(
            config.output.swift.as_ref(),
            &config.crate_config.name,
            &format!("Sources/{module_name}"),
        );
        let path = PathBuf::from(dir).join(format!("{module_name}.swift"));

        let mut files = vec![GeneratedFile {
            path,
            content,
            generated_header: false,
        }];

        // Phase 2C: emit the Rust-side swift-bridge crate
        let rust_crate_files = gen_rust_crate::emit(api, config)?;
        files.extend(rust_crate_files);

        Ok(files)
    }

    fn build_config(&self) -> Option<BuildConfig> {
        Some(BuildConfig {
            tool: "swift",
            crate_suffix: "-swift",
            build_dep: BuildDependency::None,
            // Build the Rust bridge crate first so swift-bridge codegen produces
            // the Swift glue files that the Swift Package consumes.
            post_build: vec![PostBuildStep::RunCommand {
                cmd: "cargo",
                args: vec!["build", "--release"],
            }],
        })
    }
}

/// Emits a Swift `public struct` for the given `TypeDef`.
fn emit_struct(ty: &TypeDef, out: &mut String, mapper: &SwiftMapper) {
    emit_doc_comment(&ty.doc, "", out);

    let codable = if ty.has_serde { ": Codable" } else { "" };

    if ty.fields.is_empty() {
        out.push_str(&format!("public struct {}{} {{}}\n", ty.name, codable));
        return;
    }

    out.push_str(&format!("public struct {}{} {{\n", ty.name, codable));

    // Stored properties
    for field in &ty.fields {
        emit_field_doc_comment(&field.doc, out);
        let ty_str = resolve_field_type(field, mapper);
        let name = swift_ident(&field.name.to_lower_camel_case());
        out.push_str(&format!("    public let {name}: {ty_str}\n"));
    }

    // Memberwise initialiser (Swift structs do not expose their synthesised init as `public`)
    out.push('\n');
    let init_params: Vec<String> = ty
        .fields
        .iter()
        .map(|f| {
            let ty_str = resolve_field_type(f, mapper);
            let name = swift_ident(&f.name.to_lower_camel_case());
            format!("{name}: {ty_str}")
        })
        .collect();
    out.push_str(&format!("    public init({}) {{\n", init_params.join(", ")));
    for field in &ty.fields {
        let name = swift_ident(&field.name.to_lower_camel_case());
        out.push_str(&format!("        self.{name} = {name}\n"));
    }
    out.push_str("    }\n");
    out.push_str("}\n");
}

/// Resolves a `FieldDef`'s full Swift type string (handles optionality).
fn resolve_field_type(field: &FieldDef, mapper: &SwiftMapper) -> String {
    let base = mapper.map_type(&field.ty);
    if field.optional {
        format!("{base}?")
    } else {
        base
    }
}

/// Emits a Swift `public enum` for the given `EnumDef`.
fn emit_enum(en: &EnumDef, out: &mut String, mapper: &SwiftMapper) {
    emit_doc_comment(&en.doc, "", out);

    let all_unit = en.variants.iter().all(|v| v.fields.is_empty());

    if all_unit {
        out.push_str(&format!("public enum {} {{\n", en.name));
        for variant in &en.variants {
            emit_doc_comment(&variant.doc, "    ", out);
            let case_name = swift_ident(&variant.name.to_lower_camel_case());
            out.push_str(&format!("    case {case_name}\n"));
        }
        out.push_str("}\n");
    } else {
        out.push_str(&format!("public enum {} {{\n", en.name));
        for variant in &en.variants {
            emit_variant_with_data(variant, out, mapper);
        }
        out.push_str("}\n");
    }
}

/// Emits a single enum case, with or without associated values.
fn emit_variant_with_data(variant: &EnumVariant, out: &mut String, mapper: &SwiftMapper) {
    emit_doc_comment(&variant.doc, "    ", out);
    let case_name = swift_ident(&variant.name.to_lower_camel_case());
    if variant.fields.is_empty() {
        out.push_str(&format!("    case {case_name}\n"));
    } else {
        let assoc: Vec<String> = variant
            .fields
            .iter()
            .enumerate()
            .map(|(idx, f)| {
                let ty_str = mapper.map_type(&f.ty);
                let label = swift_associated_label(&f.name, idx);
                format!("{label}: {ty_str}")
            })
            .collect();
        out.push_str(&format!("    case {case_name}({})\n", assoc.join(", ")));
    }
}

/// Resolves a Swift associated-value label for an enum case field.
///
/// - Empty, all-digit, or `_<digits>` names (positional tuple variants) become
///   `field0`, `field1`, …
/// - Otherwise lowerCamelCase + Swift keyword escaping.
fn swift_associated_label(name: &str, idx: usize) -> String {
    let stripped = name.trim_start_matches('_');
    if stripped.is_empty() || stripped.chars().all(|c| c.is_ascii_digit()) {
        return format!("field{idx}");
    }
    swift_ident(&name.to_lower_camel_case())
}

/// Emits a Swift `Error`-conforming `public enum` for the given `ErrorDef`.
fn emit_error(error: &ErrorDef, out: &mut String, mapper: &SwiftMapper) {
    emit_doc_comment(&error.doc, "", out);
    out.push_str(&format!("public enum {}: Error {{\n", error.name));
    for variant in &error.variants {
        emit_doc_comment(&variant.doc, "    ", out);
        let case_name = swift_ident(&variant.name.to_lower_camel_case());
        if variant.is_unit || variant.fields.is_empty() {
            out.push_str(&format!("    case {case_name}(message: String)\n"));
        } else {
            let mut assoc: Vec<String> = Vec::with_capacity(variant.fields.len() + 1);
            let mut seen_message = false;
            let mut labels: BTreeSet<String> = BTreeSet::new();
            for (idx, f) in variant.fields.iter().enumerate() {
                let ty_str = mapper.map_type(&f.ty);
                let mut label = swift_associated_label(&f.name, idx);
                // Disambiguate duplicate labels by suffixing the index.
                while labels.contains(&label) {
                    label = format!("{label}{idx}");
                }
                labels.insert(label.clone());
                if label == "message" {
                    seen_message = true;
                }
                assoc.push(format!("{label}: {ty_str}"));
            }
            if !seen_message {
                assoc.insert(0, "message: String".to_string());
            }
            out.push_str(&format!("    case {case_name}({})\n", assoc.join(", ")));
        }
    }
    out.push_str("}\n");
}

/// Emits a single `public static func` inside the module enum namespace.
fn emit_function(f: &FunctionDef, out: &mut String, mapper: &SwiftMapper) {
    emit_doc_comment(&f.doc, "    ", out);

    let params: Vec<String> = f.params.iter().map(|p| format_param(p, mapper)).collect();
    let return_ty = mapper.map_type(&f.return_type);

    let func_name = swift_ident(&f.name.to_lower_camel_case());

    // Build the qualifier string: [async] [throws] [-> ReturnType]
    let mut qualifiers = String::new();
    if f.is_async {
        qualifiers.push_str("async ");
    }
    if f.error_type.is_some() {
        qualifiers.push_str("throws ");
    }
    // Omit `-> Void` per Swift convention.
    if !matches!(f.return_type, TypeRef::Unit) {
        qualifiers.push_str(&format!("-> {return_ty} "));
    }

    out.push_str(&format!(
        "    public static func {func_name}({}) {qualifiers}{{\n",
        params.join(", "),
    ));

    // Build the call expression: forward each parameter by name.
    let bridge_func = format!("RustBridge.{func_name}");
    let call_args: Vec<String> = f
        .params
        .iter()
        .map(|p| swift_ident(&p.name.to_lower_camel_case()))
        .collect();
    let call_expr = format!("{bridge_func}({})", call_args.join(", "));

    // Prefix the call with await/try as required.
    let awaited = if f.is_async {
        format!("await {call_expr}")
    } else {
        call_expr
    };
    let invocation = if f.error_type.is_some() {
        format!("try {awaited}")
    } else {
        awaited
    };

    if matches!(f.return_type, TypeRef::Unit) {
        out.push_str(&format!("        {invocation}\n"));
    } else {
        out.push_str(&format!("        return {invocation}\n"));
    }
    out.push_str("    }\n");
}

/// Formats a single parameter as `label: Type`.
fn format_param(p: &ParamDef, mapper: &SwiftMapper) -> String {
    let ty_str = mapper.map_type(&p.ty);
    let name = swift_ident(&p.name.to_lower_camel_case());
    format!("{name}: {ty_str}")
}

/// Emits `/// <line>` doc-comment lines with the given indent prefix.
fn emit_doc_comment(doc: &str, indent: &str, out: &mut String) {
    if doc.is_empty() {
        return;
    }
    for line in doc.lines() {
        out.push_str(indent);
        out.push_str("/// ");
        out.push_str(line);
        out.push('\n');
    }
}

/// Emits field-level doc comments.
fn emit_field_doc_comment(doc: &str, out: &mut String) {
    emit_doc_comment(doc, "    ", out);
}
