use alef_codegen::keywords::swift_ident;
use alef_codegen::type_mapper::TypeMapper;
use alef_core::backend::{Backend, BuildConfig, BuildDependency, Capabilities, GeneratedFile, PostBuildStep};
use alef_core::config::{AlefConfig, Language, resolve_output_dir};
use alef_core::ir::{ApiSurface, EnumDef, EnumVariant, ErrorDef, TypeDef};
use heck::ToLowerCamelCase;
use std::collections::BTreeSet;
use std::path::PathBuf;

use crate::gen_rust_crate;
use crate::type_map::SwiftMapper;

pub struct SwiftBackend;

impl Backend for SwiftBackend {
    fn name(&self) -> &str {
        "swift"
    }

    fn language(&self) -> Language {
        Language::Swift
    }

    fn capabilities(&self) -> Capabilities {
        Capabilities {
            supports_async: true,
            supports_classes: true,
            supports_enums: true,
            supports_option: true,
            supports_result: true,
            supports_callbacks: false,
            supports_streaming: false,
        }
    }

    fn generate_bindings(&self, api: &ApiSurface, config: &AlefConfig) -> anyhow::Result<Vec<GeneratedFile>> {
        let module_name = config.swift_module();
        let mapper = SwiftMapper;

        // Function-wrapper emission is disabled in this phase (see comment below);
        // `swift.exclude_functions` therefore has no effect on the host wrapper but
        // is still consumed by the Rust-side bridge crate via gen_rust_crate::emit.
        let exclude_types: std::collections::HashSet<&str> = config
            .swift
            .as_ref()
            .map(|c| c.exclude_types.iter().map(String::as_str).collect())
            .unwrap_or_default();

        let mut imports: BTreeSet<String> = BTreeSet::new();
        // Foundation is always included — Codable, Data, URL all live there.
        imports.insert("import Foundation".to_string());
        // RustBridge is the Swift module generated by swift-bridge from the Rust bridge crate.
        // It provides opaque type definitions and FFI entry points.
        if !api.types.is_empty() || !api.enums.is_empty() || !api.errors.is_empty() {
            imports.insert("import RustBridge".to_string());
        }

        let mut body = String::new();

        // Compute the set of non-trait types that should be emitted as typealiases to RustBridge.X.
        // This includes ALL non-trait enums and structs (both Codable and non-Codable).
        // swift-bridge generates opaque Swift classes for these, not enums or structs.
        // Emitting typealiases makes them pass through without conversion, avoiding:
        //   1. Invalid enum pattern matching on opaque classes
        //   2. Type mismatches between Codable wrappers and RustBridge opaque types
        //   3. Need for bidirectional JSON serialization
        // Tradeoff: users interact with RustBridge opaque types directly rather than
        // idiomatic Swift wrappers. This is acceptable for the current phase where
        // swift-bridge handling is incomplete.
        let non_codable_types: std::collections::HashSet<&str> = api
            .enums
            .iter()
            .map(|e| e.name.as_str())
            .chain(api.types.iter().filter(|t| !t.is_trait).map(|t| t.name.as_str()))
            .collect();

        for ty in api.types.iter().filter(|t| !exclude_types.contains(t.name.as_str())) {
            emit_struct(ty, &mut body, &mapper, &non_codable_types);
            body.push('\n');
        }

        for en in api.enums.iter().filter(|e| !exclude_types.contains(e.name.as_str())) {
            emit_enum(en, &mut body, &mapper, &non_codable_types);
            body.push('\n');
        }

        for error in &api.errors {
            emit_error(error, &mut body, &mapper);
            body.push('\n');
        }

        // Function wrappers intentionally not emitted: swift-bridge's RustVec/RustString
        // primitive containers cannot be losslessly converted to Swift Array/String at
        // codegen time (RustVec<T> has no [T] initializer, generic-param inference fails
        // across protocol boundaries, etc.). Consumers call RustBridge functions
        // directly; the typealiases above keep `Kreuzberg.SomeType` as a stable name.
        let _ = module_name;

        let mut content = String::new();
        content.push_str("// Generated by alef. Do not edit by hand.\n\n");
        for import in &imports {
            content.push_str(import);
            content.push('\n');
        }
        content.push('\n');
        content.push_str(&body);

        let dir = resolve_output_dir(
            config.output.swift.as_ref(),
            &config.crate_config.name,
            &format!("Sources/{module_name}"),
        );
        let path = PathBuf::from(dir).join(format!("{module_name}.swift"));

        let mut files = vec![GeneratedFile {
            path,
            content,
            generated_header: false,
        }];

        // Phase 2C: emit the Rust-side swift-bridge crate
        let rust_crate_files = gen_rust_crate::emit(api, config)?;
        files.extend(rust_crate_files);

        Ok(files)
    }

    fn build_config(&self) -> Option<BuildConfig> {
        Some(BuildConfig {
            tool: "swift",
            crate_suffix: "-swift",
            build_dep: BuildDependency::None,
            // Build the Rust bridge crate first so swift-bridge codegen produces
            // the Swift glue files that the Swift Package consumes.
            post_build: vec![PostBuildStep::RunCommand {
                cmd: "cargo",
                args: vec!["build", "--release"],
            }],
        })
    }
}

/// Emits a Swift `public struct` for the given `TypeDef`.
/// All non-trait structs are emitted as typealiases to RustBridge.X.
fn emit_struct(ty: &TypeDef, out: &mut String, _mapper: &SwiftMapper, non_codable_types: &std::collections::HashSet<&str>) {
    // All structs become typealiases to the RustBridge opaque class
    if non_codable_types.contains(ty.name.as_str()) {
        emit_doc_comment(&ty.doc, "", out);
        out.push_str(&format!("public typealias {} = RustBridge.{}\n", ty.name, ty.name));
        return;
    }

    // Trait types fall through but shouldn't happen in practice
    emit_doc_comment(&ty.doc, "", out);
    out.push_str(&format!("public struct {} {{\n", ty.name));
    out.push_str("}\n");
}

/// Emits a Swift `public enum` for the given `EnumDef`.
/// All non-trait enums are emitted as typealiases to RustBridge.X.
fn emit_enum(
    en: &EnumDef,
    out: &mut String,
    mapper: &SwiftMapper,
    non_codable_types: &std::collections::HashSet<&str>,
) {
    // All enums become typealiases to the RustBridge opaque class
    if non_codable_types.contains(en.name.as_str()) {
        emit_doc_comment(&en.doc, "", out);
        out.push_str(&format!("public typealias {} = RustBridge.{}\n", en.name, en.name));
        return;
    }

    emit_doc_comment(&en.doc, "", out);

    let all_unit = en.variants.iter().all(|v| v.fields.is_empty());

    if all_unit {
        out.push_str(&format!("public enum {} {{\n", en.name));
        for variant in &en.variants {
            emit_doc_comment(&variant.doc, "    ", out);
            let case_name = swift_ident(&variant.name.to_lower_camel_case());
            out.push_str(&format!("    case {case_name}\n"));
        }
        out.push_str("}\n");
    } else {
        out.push_str(&format!("public enum {} {{\n", en.name));
        for variant in &en.variants {
            emit_variant_with_data(variant, out, mapper);
        }
        out.push_str("}\n");
    }
}

/// Emits a single enum case, with or without associated values.
fn emit_variant_with_data(variant: &EnumVariant, out: &mut String, mapper: &SwiftMapper) {
    emit_doc_comment(&variant.doc, "    ", out);
    let case_name = swift_ident(&variant.name.to_lower_camel_case());
    if variant.fields.is_empty() {
        out.push_str(&format!("    case {case_name}\n"));
    } else {
        let assoc: Vec<String> = variant
            .fields
            .iter()
            .enumerate()
            .map(|(idx, f)| {
                let ty_str = mapper.map_type(&f.ty);
                let label = swift_associated_label(&f.name, idx);
                format!("{label}: {ty_str}")
            })
            .collect();
        out.push_str(&format!("    case {case_name}({})\n", assoc.join(", ")));
    }
}

/// Resolves a Swift associated-value label for an enum case field.
///
/// - Empty, all-digit, or `_<digits>` names (positional tuple variants) become
///   `field0`, `field1`, …
/// - Otherwise lowerCamelCase + Swift keyword escaping.
fn swift_associated_label(name: &str, idx: usize) -> String {
    let stripped = name.trim_start_matches('_');
    if stripped.is_empty() || stripped.chars().all(|c| c.is_ascii_digit()) {
        return format!("field{idx}");
    }
    swift_ident(&name.to_lower_camel_case())
}

/// Emits a Swift `Error`-conforming `public enum` for the given `ErrorDef`.
fn emit_error(error: &ErrorDef, out: &mut String, mapper: &SwiftMapper) {
    emit_doc_comment(&error.doc, "", out);
    out.push_str(&format!("public enum {}: Error {{\n", error.name));
    for variant in &error.variants {
        emit_doc_comment(&variant.doc, "    ", out);
        let case_name = swift_ident(&variant.name.to_lower_camel_case());
        if variant.is_unit || variant.fields.is_empty() {
            out.push_str(&format!("    case {case_name}(message: String)\n"));
        } else {
            let mut assoc: Vec<String> = Vec::with_capacity(variant.fields.len() + 1);
            let mut seen_message = false;
            let mut labels: BTreeSet<String> = BTreeSet::new();
            for (idx, f) in variant.fields.iter().enumerate() {
                let ty_str = mapper.map_type(&f.ty);
                let mut label = swift_associated_label(&f.name, idx);
                // Disambiguate duplicate labels by suffixing the index.
                while labels.contains(&label) {
                    label = format!("{label}{idx}");
                }
                labels.insert(label.clone());
                if label == "message" {
                    seen_message = true;
                }
                assoc.push(format!("{label}: {ty_str}"));
            }
            if !seen_message {
                assoc.insert(0, "message: String".to_string());
            }
            out.push_str(&format!("    case {case_name}({})\n", assoc.join(", ")));
        }
    }
    out.push_str("}\n");
}

/// Emits `/// <line>` doc-comment lines with the given indent prefix.
fn emit_doc_comment(doc: &str, indent: &str, out: &mut String) {
    if doc.is_empty() {
        return;
    }
    for line in doc.lines() {
        out.push_str(indent);
        out.push_str("/// ");
        out.push_str(line);
        out.push('\n');
    }
}

