pub(super) static TEMPLATES: &[(&str, &str)] = &[
    (
        "extern_type_decl.jinja",
        include_str!("../templates/extern_type_decl.jinja"),
    ),
    (
        "extern_init_attr.jinja",
        include_str!("../templates/extern_init_attr.jinja"),
    ),
    ("extern_fn_new.jinja", include_str!("../templates/extern_fn_new.jinja")),
    (
        "extern_fn_getter.jinja",
        include_str!("../templates/extern_fn_getter.jinja"),
    ),
    (
        "extern_fn_noop.jinja",
        include_str!("../templates/extern_fn_noop.jinja"),
    ),
    (
        "extern_enum_type.jinja",
        include_str!("../templates/extern_enum_type.jinja"),
    ),
    (
        "extern_functions_header.jinja",
        include_str!("../templates/extern_functions_header.jinja"),
    ),
    (
        "extern_swift_name_attr.jinja",
        include_str!("../templates/extern_swift_name_attr.jinja"),
    ),
    (
        "extern_fn_decl.jinja",
        include_str!("../templates/extern_fn_decl.jinja"),
    ),
    (
        "trait_extern_type.jinja",
        include_str!("../templates/trait_extern_type.jinja"),
    ),
    (
        "trait_phantom_fn.jinja",
        include_str!("../templates/trait_phantom_fn.jinja"),
    ),
    (
        "trait_method_fn.jinja",
        include_str!("../templates/trait_method_fn.jinja"),
    ),
    ("trait_struct.jinja", include_str!("../templates/trait_struct.jinja")),
    (
        "trait_phantom_impl.jinja",
        include_str!("../templates/trait_phantom_impl.jinja"),
    ),
    (
        "trait_method_impl.jinja",
        include_str!("../templates/trait_method_impl.jinja"),
    ),
    (
        "trait_clear_forwarder.rs.jinja",
        include_str!("../templates/trait_clear_forwarder.rs.jinja"),
    ),
    (
        "rust_from_json_extern_decl.rs.jinja",
        include_str!("../templates/rust_from_json_extern_decl.rs.jinja"),
    ),
    (
        "rust_from_json_shim.rs.jinja",
        include_str!("../templates/rust_from_json_shim.rs.jinja"),
    ),
    (
        "rust_service_app_wrapper.rs.jinja",
        include_str!("../templates/rust_service_app_wrapper.rs.jinja"),
    ),
    (
        "rust_service_app_free_fns.rs.jinja",
        include_str!("../templates/rust_service_app_free_fns.rs.jinja"),
    ),
    (
        "rust_wrapper_constructor_fn.rs.jinja",
        include_str!("../templates/rust_wrapper_constructor_fn.rs.jinja"),
    ),
    (
        "rust_newtype_from_impl.rs.jinja",
        include_str!("../templates/rust_newtype_from_impl.rs.jinja"),
    ),
    (
        "rust_bidirectional_newtype_from_impls.rs.jinja",
        include_str!("../templates/rust_bidirectional_newtype_from_impls.rs.jinja"),
    ),
    (
        "inbound_registration_fn.rs.jinja",
        include_str!("../templates/inbound_registration_fn.rs.jinja"),
    ),
    (
        "inbound_swift_type.rs.jinja",
        include_str!("../templates/inbound_swift_type.rs.jinja"),
    ),
    (
        "inbound_swift_method.rs.jinja",
        include_str!("../templates/inbound_swift_method.rs.jinja"),
    ),
    (
        "inbound_wrapper_struct.rs.jinja",
        include_str!("../templates/inbound_wrapper_struct.rs.jinja"),
    ),
    (
        "inbound_plain_wrapper_struct.rs.jinja",
        include_str!("../templates/inbound_plain_wrapper_struct.rs.jinja"),
    ),
    (
        "inbound_plain_wrapper_debug.rs.jinja",
        include_str!("../templates/inbound_plain_wrapper_debug.rs.jinja"),
    ),
    (
        "inbound_plugin_impl.rs.jinja",
        include_str!("../templates/inbound_plugin_impl.rs.jinja"),
    ),
    (
        "inbound_plugin_path_compile_error.rs.jinja",
        include_str!("../templates/inbound_plugin_path_compile_error.rs.jinja"),
    ),
    (
        "inbound_trait_impl_open.rs.jinja",
        include_str!("../templates/inbound_trait_impl_open.rs.jinja"),
    ),
    (
        "inbound_register_fn.rs.jinja",
        include_str!("../templates/inbound_register_fn.rs.jinja"),
    ),
    (
        "plugin_error_helper.rs.jinja",
        include_str!("../templates/plugin_error_helper.rs.jinja"),
    ),
    (
        "inbound_method_open.rs.jinja",
        include_str!("../templates/inbound_method_open.rs.jinja"),
    ),
    (
        "inbound_method_binding.rs.jinja",
        include_str!("../templates/inbound_method_binding.rs.jinja"),
    ),
    (
        "inbound_method_result_unit.rs.jinja",
        include_str!("../templates/inbound_method_result_unit.rs.jinja"),
    ),
    (
        "inbound_method_result_value.rs.jinja",
        include_str!("../templates/inbound_method_result_value.rs.jinja"),
    ),
    (
        "inbound_method_mime_types.rs.jinja",
        include_str!("../templates/inbound_method_mime_types.rs.jinja"),
    ),
    (
        "inbound_method_json_return.rs.jinja",
        include_str!("../templates/inbound_method_json_return.rs.jinja"),
    ),
    (
        "inbound_method_json_vec_return.rs.jinja",
        include_str!("../templates/inbound_method_json_vec_return.rs.jinja"),
    ),
    (
        "inbound_method_json_optional_vec_return.rs.jinja",
        include_str!("../templates/inbound_method_json_optional_vec_return.rs.jinja"),
    ),
    (
        "inbound_method_unit_call.rs.jinja",
        include_str!("../templates/inbound_method_unit_call.rs.jinja"),
    ),
    (
        "inbound_method_value_call.rs.jinja",
        include_str!("../templates/inbound_method_value_call.rs.jinja"),
    ),
    (
        "rust_extern_opaque_type.rs.jinja",
        include_str!("../templates/rust_extern_opaque_type.rs.jinja"),
    ),
    (
        "rust_extern_init.rs.jinja",
        include_str!("../templates/rust_extern_init.rs.jinja"),
    ),
    (
        "rust_extern_configurator.rs.jinja",
        include_str!("../templates/rust_extern_configurator.rs.jinja"),
    ),
    (
        "rust_extern_c_register_via_callback.rs.jinja",
        include_str!("../templates/rust_extern_c_register_via_callback.rs.jinja"),
    ),
    (
        "rust_extern_entrypoint.rs.jinja",
        include_str!("../templates/rust_extern_entrypoint.rs.jinja"),
    ),
    (
        "rust_extern_service_consolidated.rs.jinja",
        include_str!("../templates/rust_extern_service_consolidated.rs.jinja"),
    ),
    (
        "rust_extern_service_type_and_constructor.rs.jinja",
        include_str!("../templates/rust_extern_service_type_and_constructor.rs.jinja"),
    ),
    (
        "rust_extern_service_methods.rs.jinja",
        include_str!("../templates/rust_extern_service_methods.rs.jinja"),
    ),
    (
        "rust_wrapper_free_fn.rs.jinja",
        include_str!("../templates/rust_wrapper_free_fn.rs.jinja"),
    ),
    (
        "rust_wrapper_raw_ptr_fn.rs.jinja",
        include_str!("../templates/rust_wrapper_raw_ptr_fn.rs.jinja"),
    ),
    (
        "rust_enum_to_string_impl.rs.jinja",
        include_str!("../templates/rust_enum_to_string_impl.rs.jinja"),
    ),
    (
        "rust_enum_to_string_variant.rs.jinja",
        include_str!("../templates/rust_enum_to_string_variant.rs.jinja"),
    ),
    (
        "rust_enum_from_string_impl.rs.jinja",
        include_str!("../templates/rust_enum_from_string_impl.rs.jinja"),
    ),
    (
        "rust_enum_from_string_variant.rs.jinja",
        include_str!("../templates/rust_enum_from_string_variant.rs.jinja"),
    ),
    (
        "rust_phantom_vec_decl.rs.jinja",
        include_str!("../templates/rust_phantom_vec_decl.rs.jinja"),
    ),
    (
        "rust_phantom_vec_impl.rs.jinja",
        include_str!("../templates/rust_phantom_vec_impl.rs.jinja"),
    ),
    (
        "rust_trait_use.rs.jinja",
        include_str!("../templates/rust_trait_use.rs.jinja"),
    ),
    (
        "rust_stream_handle_struct.rs.jinja",
        include_str!("../templates/rust_stream_handle_struct.rs.jinja"),
    ),
    (
        "rust_stream_handle_start.rs.jinja",
        include_str!("../templates/rust_stream_handle_start.rs.jinja"),
    ),
    (
        "rust_stream_handle_next.rs.jinja",
        include_str!("../templates/rust_stream_handle_next.rs.jinja"),
    ),
    (
        "ffi_keep_alive_shim.rs.jinja",
        include_str!("../templates/ffi_keep_alive_shim.rs.jinja"),
    ),
    (
        "rust_writeback_body.rs.jinja",
        include_str!("../templates/rust_writeback_body.rs.jinja"),
    ),
];
