pub(super) static TEMPLATES: &[(&str, &str)] = &[
    (
        "swift_enum_header.jinja",
        include_str!("../templates/swift_enum_header.jinja"),
    ),
    (
        "first_class_struct.swift.jinja",
        include_str!("../templates/first_class_struct.swift.jinja"),
    ),
    (
        "swift_struct_property.swift.jinja",
        include_str!("../templates/swift_struct_property.swift.jinja"),
    ),
    (
        "swift_self_assignment.swift.jinja",
        include_str!("../templates/swift_self_assignment.swift.jinja"),
    ),
    (
        "swift_coding_key.swift.jinja",
        include_str!("../templates/swift_coding_key.swift.jinja"),
    ),
    (
        "swift_decode_optional_assignment.swift.jinja",
        include_str!("../templates/swift_decode_optional_assignment.swift.jinja"),
    ),
    (
        "swift_decode_default_assignment.swift.jinja",
        include_str!("../templates/swift_decode_default_assignment.swift.jinja"),
    ),
    (
        "swift_decode_required_assignment.swift.jinja",
        include_str!("../templates/swift_decode_required_assignment.swift.jinja"),
    ),
    (
        "swift_into_rust_json_return.swift.jinja",
        include_str!("../templates/swift_into_rust_json_return.swift.jinja"),
    ),
    (
        "swift_bridge_constructor_return.swift.jinja",
        include_str!("../templates/swift_bridge_constructor_return.swift.jinja"),
    ),
    (
        "swift_enum_decl.swift.jinja",
        include_str!("../templates/swift_enum_decl.swift.jinja"),
    ),
    (
        "swift_enum_raw_decl.swift.jinja",
        include_str!("../templates/swift_enum_raw_decl.swift.jinja"),
    ),
    (
        "swift_enum_into_rust.swift.jinja",
        include_str!("../templates/swift_enum_into_rust.swift.jinja"),
    ),
    (
        "swift_tagged_codable.swift.jinja",
        include_str!("../templates/swift_tagged_codable.swift.jinja"),
    ),
    (
        "swift_untagged_codable.swift.jinja",
        include_str!("../templates/swift_untagged_codable.swift.jinja"),
    ),
    (
        "swift_tagged_coding_key_case.swift.jinja",
        include_str!("../templates/swift_tagged_coding_key_case.swift.jinja"),
    ),
    (
        "swift_tagged_decode_payload_case.swift.jinja",
        include_str!("../templates/swift_tagged_decode_payload_case.swift.jinja"),
    ),
    (
        "swift_tagged_decode_unit_case.swift.jinja",
        include_str!("../templates/swift_tagged_decode_unit_case.swift.jinja"),
    ),
    (
        "swift_tagged_encode_field.swift.jinja",
        include_str!("../templates/swift_tagged_encode_field.swift.jinja"),
    ),
    (
        "swift_tagged_encode_payload_case.swift.jinja",
        include_str!("../templates/swift_tagged_encode_payload_case.swift.jinja"),
    ),
    (
        "swift_tagged_encode_unit_case.swift.jinja",
        include_str!("../templates/swift_tagged_encode_unit_case.swift.jinja"),
    ),
    (
        "swift_untagged_decode_attempt.swift.jinja",
        include_str!("../templates/swift_untagged_decode_attempt.swift.jinja"),
    ),
    (
        "swift_untagged_encode_case.swift.jinja",
        include_str!("../templates/swift_untagged_encode_case.swift.jinja"),
    ),
    (
        "swift_error_extension.swift.jinja",
        include_str!("../templates/swift_error_extension.swift.jinja"),
    ),
    (
        "swift_error_property.swift.jinja",
        include_str!("../templates/swift_error_property.swift.jinja"),
    ),
    (
        "swift_error_property_case.swift.jinja",
        include_str!("../templates/swift_error_property_case.swift.jinja"),
    ),
    (
        "swift_client_class.swift.jinja",
        include_str!("../templates/swift_client_class.swift.jinja"),
    ),
    (
        "swift_client_method.swift.jinja",
        include_str!("../templates/swift_client_method.swift.jinja"),
    ),
    (
        "swift_client_method_bytes_body.swift.jinja",
        include_str!("../templates/swift_client_method_bytes_body.swift.jinja"),
    ),
    (
        "swift_client_method_dto_return_body.swift.jinja",
        include_str!("../templates/swift_client_method_dto_return_body.swift.jinja"),
    ),
    (
        "swift_client_method_return_body.swift.jinja",
        include_str!("../templates/swift_client_method_return_body.swift.jinja"),
    ),
    (
        "swift_client_method_unit_body.swift.jinja",
        include_str!("../templates/swift_client_method_unit_body.swift.jinja"),
    ),
    (
        "swift_async_forwarder.swift.jinja",
        include_str!("../templates/swift_async_forwarder.swift.jinja"),
    ),
    (
        "swift_sync_forwarder.swift.jinja",
        include_str!("../templates/swift_sync_forwarder.swift.jinja"),
    ),
    (
        "swift_forwarder_conversion_line.swift.jinja",
        include_str!("../templates/swift_forwarder_conversion_line.swift.jinja"),
    ),
    (
        "swift_forwarder_decode_json_body.swift.jinja",
        include_str!("../templates/swift_forwarder_decode_json_body.swift.jinja"),
    ),
    (
        "swift_forwarder_dto_return_body.swift.jinja",
        include_str!("../templates/swift_forwarder_dto_return_body.swift.jinja"),
    ),
    (
        "swift_forwarder_let_return_body.swift.jinja",
        include_str!("../templates/swift_forwarder_let_return_body.swift.jinja"),
    ),
    (
        "swift_forwarder_result_return_body.swift.jinja",
        include_str!("../templates/swift_forwarder_result_return_body.swift.jinja"),
    ),
    (
        "swift_forwarder_unit_body.swift.jinja",
        include_str!("../templates/swift_forwarder_unit_body.swift.jinja"),
    ),
    (
        "swift_sync_forwarder_client_return_body.swift.jinja",
        include_str!("../templates/swift_sync_forwarder_client_return_body.swift.jinja"),
    ),
    (
        "swift_sync_forwarder_decode_json_body.swift.jinja",
        include_str!("../templates/swift_sync_forwarder_decode_json_body.swift.jinja"),
    ),
    (
        "swift_sync_forwarder_decode_optional_json_body.swift.jinja",
        include_str!("../templates/swift_sync_forwarder_decode_optional_json_body.swift.jinja"),
    ),
    (
        "swift_sync_forwarder_dto_return_body.swift.jinja",
        include_str!("../templates/swift_sync_forwarder_dto_return_body.swift.jinja"),
    ),
    (
        "swift_sync_forwarder_unit_enum_return_body.swift.jinja",
        include_str!("../templates/swift_sync_forwarder_unit_enum_return_body.swift.jinja"),
    ),
    (
        "swift_sync_forwarder_result_return_body.swift.jinja",
        include_str!("../templates/swift_sync_forwarder_result_return_body.swift.jinja"),
    ),
    (
        "swift_from_json_decode.swift.jinja",
        include_str!("../templates/swift_from_json_decode.swift.jinja"),
    ),
    (
        "swift_from_json_bridge.swift.jinja",
        include_str!("../templates/swift_from_json_bridge.swift.jinja"),
    ),
    (
        "swift_json_string_overload.swift.jinja",
        include_str!("../templates/swift_json_string_overload.swift.jinja"),
    ),
    (
        "swift_json_decode_line.swift.jinja",
        include_str!("../templates/swift_json_decode_line.swift.jinja"),
    ),
    (
        "enum_case_raw_value.swift.jinja",
        include_str!("../templates/enum_case_raw_value.swift.jinja"),
    ),
    (
        "swift_bytes_string_overload.jinja",
        include_str!("../templates/swift_bytes_string_overload.jinja"),
    ),
    (
        "swift_bytes_array_overload.jinja",
        include_str!("../templates/swift_bytes_array_overload.jinja"),
    ),
    (
        "swift_path_overload.jinja",
        include_str!("../templates/swift_path_overload.jinja"),
    ),
    (
        "swift_trailing_param.jinja",
        include_str!("../templates/swift_trailing_param.jinja"),
    ),
    (
        "swift_trailing_param_optional_default.jinja",
        include_str!("../templates/swift_trailing_param_optional_default.jinja"),
    ),
    (
        "swift_trailing_arg.jinja",
        include_str!("../templates/swift_trailing_arg.jinja"),
    ),
    (
        "swift_file_header.swift.jinja",
        include_str!("../templates/swift_file_header.swift.jinja"),
    ),
    (
        "swift_module_header.swift.jinja",
        include_str!("../templates/swift_module_header.swift.jinja"),
    ),
    (
        "swift_sendable_conformance.swift.jinja",
        include_str!("../templates/swift_sendable_conformance.swift.jinja"),
    ),
    (
        "swift_plugin_bridge_protocol.swift.jinja",
        include_str!("../templates/swift_plugin_bridge_protocol.swift.jinja"),
    ),
    (
        "swift_trait_bridge_file.swift.jinja",
        include_str!("../templates/swift_trait_bridge_file.swift.jinja"),
    ),
    (
        "swift_trait_protocol_method.swift.jinja",
        include_str!("../templates/swift_trait_protocol_method.swift.jinja"),
    ),
    (
        "swift_bridge_protocol_open.swift.jinja",
        include_str!("../templates/swift_bridge_protocol_open.swift.jinja"),
    ),
    (
        "swift_bridge_protocol_method.swift.jinja",
        include_str!("../templates/swift_bridge_protocol_method.swift.jinja"),
    ),
    (
        "swift_bridge_protocol_default_open.swift.jinja",
        include_str!("../templates/swift_bridge_protocol_default_open.swift.jinja"),
    ),
    (
        "swift_bridge_protocol_default_method.swift.jinja",
        include_str!("../templates/swift_bridge_protocol_default_method.swift.jinja"),
    ),
    (
        "swift_bridge_adapter_open.swift.jinja",
        include_str!("../templates/swift_bridge_adapter_open.swift.jinja"),
    ),
    (
        "swift_bridge_adapter_method_open.swift.jinja",
        include_str!("../templates/swift_bridge_adapter_method_open.swift.jinja"),
    ),
    (
        "swift_bridge_adapter_method_close.swift.jinja",
        include_str!("../templates/swift_bridge_adapter_method_close.swift.jinja"),
    ),
    (
        "swift_bridge_adapter_void_return.swift.jinja",
        include_str!("../templates/swift_bridge_adapter_void_return.swift.jinja"),
    ),
    (
        "swift_bridge_result_helper_open.swift.jinja",
        include_str!("../templates/swift_bridge_result_helper_open.swift.jinja"),
    ),
    (
        "swift_bridge_result_unit_case.swift.jinja",
        include_str!("../templates/swift_bridge_result_unit_case.swift.jinja"),
    ),
    (
        "swift_bridge_result_newtype_case.swift.jinja",
        include_str!("../templates/swift_bridge_result_newtype_case.swift.jinja"),
    ),
    (
        "swift_bridge_json_escape_helper.swift.jinja",
        include_str!("../templates/swift_bridge_json_escape_helper.swift.jinja"),
    ),
    (
        "swift_bridge_factory.swift.jinja",
        include_str!("../templates/swift_bridge_factory.swift.jinja"),
    ),
    (
        "swift_bridge_options_forwarder.swift.jinja",
        include_str!("../templates/swift_bridge_options_forwarder.swift.jinja"),
    ),
    (
        "swift_trait_default_method.swift.jinja",
        include_str!("../templates/swift_trait_default_method.swift.jinja"),
    ),
    (
        "swift_trait_adapter_method.swift.jinja",
        include_str!("../templates/swift_trait_adapter_method.swift.jinja"),
    ),
    (
        "swift_trait_adapter_direct_body.swift.jinja",
        include_str!("../templates/swift_trait_adapter_direct_body.swift.jinja"),
    ),
    (
        "swift_trait_adapter_error_body.swift.jinja",
        include_str!("../templates/swift_trait_adapter_error_body.swift.jinja"),
    ),
    (
        "swift_trait_adapter_excluded_success.swift.jinja",
        include_str!("../templates/swift_trait_adapter_excluded_success.swift.jinja"),
    ),
    (
        "swift_trait_adapter_success.swift.jinja",
        include_str!("../templates/swift_trait_adapter_success.swift.jinja"),
    ),
    (
        "swift_trait_bridge_overloads.swift.jinja",
        include_str!("../templates/swift_trait_bridge_overloads.swift.jinja"),
    ),
    (
        "swift_trait_register_overload.swift.jinja",
        include_str!("../templates/swift_trait_register_overload.swift.jinja"),
    ),
    (
        "swift_trait_unregister_overload.swift.jinja",
        include_str!("../templates/swift_trait_unregister_overload.swift.jinja"),
    ),
    (
        "swift_trait_forwarder_clear.swift.jinja",
        include_str!("../templates/swift_trait_forwarder_clear.swift.jinja"),
    ),
    (
        "swift_trait_forwarder_register.swift.jinja",
        include_str!("../templates/swift_trait_forwarder_register.swift.jinja"),
    ),
    (
        "swift_trait_forwarder_unregister.swift.jinja",
        include_str!("../templates/swift_trait_forwarder_unregister.swift.jinja"),
    ),
    (
        "swift_inbound_box_class_open.swift.jinja",
        include_str!("../templates/swift_inbound_box_class_open.swift.jinja"),
    ),
    (
        "swift_inbound_box_delegate_method.swift.jinja",
        include_str!("../templates/swift_inbound_box_delegate_method.swift.jinja"),
    ),
    (
        "swift_inbound_box_delegate_protocol_open.swift.jinja",
        include_str!("../templates/swift_inbound_box_delegate_protocol_open.swift.jinja"),
    ),
    (
        "swift_inbound_box_method.swift.jinja",
        include_str!("../templates/swift_inbound_box_method.swift.jinja"),
    ),
    (
        "swift_inbound_box_preamble.swift.jinja",
        include_str!("../templates/swift_inbound_box_preamble.swift.jinja"),
    ),
    (
        "swift_function_param_box_class_open.swift.jinja",
        include_str!("../templates/swift_function_param_box_class_open.swift.jinja"),
    ),
    (
        "swift_function_param_box_plugin_shims.swift.jinja",
        include_str!("../templates/swift_function_param_box_plugin_shims.swift.jinja"),
    ),
    (
        "swift_function_param_box_method_open.swift.jinja",
        include_str!("../templates/swift_function_param_box_method_open.swift.jinja"),
    ),
    (
        "swift_function_param_box_param_signature.swift.jinja",
        include_str!("../templates/swift_function_param_box_param_signature.swift.jinja"),
    ),
    (
        "swift_function_param_box_catching_body.swift.jinja",
        include_str!("../templates/swift_function_param_box_catching_body.swift.jinja"),
    ),
    (
        "swift_function_param_box_method_close.swift.jinja",
        include_str!("../templates/swift_function_param_box_method_close.swift.jinja"),
    ),
    (
        "swift_function_param_box_setup_line.swift.jinja",
        include_str!("../templates/swift_function_param_box_setup_line.swift.jinja"),
    ),
    (
        "swift_function_param_box_throwing_result.swift.jinja",
        include_str!("../templates/swift_function_param_box_throwing_result.swift.jinja"),
    ),
    (
        "swift_function_param_box_throwing_unit.swift.jinja",
        include_str!("../templates/swift_function_param_box_throwing_unit.swift.jinja"),
    ),
    (
        "swift_class_header.swift.jinja",
        include_str!("../templates/swift_class_header.swift.jinja"),
    ),
    (
        "swift_init.swift.jinja",
        include_str!("../templates/swift_init.swift.jinja"),
    ),
    (
        "swift_deinit.swift.jinja",
        include_str!("../templates/swift_deinit.swift.jinja"),
    ),
    (
        "swift_configurator.swift.jinja",
        include_str!("../templates/swift_configurator.swift.jinja"),
    ),
    (
        "swift_config_method.swift.jinja",
        include_str!("../templates/swift_config_method.swift.jinja"),
    ),
    (
        "swift_registration.swift.jinja",
        include_str!("../templates/swift_registration.swift.jinja"),
    ),
    (
        "swift_registration_variant.swift.jinja",
        include_str!("../templates/swift_registration_variant.swift.jinja"),
    ),
    (
        "swift_registration_variant_delegate.swift.jinja",
        include_str!("../templates/swift_registration_variant_delegate.swift.jinja"),
    ),
    (
        "swift_silgen_callback.swift.jinja",
        include_str!("../templates/swift_silgen_callback.swift.jinja"),
    ),
    (
        "swift_entrypoint.swift.jinja",
        include_str!("../templates/swift_entrypoint.swift.jinja"),
    ),
    (
        "swift_class_footer.swift.jinja",
        include_str!("../templates/swift_class_footer.swift.jinja"),
    ),
    (
        "swift_ref_extension_open.swift.jinja",
        include_str!("../templates/swift_ref_extension_open.swift.jinja"),
    ),
    (
        "swift_ref_string_alias_property.swift.jinja",
        include_str!("../templates/swift_ref_string_alias_property.swift.jinja"),
    ),
    (
        "swift_ref_extension_inheritance_comment.swift.jinja",
        include_str!("../templates/swift_ref_extension_inheritance_comment.swift.jinja"),
    ),
];
