pub(super) static TEMPLATES: &[(&str, &str)] = &[
    (
        "struct_newtype.jinja",
        include_str!("../templates/struct_newtype.jinja"),
    ),
    ("impl_header.jinja", include_str!("../templates/impl_header.jinja")),
    (
        "fn_new_signature.jinja",
        include_str!("../templates/fn_new_signature.jinja"),
    ),
    ("fn_getter.jinja", include_str!("../templates/fn_getter.jinja")),
    (
        "getter_json_bridge.jinja",
        include_str!("../templates/getter_json_bridge.jinja"),
    ),
    (
        "getter_optional_bytes.jinja",
        include_str!("../templates/getter_optional_bytes.jinja"),
    ),
    ("getter_bytes.jinja", include_str!("../templates/getter_bytes.jinja")),
    (
        "getter_serde_optional.jinja",
        include_str!("../templates/getter_serde_optional.jinja"),
    ),
    ("getter_serde.jinja", include_str!("../templates/getter_serde.jinja")),
    (
        "getter_simple_clone.jinja",
        include_str!("../templates/getter_simple_clone.jinja"),
    ),
    (
        "getter_duration.jinja",
        include_str!("../templates/getter_duration.jinja"),
    ),
    (
        "getter_optional_duration.jinja",
        include_str!("../templates/getter_optional_duration.jinja"),
    ),
    (
        "getter_optional_named.jinja",
        include_str!("../templates/getter_optional_named.jinja"),
    ),
    ("getter_named.jinja", include_str!("../templates/getter_named.jinja")),
    (
        "getter_vec_named_optional.jinja",
        include_str!("../templates/getter_vec_named_optional.jinja"),
    ),
    (
        "getter_vec_named.jinja",
        include_str!("../templates/getter_vec_named.jinja"),
    ),
    (
        "getter_vec_complex_serde_optional.jinja",
        include_str!("../templates/getter_vec_complex_serde_optional.jinja"),
    ),
    (
        "getter_vec_complex_serde.jinja",
        include_str!("../templates/getter_vec_complex_serde.jinja"),
    ),
    (
        "getter_vec_complex_skip.jinja",
        include_str!("../templates/getter_vec_complex_skip.jinja"),
    ),
    (
        "getter_vec_primitive_serde_optional.jinja",
        include_str!("../templates/getter_vec_primitive_serde_optional.jinja"),
    ),
    (
        "getter_vec_primitive_serde.jinja",
        include_str!("../templates/getter_vec_primitive_serde.jinja"),
    ),
    (
        "getter_vec_primitive_clone.jinja",
        include_str!("../templates/getter_vec_primitive_clone.jinja"),
    ),
    (
        "getter_enum_string_optional.jinja",
        include_str!("../templates/getter_enum_string_optional.jinja"),
    ),
    (
        "getter_enum_string.jinja",
        include_str!("../templates/getter_enum_string.jinja"),
    ),
    (
        "getter_vec_enum_string_optional.jinja",
        include_str!("../templates/getter_vec_enum_string_optional.jinja"),
    ),
    (
        "getter_vec_enum_string.jinja",
        include_str!("../templates/getter_vec_enum_string.jinja"),
    ),
    (
        "getter_char_optional.jinja",
        include_str!("../templates/getter_char_optional.jinja"),
    ),
    ("getter_char.jinja", include_str!("../templates/getter_char.jinja")),
    (
        "getter_path_optional.jinja",
        include_str!("../templates/getter_path_optional.jinja"),
    ),
    ("getter_path.jinja", include_str!("../templates/getter_path.jinja")),
    (
        "getter_string_like_debug_optional.jinja",
        include_str!("../templates/getter_string_like_debug_optional.jinja"),
    ),
    (
        "getter_string_like_debug.jinja",
        include_str!("../templates/getter_string_like_debug.jinja"),
    ),
    (
        "getter_string_like_serde_optional.jinja",
        include_str!("../templates/getter_string_like_serde_optional.jinja"),
    ),
    (
        "getter_string_like_serde.jinja",
        include_str!("../templates/getter_string_like_serde.jinja"),
    ),
    (
        "getter_string_cow.jinja",
        include_str!("../templates/getter_string_cow.jinja"),
    ),
    (
        "getter_string_cow_optional.jinja",
        include_str!("../templates/getter_string_cow_optional.jinja"),
    ),
    (
        "getter_skip_comment.jinja",
        include_str!("../templates/getter_skip_comment.jinja"),
    ),
    (
        "default_construction_var.jinja",
        include_str!("../templates/default_construction_var.jinja"),
    ),
    (
        "default_field_excluded.jinja",
        include_str!("../templates/default_field_excluded.jinja"),
    ),
    (
        "default_field_inner_excluded.jinja",
        include_str!("../templates/default_field_inner_excluded.jinja"),
    ),
    (
        "default_field_json_bridge.jinja",
        include_str!("../templates/default_field_json_bridge.jinja"),
    ),
    (
        "default_field_enum_skip.jinja",
        include_str!("../templates/default_field_enum_skip.jinja"),
    ),
    (
        "default_field_named_optional_boxed.jinja",
        include_str!("../templates/default_field_named_optional_boxed.jinja"),
    ),
    (
        "default_field_named_optional_arc.jinja",
        include_str!("../templates/default_field_named_optional_arc.jinja"),
    ),
    (
        "default_field_named_optional_plain.jinja",
        include_str!("../templates/default_field_named_optional_plain.jinja"),
    ),
    (
        "default_field_named_boxed.jinja",
        include_str!("../templates/default_field_named_boxed.jinja"),
    ),
    (
        "default_field_named_arc.jinja",
        include_str!("../templates/default_field_named_arc.jinja"),
    ),
    (
        "default_field_named_plain.jinja",
        include_str!("../templates/default_field_named_plain.jinja"),
    ),
    (
        "default_field_vec_named_enum_skip.jinja",
        include_str!("../templates/default_field_vec_named_enum_skip.jinja"),
    ),
    (
        "default_field_vec_named_arc_optional.jinja",
        include_str!("../templates/default_field_vec_named_arc_optional.jinja"),
    ),
    (
        "default_field_vec_named_plain_optional.jinja",
        include_str!("../templates/default_field_vec_named_plain_optional.jinja"),
    ),
    (
        "default_field_vec_named_arc_plain.jinja",
        include_str!("../templates/default_field_vec_named_arc_plain.jinja"),
    ),
    (
        "default_field_vec_named_plain.jinja",
        include_str!("../templates/default_field_vec_named_plain.jinja"),
    ),
    (
        "default_field_vec_serde.jinja",
        include_str!("../templates/default_field_vec_serde.jinja"),
    ),
    (
        "default_field_string_like.jinja",
        include_str!("../templates/default_field_string_like.jinja"),
    ),
    (
        "default_field_string_like_non_serde_comment.jinja",
        include_str!("../templates/default_field_string_like_non_serde_comment.jinja"),
    ),
    (
        "default_field_string_like_optional_serde.jinja",
        include_str!("../templates/default_field_string_like_optional_serde.jinja"),
    ),
    (
        "default_field_string_like_serde.jinja",
        include_str!("../templates/default_field_string_like_serde.jinja"),
    ),
    (
        "default_field_bytes_assign.jinja",
        include_str!("../templates/default_field_bytes_assign.jinja"),
    ),
    (
        "default_field_duration_assign.jinja",
        include_str!("../templates/default_field_duration_assign.jinja"),
    ),
    (
        "default_field_optional_duration_assign.jinja",
        include_str!("../templates/default_field_optional_duration_assign.jinja"),
    ),
    (
        "default_field_generic_assign.jinja",
        include_str!("../templates/default_field_generic_assign.jinja"),
    ),
    (
        "dc_construct_target.jinja",
        include_str!("../templates/dc_construct_target.jinja"),
    ),
    (
        "struct_literal_open.jinja",
        include_str!("../templates/struct_literal_open.jinja"),
    ),
    (
        "default_construction_let_mut.jinja",
        include_str!("../templates/default_construction_let_mut.jinja"),
    ),
    (
        "default_construction_return.jinja",
        include_str!("../templates/default_construction_return.jinja"),
    ),
    (
        "default_field_arc_assign.jinja",
        include_str!("../templates/default_field_arc_assign.jinja"),
    ),
    (
        "default_field_boxed_assign.jinja",
        include_str!("../templates/default_field_boxed_assign.jinja"),
    ),
    (
        "default_field_enum_assign.jinja",
        include_str!("../templates/default_field_enum_assign.jinja"),
    ),
    (
        "default_field_excluded_comment.jinja",
        include_str!("../templates/default_field_excluded_comment.jinja"),
    ),
    (
        "default_field_json_bridge_read.jinja",
        include_str!("../templates/default_field_json_bridge_read.jinja"),
    ),
    (
        "default_field_optional_arc_assign.jinja",
        include_str!("../templates/default_field_optional_arc_assign.jinja"),
    ),
    (
        "default_field_optional_boxed_assign.jinja",
        include_str!("../templates/default_field_optional_boxed_assign.jinja"),
    ),
    (
        "default_field_optional_plain_assign.jinja",
        include_str!("../templates/default_field_optional_plain_assign.jinja"),
    ),
    (
        "default_field_optional_char_assign.jinja",
        include_str!("../templates/default_field_optional_char_assign.jinja"),
    ),
    (
        "default_field_char_assign.jinja",
        include_str!("../templates/default_field_char_assign.jinja"),
    ),
    (
        "default_field_plain_assign.jinja",
        include_str!("../templates/default_field_plain_assign.jinja"),
    ),
    (
        "default_field_vec_named_unwrap_plain.jinja",
        include_str!("../templates/default_field_vec_named_unwrap_plain.jinja"),
    ),
    (
        "default_field_vec_named_unwrap.jinja",
        include_str!("../templates/default_field_vec_named_unwrap.jinja"),
    ),
    (
        "default_field_vec_non_primitive_comment.jinja",
        include_str!("../templates/default_field_vec_non_primitive_comment.jinja"),
    ),
    (
        "default_field_vec_primitive_assign.jinja",
        include_str!("../templates/default_field_vec_primitive_assign.jinja"),
    ),
    (
        "default_field_vec_serde_round_trip.jinja",
        include_str!("../templates/default_field_vec_serde_round_trip.jinja"),
    ),
];
